{
  "name": "control_dash — Power BI Desktop",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "ru-RU",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "ru-RU",
    "tables": [
      {
        "name": "metrika_stats",
        "lineageTag": "ed5cd1e1-5e86-4cb5-b3d3-726c8391e891",
        "columns": [
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date",
            "formatString": "Long Date",
            "lineageTag": "539c7c2d-f6b1-40de-922f-0b4bac667042",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "sumVisits",
            "dataType": "double",
            "sourceColumn": "sumVisits",
            "lineageTag": "9609cd10-9879-47bc-8b68-0104ffccbd79",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "bounceRate",
            "dataType": "double",
            "sourceColumn": "bounceRate",
            "lineageTag": "34fd413a-7482-484c-a79e-7c58b979bd12",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "avgPageViews",
            "dataType": "double",
            "sourceColumn": "avgPageViews",
            "lineageTag": "9e9b97cb-0afa-4146-93c7-e35e5c97040f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "tag",
            "dataType": "string",
            "sourceColumn": "tag",
            "lineageTag": "9d55e86b-6dd1-4c44-8349-3280251d4d61",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_290534052_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_290534052_LSC",
            "lineageTag": "81647be5-c3e9-4100-82ea-7d4171a9cb66",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_290532335_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_290532335_LSC",
            "lineageTag": "494a1d62-029e-4ee3-93cc-cdb63f6a4d25",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_290531916_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_290531916_LSC",
            "lineageTag": "64c4b1c5-344d-42fb-a313-2cee50efda45",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_291210068_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_291210068_LSC",
            "lineageTag": "5768eab9-ae42-44d4-9eee-9ebcdac89f46",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_291212676_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_291212676_LSC",
            "lineageTag": "d24c5e52-b465-4389-9b0c-38b1a5235378",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_291214181_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_291214181_LSC",
            "lineageTag": "69128cad-ce9f-418d-95b8-0631acc838b8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "utm_campaign",
            "dataType": "string",
            "sourceColumn": "utm_campaign",
            "lineageTag": "b8d0584c-49b0-46b2-bc11-5222b65fe582",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "utm_source",
            "dataType": "string",
            "sourceColumn": "utm_source",
            "lineageTag": "41552a4d-58dc-4860-8071-d734274af26f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "utm_medium",
            "dataType": "string",
            "sourceColumn": "utm_medium",
            "lineageTag": "930b0419-d65e-4a1e-a85d-f37aa90ea964",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CampaignId",
            "dataType": "string",
            "sourceColumn": "CampaignId",
            "lineageTag": "14e21f35-a23d-45d5-9a26-a4bae816a5ee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CampaignName",
            "dataType": "string",
            "sourceColumn": "CampaignName",
            "lineageTag": "1404556f-098f-4175-ae1a-3904c2d5220a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "state",
            "dataType": "string",
            "sourceColumn": "state",
            "lineageTag": "a38cfc57-b865-4d94-b8b2-7b7735091d8f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Impressions",
            "dataType": "int64",
            "sourceColumn": "Impressions",
            "formatString": "0",
            "lineageTag": "f1cf402f-0729-4c2c-b126-ab2794d52a72",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Clicks",
            "dataType": "int64",
            "sourceColumn": "Clicks",
            "formatString": "0",
            "lineageTag": "d7153693-2d4f-424a-86d2-3620a84f70b6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Cost",
            "dataType": "double",
            "sourceColumn": "Cost",
            "lineageTag": "e9e7793e-ce7b-495a-b4d7-503a755900a5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "NewTypes",
            "dataType": "string",
            "sourceColumn": "NewTypes",
            "lineageTag": "4c32dccb-fa6b-45e9-bee5-a6fd878f542f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NewEngines",
            "dataType": "string",
            "sourceColumn": "NewEngines",
            "lineageTag": "d44b4176-c419-45e9-9e09-618436cda03f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversion_290534052_ASS",
            "dataType": "double",
            "sourceColumn": "Conversion_290534052_ASS",
            "lineageTag": "3d4feece-4632-405b-9234-efe7c6a69cec",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversion_290532335_ASS",
            "dataType": "double",
            "sourceColumn": "Conversion_290532335_ASS",
            "lineageTag": "a4f95c26-ba7b-44ca-a87e-bc3cf1f35b5d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversion_290531916_ASS",
            "dataType": "double",
            "sourceColumn": "Conversion_290531916_ASS",
            "lineageTag": "465e273e-2170-471d-9df2-4b22b19a385a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversion_291210068_ASS",
            "dataType": "double",
            "sourceColumn": "Conversion_291210068_ASS",
            "lineageTag": "1c73ba6c-c7c1-4fe5-bf6e-edd8433c4d08",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversion_291212676_ASS",
            "dataType": "double",
            "sourceColumn": "Conversion_291212676_ASS",
            "lineageTag": "d921cb0b-3b12-45cf-ab04-f566400cf61f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversion_291214181_ASS",
            "dataType": "double",
            "sourceColumn": "Conversion_291214181_ASS",
            "lineageTag": "0abae29e-2e14-4412-b1b0-0265e39c7172",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED('Date'[Year Month])",
            "lineageTag": "c34cc374-244d-40e5-84f8-6af272a7b504",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "metrika_stats-ed2a1afc-6906-4996-9025-a3d8ca57fd63",
            "mode": "import",
            "queryGroup": "4 Получаем главный датасет метрики",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
                "    public_control_metrika_stats = Источник{[Schema=\"public\",Item=\"control_metrika_stats\"]}[Data],",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(public_control_metrika_stats,{{\"date\", type date}}),",
                "    #\"Замененное значение\" = Table.ReplaceValue(#\"Измененный тип\",\"N-\",\"\",Replacer.ReplaceText,{\"directID\"}),",
                "    #\"Вставлено: объединенный столбец\" = Table.AddColumn(#\"Замененное значение\", \"Сведено\", each Text.Combine({[lastsignTrafficSourceName], [lastSignSourceEngineName]}, \"\"), type text),",
                "    #\"Условный столбец добавлен\" = Table.AddColumn(#\"Вставлено: объединенный столбец\", \"utm_campaign\", each if [Сведено] = \"Переходы по рекламеЯндекс: Директ\" then [directID] else [lastSignUTMCampaign]),",
                "    #\"Условный столбец добавлен1\" = Table.AddColumn(#\"Условный столбец добавлен\", \"utm_source\", each if [Сведено] = \"Переходы по рекламеЯндекс: Директ\" then \"yandex\" else [lastSignUTMSource]),",
                "    #\"Условный столбец добавлен2\" = Table.AddColumn(#\"Условный столбец добавлен1\", \"utm_medium\", each if [lastSignUTMMedium] = \"Переходы по рекламеЯндекс: Директ\" then \"cpc\" else [lastSignUTMMedium]),",
                "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Условный столбец добавлен2\",{\"Сведено\", \"lastSignUTMSource\", \"lastSignUTMMedium\", \"lastSignUTMCampaign\"}),",
                "    #\"Измененный тип1\" = Table.TransformColumnTypes(#\"Удаленные столбцы\",{{\"utm_campaign\", type text}, {\"utm_source\", type text}, {\"utm_medium\", type text}}),",
                "    #\"ДЖОЙН all_stats\" = Table.NestedJoin(#\"Измененный тип1\", {\"tag\", \"utm_source\", \"utm_medium\", \"utm_campaign\"}, all_camps, {\"tag\", \"utm_source\", \"utm_medium\", \"utm_campaign\"}, \"all_camps\", JoinKind.LeftOuter),",
                "    #\"Развернутый элемент all_camps\" = Table.ExpandTableColumn(#\"ДЖОЙН all_stats\", \"all_camps\", {\"CampaignId\", \"CampaignName\", \"state\"}, {\"CampaignId\", \"CampaignName\", \"state\"}),",
                "    #\"Добавленный запрос\" = Table.Combine({#\"Развернутый элемент all_camps\", all_stats}),",
                "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавленный запрос\",{{\"lastsignTrafficSourceName\", \"TrafficType\"}}),",
                "    #\"Замененное значение0\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"Переходы из мессенджеров\",\"Мессенджеры\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение0\",\"Переходы из поисковых систем\",\"Поисковые системы\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"Переходы из рекомендательных систем\",\"Рекомендательные системы\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"Переходы из социальных сетей\",\"Соцсети\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"Переходы с почтовых рассылок\",\"E-Mail Маркетинг\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"Замененное значение5\" = Table.ReplaceValue(#\"Замененное значение4\",\"Переходы с сохранённых страниц\",\"Сохраненные страницы\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"Замененное значение6\" = Table.ReplaceValue(#\"Замененное значение5\",\"Переходы по ссылкам на сайтах\",\"Ссылки на иных сайтах\",Replacer.ReplaceText,{\"TrafficType\"}),",
                "    #\"ДЖОЙН paid_source_names\" = Table.NestedJoin(#\"Замененное значение6\", {\"utm_source\"}, paid_source_names, {\"utm_source\"}, \"Paid Source Names\", JoinKind.LeftOuter),",
                "    #\"Развернутый элемент Paid Source Names\" = Table.ExpandTableColumn(#\"ДЖОЙН paid_source_names\", \"Paid Source Names\", {\"lastsignTrafficSourceName\", \"lastSignSourceEngineName\"}, {\"lastsignTrafficSourceName\", \"lastSignSourceEngineName.1\"}),",
                "    #\"Условный столбец добавлен3\" = Table.AddColumn(#\"Развернутый элемент Paid Source Names\", \"NewTypes\", each if [lastsignTrafficSourceName] = null then [TrafficType] else [lastsignTrafficSourceName]),",
                "    #\"Условный столбец добавлен4\" = Table.AddColumn(#\"Условный столбец добавлен3\", \"NewEngines\", each if [lastSignSourceEngineName.1] = null then [lastSignSourceEngineName] else [lastSignSourceEngineName.1]),",
                "    #\"Удаленные столбцы1\" = Table.RemoveColumns(#\"Условный столбец добавлен4\",{\"TrafficType\", \"lastSignSourceEngineName\", \"startURL\", \"Login\", \"directID\", \"lastsignTrafficSourceName\", \"lastSignSourceEngineName.1\"}),",
                "    #\"Измененный тип2\" = Table.TransformColumnTypes(#\"Удаленные столбцы1\",{{\"NewTypes\", type text}, {\"NewEngines\", type text}}),",
                "    #\"Удаленные столбцы2\" = Table.RemoveColumns(#\"Измененный тип2\",{\"index\"}),",
                "    #\"Текст в нижнем регистре\" = Table.TransformColumns(#\"Удаленные столбцы2\",{{\"NewEngines\", Text.Lower, type text}}),",
                "    #\"АППЕНД associate_conv\" = Table.Combine({#\"Текст в нижнем регистре\", associate_conv_campaigns, associate_conv_sources}),",
                "    #\"Строки с примененным фильтром\" = Table.SelectRows(#\"АППЕНД associate_conv\", each [NewTypes] <> null and [NewTypes] <> \"\")",
                "in",
                "    #\"Строки с примененным фильтром\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "YTD impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\impr",
            "lineageTag": "b1558515-3b3e-405c-a28d-ebddd23922a3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\impr",
            "lineageTag": "b66f071b-23e3-4e99-aaf0-9ce5789ac347",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\impr",
            "lineageTag": "c623a5a8-69f2-459d-94d5-0bb410c02635",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "01468121-d97c-4af9-bbcd-39f191d3ce8e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Показы]",
              "VAR __ValuePreviousPeriod = [PY impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "86c6ab90-6287-47c8-b3c8-c3f92ff4e276",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY impr],",
              "    [PY impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "9e61a167-6b8c-46b0-b264-b3000c35a011",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "8c4a4edd-e5be-4130-abb4-3b51957bf02f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Показы]",
              "VAR __ValuePreviousPeriod = [PQ impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "9b24b76e-c4a5-4028-a280-3a17dd820058",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ impr],",
              "    [PQ impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "9aeab192-89ed-45e0-89e3-b151f6f33605",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "db09e3f3-3b09-4ef0-bc14-129f66109ae8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Показы]",
              "VAR __ValuePreviousPeriod = [PM impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "99bfbd50-b948-4b20-b614-615c4586ddd0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM impr],",
              "    [PM impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\impr",
            "lineageTag": "35527ded-dd73-4a23-a71e-d17bb5736d3d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD impr],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "e29d5414-3dbe-4e0a-935e-3222672da358",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD impr]",
              "VAR __ValuePreviousPeriod = [PYTD impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "bcd2ca57-cd57-42f4-abad-605f89184a6b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD impr],",
              "    [PYTD impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "f08d9fa1-0b19-4752-8732-9d309f0059ba",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD impr],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "5f4f8f50-b6e7-473e-baab-8b6eb6c47a7e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD impr]",
              "VAR __ValuePreviousPeriod = [PQTD impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "75c0a1eb-3a97-4d0b-b91d-1e5bc70df540",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD impr],",
              "    [PQTD impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "23214dc9-125b-403a-8250-d716d623a77a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD impr],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "e6132f34-e71c-4d2f-b086-5a44517bf9ac",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD impr]",
              "VAR __ValuePreviousPeriod = [PMTD impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "a9afe9eb-4a42-4576-9f9a-50085c245888",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD impr],",
              "    [PMTD impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\impr",
            "lineageTag": "3677b988-14a9-43f6-8eb8-ee08926db4c8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "43bf78a2-57d3-4a3b-936f-1f59fb2453ed",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD impr]",
              "VAR __ValuePreviousPeriod = [PYC impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "49c88117-a924-4092-b5de-246e610464d6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY impr],",
              "    [PYC impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "d9068abc-f003-49ac-b321-ce7be50572d2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "4edca0b6-d1d7-4fa2-a067-4b03e2d136c8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD impr]",
              "VAR __ValuePreviousPeriod = [PQC impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "bf347fce-ceee-49fc-9a70-eac1976b7e0c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ impr],",
              "    [PQC impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "8d8798e1-7004-4b97-a9d3-c8f2fe8141ee",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "aeabe7ee-80b4-4f90-91a1-7f2a6e204b04",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD impr]",
              "VAR __ValuePreviousPeriod = [PMC impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "a5761b29-da2d-4137-afc0-68c0b1d21387",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM impr],",
              "    [PMC impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\impr",
            "lineageTag": "757b5ded-0743-43d7-bbae-758fa7074221",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Показы],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\impr",
            "lineageTag": "850bcf50-a3b3-4a5f-b5eb-231b57668c0f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT impr",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT impr],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\impr",
            "lineageTag": "13f5c3ae-d68e-4aba-8cf9-0b7964dc1c70",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG impr",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT impr]",
              "VAR __ValuePreviousPeriod = [PYMAT impr]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\impr",
            "lineageTag": "02df567c-cbb0-4338-b1fe-f1738c0b650e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % impr",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG impr],",
              "    [PYMAT impr]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\impr",
            "lineageTag": "c86b970b-f01d-4ca3-a8a6-6bf100be4148",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date total\\sum_cost",
            "lineageTag": "64d34b5d-f85b-4e3a-844a-fd9b9890e14f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date total\\sum_cost",
            "lineageTag": "21997caa-cdaf-49a6-baa0-ae5225300861",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date total\\sum_cost",
            "lineageTag": "a1bcd312-8eb9-4a0e-8bbd-13e4af171d20",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "d4a22f80-4d2e-468d-bab2-476d9331cea6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [sum_cost]",
              "VAR __ValuePreviousPeriod = [PY sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "a8f20798-9daa-4440-806b-da0ed94820de",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY sum_cost],",
              "    [PY sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "dd81d2e4-abf4-4379-8239-a8ad3e0e1c31",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "6c929adc-b344-491b-a8ee-3d91774bacb2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [sum_cost]",
              "VAR __ValuePreviousPeriod = [PQ sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "f2aca0a9-1abc-4293-8562-e35fada11ae6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ sum_cost],",
              "    [PQ sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "11b58f36-917b-4c93-9ac1-110e3a950307",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "35bb778e-042a-437c-9b20-da16c9c196d8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [sum_cost]",
              "VAR __ValuePreviousPeriod = [PM sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "f89bbb71-30b8-4052-b023-a184b70887d0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM sum_cost],",
              "    [PM sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\sum_cost",
            "lineageTag": "46741a35-4af1-4a31-adcb-a5cf925a635c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD sum_cost],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "fceec431-6fb1-4ac3-a355-a5335b81cd33",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD sum_cost]",
              "VAR __ValuePreviousPeriod = [PYTD sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "906d748b-5e0c-4923-aa66-6b31fb068458",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD sum_cost],",
              "    [PYTD sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "0b360bdb-2d0b-4d23-81a2-28fee96bdaf4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD sum_cost],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "01cad56f-f8d8-4278-8c83-2f56a5be60ba",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD sum_cost]",
              "VAR __ValuePreviousPeriod = [PQTD sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "4e444487-14d3-41f0-b4c4-cb47996a64bf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD sum_cost],",
              "    [PQTD sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "01300ee9-3ad8-4d43-98c7-ca9246da2fc3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD sum_cost],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "31f49ba5-6d6f-4a54-8c4d-50a29998fe3e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD sum_cost]",
              "VAR __ValuePreviousPeriod = [PMTD sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "0fc8a5e0-b49a-48f1-b20d-035219db56e5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD sum_cost],",
              "    [PMTD sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\sum_cost",
            "lineageTag": "2e00c4fb-5c1f-45f1-9fae-49467c0044d6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "0aedfe05-d03e-46c2-85b9-a4572e927e87",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD sum_cost]",
              "VAR __ValuePreviousPeriod = [PYC sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "486728e7-9fc7-441f-a84f-af23ce16ce84",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY sum_cost],",
              "    [PYC sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "7433e358-df06-40ab-91e2-97c4899bd1fe",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "2fdbaca2-fbe4-4f8f-989f-ff1873a9bc8f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD sum_cost]",
              "VAR __ValuePreviousPeriod = [PQC sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "0aa4a1fb-0d41-4624-a8e0-44fc4dbaf47e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ sum_cost],",
              "    [PQC sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "97419579-dfee-4a5b-ba40-4cf210eee1fd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "f1d50f71-6ce6-4214-a45f-8314dc3fa827",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD sum_cost]",
              "VAR __ValuePreviousPeriod = [PMC sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "26f2c92a-da67-40a8-ab9d-12e214519f5d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM sum_cost],",
              "    [PMC sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\sum_cost",
            "lineageTag": "d6b128ae-e079-4fe3-ad57-1eb7e68a32cb",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [sum_cost],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\sum_cost",
            "lineageTag": "5c2dca4a-074b-44d9-b76e-139604d41ef4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT sum_cost",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT sum_cost],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\sum_cost",
            "lineageTag": "f0f8cf65-de0c-44d3-9d62-cbf679a53163",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG sum_cost",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT sum_cost]",
              "VAR __ValuePreviousPeriod = [PYMAT sum_cost]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\sum_cost",
            "lineageTag": "e85dc4ed-e03f-41f8-b4a3-7314910018cd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % sum_cost",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG sum_cost],",
              "    [PYMAT sum_cost]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\sum_cost",
            "lineageTag": "9c4717e3-5bcb-4548-8313-5d47c4fced4c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "ydirect_extended",
        "lineageTag": "07541975-0bfe-4861-b84a-7e0f2589f0ad",
        "columns": [
          {
            "name": "index",
            "dataType": "int64",
            "sourceColumn": "index",
            "formatString": "0",
            "lineageTag": "e89c3b3b-2e09-4a03-acce-18b1da86ef0a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "4f13981b-a979-4fb2-98df-bee5b7b65e3e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "e4595536-f327-4d2b-aa51-abdc9506dcc2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AvgPageviews",
            "dataType": "double",
            "sourceColumn": "AvgPageviews",
            "lineageTag": "3046571c-ea23-428e-85c4-fcd8111ef149",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "BounceRate",
            "dataType": "double",
            "sourceColumn": "BounceRate",
            "lineageTag": "aa367b44-e2f6-41fe-a06f-8d6cc684eeb7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CampaignType",
            "dataType": "string",
            "sourceColumn": "CampaignType",
            "lineageTag": "3070743c-8d13-45e7-8643-a51fa50e5fe4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CampaignName",
            "dataType": "string",
            "sourceColumn": "CampaignName",
            "lineageTag": "f6fc66d8-a332-4521-bbf0-36044f5e0879",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CampaignId",
            "dataType": "string",
            "sourceColumn": "CampaignId",
            "lineageTag": "b38790bb-9fdb-49ce-9d9c-5aed925b1510",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AdGroupName",
            "dataType": "string",
            "sourceColumn": "AdGroupName",
            "lineageTag": "667e799f-b38c-4164-8b44-ac93272056fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "AdGroupId",
            "dataType": "string",
            "sourceColumn": "AdGroupId",
            "lineageTag": "a564a3d6-13e5-47ef-8dc1-902c7f372daa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Criterion",
            "dataType": "string",
            "sourceColumn": "Criterion",
            "lineageTag": "07bd6aa1-7690-485c-bd1e-82846e5b0af1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CriterionId",
            "dataType": "string",
            "sourceColumn": "CriterionId",
            "lineageTag": "da1bf530-bc79-4ef1-950f-b7fc9a8fe9a3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Impressions",
            "dataType": "int64",
            "sourceColumn": "Impressions",
            "formatString": "0",
            "lineageTag": "ea6bf08c-87c3-4104-88b6-2083c740945f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Clicks",
            "dataType": "int64",
            "sourceColumn": "Clicks",
            "formatString": "0",
            "lineageTag": "c87ee9a5-852c-48a0-868b-dde59af2a6de",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Cost",
            "dataType": "double",
            "sourceColumn": "Cost",
            "lineageTag": "f49fcf57-19a5-47c6-a3c8-298efc6d8108",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Login",
            "dataType": "string",
            "sourceColumn": "Login",
            "lineageTag": "8a787433-76d9-409e-8bf3-e4db8d0d3467",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "tag",
            "dataType": "string",
            "sourceColumn": "tag",
            "lineageTag": "0c202d62-4b21-4d8a-836d-b4fd86cd360f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_290534052_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_290534052_LSC",
            "lineageTag": "29177c7b-40f1-422a-8ad0-ff1188479aa3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_290532335_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_290532335_LSC",
            "lineageTag": "512073ed-8a40-4e86-a2e0-a12294df4d4a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_290531916_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_290531916_LSC",
            "lineageTag": "2ab82c77-8ea8-45ed-b43b-81b084bb4d6e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_291210068_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_291210068_LSC",
            "lineageTag": "fabb11bd-a12f-4e00-af63-ff4e6ceeab4b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_291212676_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_291212676_LSC",
            "lineageTag": "8d6dbb09-b49f-420e-9695-661dc5298c2d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_291214181_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_291214181_LSC",
            "lineageTag": "4dc3a085-fde1-4571-9124-6d4607ff2fd9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "login 2",
            "dataType": "string",
            "sourceColumn": "login",
            "lineageTag": "b7776c4f-77cd-4225-9fc7-792dce391c8a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "custom_dimension",
            "dataType": "string",
            "sourceColumn": "custom_dimension",
            "lineageTag": "80c74743-2ef6-448e-a7fb-34ab8cd8cb43",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "ydirect_extended-a9114429-26f8-48f6-b621-6099462bac8b",
            "mode": "import",
            "queryGroup": "5 Расширенные датасеты по источникам",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
                "    public_control_ydirect_stats = Источник{[Schema=\"public\",Item=\"control_ydirect_stats\"]}[Data]",
                "in",
                "    public_control_ydirect_stats"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "_measures",
        "lineageTag": "34314daa-770f-4e93-b178-2e96a0bcd498",
        "columns": [
          {
            "name": "_measures",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "_measures",
            "lineageTag": "9f530c30-41f4-4947-8622-9cbc90ce3e0f",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_measures-2a1a3396-962a-4d92-be0f-2041fef68735",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = \"\"",
                "in",
                "    Источник"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Refresh_date",
            "expression": "\"Последнее обновление \" & FORMAT(LASTDATE('metrika_stats'[Date]) + 1, \"dd.mm.yyyy\")",
            "lineageTag": "ca32954a-6fce-429d-b484-40059e373887"
          },
          {
            "name": "YTD Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date total\\Refresh_date",
            "lineageTag": "1a7b3867-4fb9-4280-9675-8d9e840be008",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date total\\Refresh_date",
            "lineageTag": "df569b13-2322-48f3-a3b4-605e22e7dd59",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date total\\Refresh_date",
            "lineageTag": "f6d22217-2013-4e52-a89e-e6119bbe2fec",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "ffce9df1-dd5d-4d5e-a0f9-17322fdefdaa",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Refresh_date]",
              "VAR __ValuePreviousPeriod = [PY Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "69adab72-1116-405b-9030-e4f472d6485b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY Refresh_date],",
              "    [PY Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "bf97bfdd-9362-46a5-a0ad-4262c8a49453",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "26bd1e29-9a9e-4d6e-b3a1-fa0bb95ec065",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Refresh_date]",
              "VAR __ValuePreviousPeriod = [PQ Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "2fb45875-e85b-4d98-9eac-6a18b92a3b8b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ Refresh_date],",
              "    [PQ Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "fd6f14e7-7acd-4c3d-b802-7a49c0c0fdd7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "891c94a5-32dc-4404-9a15-a2ba9a707266",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [Refresh_date]",
              "VAR __ValuePreviousPeriod = [PM Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "9421f7cd-2775-47ed-a681-3a9d6ba111cf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM Refresh_date],",
              "    [PM Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\Refresh_date",
            "lineageTag": "ead24df5-f3f7-46d7-8fd3-0baa04745b13",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD Refresh_date],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "f4141c68-b0f9-45f3-b219-3da53ba3c5cb",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Refresh_date]",
              "VAR __ValuePreviousPeriod = [PYTD Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "4488b47e-385c-45ca-928f-c3da82f80a81",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD Refresh_date],",
              "    [PYTD Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "bb2d1fc2-d3ce-4c57-9934-14b4b5e81592",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD Refresh_date],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "e3b33b7c-9805-4831-b8dd-2ec380357b1f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Refresh_date]",
              "VAR __ValuePreviousPeriod = [PQTD Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "e8c2d39c-c575-419f-8489-82f3432ec173",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD Refresh_date],",
              "    [PQTD Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "6ed206af-2c66-4138-bcff-dfc26233b0a7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD Refresh_date],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "35822650-345e-4799-ad10-5b71c0cbc8d3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Refresh_date]",
              "VAR __ValuePreviousPeriod = [PMTD Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "85ae3f5c-22e9-4814-97f9-b84d4fa125f3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD Refresh_date],",
              "    [PMTD Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\Refresh_date",
            "lineageTag": "0f9ffe1d-a7ab-468c-ab1b-ae920b561316",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "7add3146-f988-4dd3-9d79-16dbc48940c5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD Refresh_date]",
              "VAR __ValuePreviousPeriod = [PYC Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "099be33a-e990-4c02-ae9b-908d05519bdd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY Refresh_date],",
              "    [PYC Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "bc4db1b0-2a50-452c-b78e-d052ab2083c8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "7715a921-f4b1-475c-a26a-ed092190edcc",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD Refresh_date]",
              "VAR __ValuePreviousPeriod = [PQC Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "48ec4d1e-f4ff-4087-adce-48fa53ede41f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ Refresh_date],",
              "    [PQC Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "63ce4b55-0a69-416d-b2ff-d5ff53799f2f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "512a32de-638c-436d-9d95-c03cab40c933",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD Refresh_date]",
              "VAR __ValuePreviousPeriod = [PMC Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "18177be0-c5c8-4034-ab05-28320ebde6e6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM Refresh_date],",
              "    [PMC Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\Refresh_date",
            "lineageTag": "7c82008b-4ebc-4961-89fc-95b46dcfd03a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [Refresh_date],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Refresh_date",
            "lineageTag": "3cd124ed-b56a-43e9-98a5-f4f361f0c8e1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT Refresh_date",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT Refresh_date],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Refresh_date",
            "lineageTag": "a629fd2b-a237-4788-9466-e1401b9aacf0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG Refresh_date",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT Refresh_date]",
              "VAR __ValuePreviousPeriod = [PYMAT Refresh_date]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "displayFolder": "Time intelligence\\Moving annual growth\\Refresh_date",
            "lineageTag": "a2d86485-65af-4427-8992-0ac85e516975",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % Refresh_date",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG Refresh_date],",
              "    [PYMAT Refresh_date]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\Refresh_date",
            "lineageTag": "19d7f26d-a38c-4b80-956e-83af4953039e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "WEEKNOW_CHECK",
            "expression": "IF(CONTAINS('Date','Date'[WeekNow], TRUE()) = TRUE(), 1,0)",
            "formatString": "0",
            "lineageTag": "51ed2219-5cd0-4d91-8afb-8498fb7a4eb7"
          },
          {
            "name": "MONTHNOW_CHECK",
            "expression": "IF(CONTAINS('Date','Date'[MonthNow], TRUE()) = TRUE(), 1,0)",
            "formatString": "0",
            "lineageTag": "db0a16eb-7540-40bb-a491-51887e5879a7"
          },
          {
            "name": "MONTHPREV_CHECK",
            "expression": "IF(CONTAINS('Date','Date'[MonthPrev], TRUE()) = TRUE(), 1,0)",
            "formatString": "0",
            "lineageTag": "910dba84-9e37-4fcd-890b-33f4c1e9f296"
          },
          {
            "name": "PREV7DAYS_CHECK",
            "expression": "IF(CONTAINS('Date','Date'[Prev7days], TRUE()) = TRUE(), 1,0)",
            "formatString": "0",
            "lineageTag": "59312e63-a39a-45ec-b32f-548f17fa761f"
          },
          {
            "name": "WEEKPREV_CHECK",
            "expression": "IF(CONTAINS('Date','Date'[WeekPrev], TRUE()) = TRUE(), 1,0)",
            "formatString": "0",
            "lineageTag": "d4333ae5-5a9a-4121-83be-4f9b78cf8e4b"
          },
          {
            "name": "YESTERDAY_CHECK",
            "expression": "IF(CONTAINS('Date','Date'[Yesterday], TRUE()) = TRUE(), 1,0)",
            "formatString": "0",
            "lineageTag": "306533e2-1ad4-4409-b2cf-597742e70114"
          },
          {
            "name": "Визиты",
            "expression": "SUM(metrika_stats[sumVisits])",
            "formatString": "0",
            "lineageTag": "44e21e6e-6504-4210-8108-58776d6b0b4f"
          },
          {
            "name": "Клики",
            "expression": "SUM(metrika_stats[Clicks])",
            "formatString": "0",
            "lineageTag": "e87d0562-b1e8-41b6-ad06-19164e81dc35"
          },
          {
            "name": "Показы",
            "expression": "SUM(metrika_stats[Impressions])",
            "formatString": "0",
            "lineageTag": "1be46687-4d0d-4bed-91bf-34bb486cfd2b"
          },
          {
            "name": "Расход",
            "expression": "SUM(metrika_stats[Cost])",
            "formatString": "0",
            "lineageTag": "7f605d2a-9417-42ba-9c07-705f2d6d6758"
          },
          {
            "name": "Целевые действия",
            "expression": [
              "",
              "VAR __SelectedGoals = ALLSELECTED ( _goals[Goal] )",
              "/// перечислите меры в соответствии с шаблоном",
              "/// VAR __goalN = IF (\"название конверсии\" IN __SelectedGoals, SUM( 'dataset'[Conversions_XXXXXXXXX_LSC] ))",
              "",
              "VAR __goal1 = IF (\"клик по номеру\" IN __SelectedGoals,SUM ( 'metrika_stats'[Conversions_290531916_LSC] ) + SUM('metrika_stats'[Conversions_291210068_LSC]))",
              "VAR __goal2 = IF (\"отправка формы\" IN __SelectedGoals, SUM( 'metrika_stats'[Conversions_290532335_LSC] ) + SUM('metrika_stats'[Conversions_291212676_LSC]))",
              "VAR __goal3 = IF (\"Заказ посещения\" IN __SelectedGoals, SUM( 'metrika_stats'[Conversions_290534052_LSC] ) + SUM('metrika_stats'[Conversions_291214181_LSC]))",
              "",
              "RETURN",
              "// Добавьте вывод конверсии плюсанув к выражению:",
              "__goal1 + __goal2 + __goal3"
            ],
            "formatString": "0",
            "lineageTag": "55102e49-1837-4a0e-a221-375fe35309f8"
          },
          {
            "name": "Ассоц. конв.",
            "expression": [
              "",
              "VAR __SelectedGoals = ALLSELECTED ( _goals[Goal] )",
              "/// перечислите меры в соответствии с шаблоном",
              "/// VAR __goalN = IF (\"название конверсии\" IN __SelectedGoals, SUM( 'dataset'[Conversions_XXXXXXXXX_LSC] ))",
              "",
              "/// Для источников",
              "VAR s__goal1 = CALCULATE(IF (\"клик по номеру\" IN __SelectedGoals,SUM ( 'metrika_stats'[Conversion_290531916_ASS] ) + SUM('metrika_stats'[Conversion_291210068_ASS])),metrika_stats[CampaignName] = BLANK())",
              "VAR s__goal2 = CALCULATE(IF (\"отправка формы\" IN __SelectedGoals, SUM( 'metrika_stats'[Conversion_290532335_ASS] ) + SUM('metrika_stats'[Conversion_291212676_ASS])),metrika_stats[CampaignName] = BLANK())",
              "VAR s__goal3 = CALCULATE(IF (\"Заказ посещения\" IN __SelectedGoals, SUM( 'metrika_stats'[Conversion_290534052_ASS] ) + SUM('metrika_stats'[Conversion_291214181_ASS])),metrika_stats[CampaignName] = BLANK())",
              "",
              "/// Для кампаний",
              "VAR c__goal1 = CALCULATE(IF (\"клик по номеру\" IN __SelectedGoals,SUM ( 'metrika_stats'[Conversion_290531916_ASS] ) + SUM('metrika_stats'[Conversion_291210068_ASS])),metrika_stats[CampaignName] <> BLANK())",
              "VAR c__goal2 = CALCULATE(IF (\"отправка формы\" IN __SelectedGoals, SUM( 'metrika_stats'[Conversion_290532335_ASS] ) + SUM('metrika_stats'[Conversion_291212676_ASS])),metrika_stats[CampaignName] <> BLANK())",
              "VAR c__goal3 = CALCULATE(IF (\"Заказ посещения\" IN __SelectedGoals, SUM( 'metrika_stats'[Conversion_290534052_ASS] ) + SUM('metrika_stats'[Conversion_291214181_ASS])),metrika_stats[CampaignName] <> BLANK())",
              "",
              "// Добавьте вывод конверсии плюсанув к выражению:",
              "var res_camp = c__goal1+c__goal2+c__goal3",
              "var res_source = s__goal1+s__goal2+s__goal3",
              "",
              "RETURN",
              "IF(ISINSCOPE(metrika_stats[NewTypes]) = TRUE(), res_source, ",
              "IF(ISINSCOPE(metrika_stats[NewEngines]) = TRUE(), res_source, ",
              "IF(ISINSCOPE(metrika_stats[CampaignName]) = TRUE(), res_camp,",
              "IF(SELECTEDVALUE('Детализация'[Заказ Детализация]) = 1, res_camp,",
              "IF(SELECTEDVALUE('Детализация'[Заказ Детализация]) = 2, res_camp,",
              "IF(ISINSCOPE(Campaigns_list[CampaignName]) = TRUE(), res_camp,",
              "BLANK()))))))"
            ],
            "formatString": "0",
            "lineageTag": "7112ac9f-65d6-4a02-b0b2-990a6891fd2e"
          },
          {
            "name": "Кликабельность",
            "expression": "DIVIDE([Клики],[Показы])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2e6698dc-d588-4119-8613-fbfd9b8005e7"
          },
          {
            "name": "Стоимость клика",
            "expression": "DIVIDE([Расход],[Клики])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "f90cfdce-0ffc-4c53-b9e2-02e66b8a978a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Стоимость действ.",
            "expression": [
              "",
              "var A = CALCULATE(DIVIDE([Расход],[Целевые действия]),OR(TrafficSources[NewTypes] = \"Контекст\",TrafficSources[NewTypes] = \"Таргет\"))",
              "var B = DIVIDE([Расход],[Целевые действия])",
              "return",
              "IF(SELECTEDVALUE(CPA_mode[Расчет CPA]) = \"Конверсии только с платного трафика\", A, B)"
            ],
            "formatString": "0",
            "lineageTag": "8db5050a-90b6-4be4-906a-a260e8e9fd30"
          },
          {
            "name": "% Отказов",
            "expression": "AVERAGE(metrika_stats[bounceRate])",
            "lineageTag": "abb479d8-84ef-43f3-9c4c-857aeb7ace90",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% Конверсия",
            "expression": "DIVIDE([Целевые действия], [Клики]) ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "af675614-e6f0-4e8e-be5b-a70d2810a44a"
          },
          {
            "name": "Глубина просмотра",
            "expression": "AVERAGE(metrika_stats[avgPageViews])",
            "lineageTag": "8fab8f38-7900-4b13-9c87-502614ffbf49",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "BLANK_GRAPH",
            "expression": "BLANK()",
            "formatString": "0",
            "lineageTag": "efffe96e-0669-4fc5-abae-878c9de68ee3"
          },
          {
            "name": "Клики YD",
            "expression": "SUM(ydirect_extended[Clicks])",
            "formatString": "0",
            "lineageTag": "a73db0f9-3ef0-441f-8698-0eb98646c22f"
          },
          {
            "name": "Показы YD",
            "expression": "SUM(ydirect_extended[Impressions])",
            "formatString": "0",
            "lineageTag": "e847f353-bf99-4de4-8582-5e42d336d9c4"
          },
          {
            "name": "Расход YD",
            "expression": "SUM(ydirect_extended[Cost])",
            "formatString": "0",
            "lineageTag": "184f3f49-c5d9-439e-8392-0466976c18b8"
          },
          {
            "name": "Целевые действия YD",
            "expression": [
              "",
              "VAR __SelectedGoals = ALLSELECTED ( _goals[Goal] )",
              "/// перечислите меры в соответствии с шаблоном",
              "/// VAR __goalN = IF (\"название конверсии\" IN __SelectedGoals, SUM( 'dataset'[Conversions_XXXXXXXXX_LSC] ))",
              "",
              "VAR __goal1 = IF (\"клик по номеру\" IN __SelectedGoals,SUM ( 'ydirect_extended'[Conversions_290531916_LSC] ) + SUM('ydirect_extended'[Conversions_291210068_LSC]))",
              "VAR __goal2 = IF (\"отправка формы\" IN __SelectedGoals, SUM( 'ydirect_extended'[Conversions_290532335_LSC] ) + SUM('ydirect_extended'[Conversions_291212676_LSC]))",
              "VAR __goal3 = IF (\"Заказ посещения\" IN __SelectedGoals, SUM( 'ydirect_extended'[Conversions_290534052_LSC] ) + SUM('ydirect_extended'[Conversions_291214181_LSC]))",
              "",
              "RETURN",
              "// Добавьте вывод конверсии плюсанув к выражению:",
              "__goal1 + __goal2 + __goal3"
            ],
            "formatString": "0",
            "lineageTag": "7a6ccb0b-3b0c-46ff-8abe-5e52226009cc"
          },
          {
            "name": "Кликабельность YD",
            "expression": "DIVIDE([Клики YD],[Показы YD])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "824335e8-f629-40c6-8c7c-ab1621670f39"
          },
          {
            "name": "Стоимость клика YD",
            "expression": "DIVIDE([Расход YD],[Клики YD])",
            "formatString": "#,0.00\\ \"₽\";-#,0.00\\ \"₽\";#,0.00\\ \"₽\"",
            "lineageTag": "e0f40d3e-2168-4176-b4b3-3fb8b0b86b27",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"ru-RU\"}"
              }
            ]
          },
          {
            "name": "Стоимость действ. YD",
            "expression": [
              "",
              "var A = CALCULATE(DIVIDE([Расход YD],[Целевые действия YD]),OR(TrafficSources[NewTypes] = \"Контекст\",TrafficSources[NewTypes] = \"Таргет\"))",
              "var B = DIVIDE([Расход YD],[Целевые действия YD])",
              "return",
              "IF(SELECTEDVALUE(CPA_mode[Расчет CPA]) = \"Конверсии только с платного трафика\", A, B)"
            ],
            "formatString": "0",
            "lineageTag": "01d1bba3-c1a1-4536-bb77-a57acae5bc33"
          },
          {
            "name": "% Отказов YD",
            "expression": "AVERAGE(ydirect_extended[BounceRate])",
            "lineageTag": "7984897d-6d18-481d-8bac-fe74e4773b28",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% Конверсия YD",
            "expression": "DIVIDE([Целевые действия YD], [Клики YD]) ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "df63a6d7-304c-4359-b987-e82bb35d0abd"
          },
          {
            "name": "Глубина просмотра YD",
            "expression": "AVERAGE(ydirect_extended[AvgPageviews])",
            "lineageTag": "81957af4-0006-4417-a5d0-169c6e764d0d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "STATE",
            "expression": "IF(ISINSCOPE(Campaigns_list[CampaignName]), MAX(States[For_Matrix]), BLANK())",
            "formatString": "0",
            "lineageTag": "cfe02ce8-4a51-4059-8885-51978a7bf58d"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "HolidaysDefinition",
        "isHidden": true,
        "lineageTag": "c9329cde-356e-4810-8895-b77c7fe49002",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "ISO Country",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[ISO Country]",
            "lineageTag": "acc899e6-1469-4ef9-ab23-65b18cc4cc5e",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MonthNumber]",
            "lineageTag": "d6b281c3-2e5e-40dc-bf9f-11835d9873c0",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[DayNumber]",
            "lineageTag": "7a6aa75f-99c3-4657-8d44-64efb3238e91",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WeekDayNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[WeekDayNumber]",
            "lineageTag": "489784b4-4abd-4572-85bf-1e8eee57c076",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OffsetWeek",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OffsetWeek]",
            "lineageTag": "f9d66bc1-d617-4e17-9dfa-5153b13bab3c",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OffsetDays",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OffsetDays]",
            "lineageTag": "3f9d919c-1c55-44fa-bd8e-a13e9868e4c8",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "HolidayName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[HolidayName]",
            "lineageTag": "5e577ac1-fe70-4173-ab97-b329743a7a92",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SubstituteHoliday",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[SubstituteHoliday]",
            "lineageTag": "515807ab-aa85-4d97-89c0-8e43416c46a8",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ConflictPriority",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[ConflictPriority]",
            "lineageTag": "7a94ddd6-b9bb-4a82-8c31-aafb7fca1943",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[FirstYear]",
            "lineageTag": "126ef9e5-1ab6-49f7-80d4-c9d369dea2e2",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LastYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[LastYear]",
            "lineageTag": "b5e546c8-46ef-4c1a-a41d-f0bc5bc3e384",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "HolidaysDefinition",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE (",
                "    \"ISO Country\", STRING,        -- ISO country code(to enable filter based on country)",
                "    \"MonthNumber\", INTEGER,       -- Number of month - use 99,98,97,96 for relative dates using an offset over special references:",
                "                                  --     99 = Easter (DayNumber 1 = Easter Monday, DayNumber -2 = Easter Friday)",
                "                                  --     98 = Swedish Midsummer Day ",
                "                                  --     97 = September Equinox",
                "                                  --     96 = March Equinox",
                "    \"DayNumber\", INTEGER,         -- Absolute day(ignore WeekDayNumber, otherwise use 0)",
                "    \"WeekDayNumber\", INTEGER,     -- 0 = Sunday, 1 = Monday, ... , 7 = Saturday",
                "    \"OffsetWeek\", INTEGER,        -- 1 = first, 2 = second, ... -1 = last, -2 = second - last, ...",
                "    \"OffsetDays\", INTEGER,        -- days to add after offsetWeek and WeekDayNumber have been applied",
                "    \"HolidayName\", STRING,        -- Holiday name",
                "    \"SubstituteHoliday\", INTEGER, -- 0 = no substituteHoliday, 1 = substitute holiday with next working day, 2 = substitute holiday with next working day",
                "                                  -- (use 2 before 1 only, e.g.Christmas = 2, Boxing Day = 1)",
                "                                  -- -1 = if it falls on a Saturday then it is observed on Friday, if it falls on a Sunday then it is observed on Monday",
                "    \"ConflictPriority\", INTEGER,  -- Priority in case of two or more holidays in the same date - lower number-- > higher priority",
                "                                  -- For example: marking Easter relative days with 150 and other holidays with 100 means that other holidays take",
                "                                  --              precedence over Easter - related days; use 50 for Easter related holidays to invert such a priority",
                "    \"FirstYear\", INTEGER,         -- First year for the holiday, 0 if it is not defined",
                "    \"LastYear\", INTEGER,          -- Last year for the holiday, 0 if it is not defined",
                "    {",
                "        { \"US\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"US\", 1, 0, 1, 3, 0, \"Martin Luther King, Jr.\", 0, 100, 0, 0 },",
                "        { \"US\", 2, 0, 1, 3, 0, \"Presidents' Day\", 0, 100, 0, 0 },",
                "        { \"US\", 5, 0, 1, -1, 0, \"Memorial Day\", 0, 100, 0, 0 },",
                "        { \"US\", 6, 19, 0, 0, 0, \"Juneteenth\", -1, 100, 2021, 0 },",
                "        { \"US\", 7, 4, 0, 0, 0, \"Independence Day\", 0, 100, 0, 0 },",
                "        { \"US\", 9, 0, 1, 1, 0, \"Labor Day\", 0, 100, 0, 0 },",
                "        { \"US\", 10, 0, 1, 2, 0, \"Columbus Day\", 0, 100, 0, 0 },",
                "        { \"US\", 11, 11, 0, 0, 0, \"Veterans Day\", 0, 100, 0, 0 },",
                "        { \"US\", 11, 0, 4, 4, 0, \"Thanksgiving Day\", 0, 100, 0, 0 },",
                "        { \"US\", 11, 0, 4, 4, 1, \"Black Friday\", 0, 100, 0, 0 },",
                "        { \"US\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"AT\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"AT\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"AT\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"AT\", 99, 60, 0, 0, 0, \"Corpus Christi\", 0, 50, 0, 0 },",
                "        { \"AT\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 10, 26, 0, 0, 0, \"National Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 12, 8, 0, 0, 0, \"Immaculate Conception Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"AU\", 1, 1, 0, 0, 0, \"New Year's Day\", 1, 100, 0, 0 },",
                "        { \"AU\", 1, 26, 0, 0, 0, \"Australia Day\", 1, 100, 0, 0 },",
                "        { \"AU\", 99, -1, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"AU\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"AU\", 4, 25, 0, 0, 0, \"Anzac Day\", 1, 100, 0, 0 },",
                "        { \"AU\", 12, 25, 0, 0, 0, \"Christmas Day\", 2, 100, 0, 0 },",
                "        { \"AU\", 12, 26, 0, 0, 0, \"Boxing Day\", 1, 100, 0, 0 },",
                "        { \"BE\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"BE\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"BE\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"BE\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 7, 21, 0, 0, 0, \"Belgian National Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 11, 11, 0, 0, 0, \"Armistice Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"CA\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"CA\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"CA\", 7, 1, 0, 0, 0, \"Canada Day\", 0, 50, 0, 0 },",
                "        { \"CA\", 9, 0, 1, 1, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"CA\", 10, 0, 1, 2, 0, \"Thanksgiving\", 0, 100, 0, 0 },",
                "        { \"CA\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"DE\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"DE\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"DE\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"DE\", 10, 3, 0, 0, 0, \"German Unity Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"ES\", 99, -3, 0, 0, 0, \"Maundy Thursday\", 0, 50, 0, 0 },",
                "        { \"ES\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"ES\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"ES\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 10, 12, 0, 0, 0, \"Fiesta Navional de España\", 0, 100, 0, 0 },",
                "        { \"ES\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 12, 6, 0, 0, 0, \"Constitution Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 12, 8, 0, 0, 0, \"Immaculate Conception\", 0, 100, 0, 0 },",
                "        { \"ES\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"FR\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 5, 8, 0, 0, 0, \"Victor in Europe Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"FR\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"FR\", 7, 14, 0, 0, 0, \"Bastille Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 11, 11, 0, 0, 0, \"Armistice Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"GB\", 1, 1, 0, 0, 0, \"New Year's Day\", 1, 100, 0, 0 },",
                "        { \"GB\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"GB\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"GB\", 5, 0, 1, 1, 0, \"May Day Bank Holiday\", 0, 100, 0, 0 },",
                "        { \"GB\", 5, 0, 1, -1, 0, \"Spring Bank Holiday\", 0, 100, 0, 0 },",
                "        { \"GB\", 8, 0, 1, -1, 0, \"Late Summer Bank Holiday\", 0, 100, 0, 0 },",
                "        { \"GB\", 12, 25, 0, 0, 0, \"Christmas Day\", 2, 100, 0, 0 },",
                "        { \"GB\", 12, 26, 0, 0, 0, \"Boxing Day\", 1, 100, 0, 0 },",
                "        { \"IT\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"IT\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 100, 0, 0 },",
                "        { \"IT\", 4, 25, 0, 0, 0, \"Liberation Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 6, 2, 0, 0, 0, \"Republic Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 12, 8, 0, 0, 0, \"Immaculate Conception\", 0, 100, 0, 0 },",
                "        { \"IT\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"NL\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"NL\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"NL\", 4, 27, 0, 0, 0, \"King's Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 5, 5, 0, 0, 0, \"Liberation Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 99, -3, 0, 0, 0, \"Maundy Thursday\", 0, 100, 0, 0 },",
                "        { \"NO\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"NO\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"NO\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"NO\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"NO\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 5, 17, 0, 0, 0, \"Constitution Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 12, 24, 0, 0, 0, \"Christmas Eve\", 0, 50, 0, 0 },",
                "        { \"NO\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 12, 26, 0, 0, 0, \"Boxing Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 12, 31, 0, 0, 0, \"New Year's Eve\", 0, 100, 0, 0 },",
                "        { \"PT\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"PT\", 99, 60, 0, 0, 0, \"Corpus Christi\", 0, 50, 0, 0 },",
                "        { \"PT\", 4, 25, 0, 0, 0, \"Freedom Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 6, 10, 0, 0, 0, \"Portugal Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 10, 5, 0, 0, 0, \"Republic Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 12, 1, 0, 0, 0, \"Restoration of Independence\", 0, 100, 0, 0 },",
                "        { \"PT\", 12, 8, 0, 0, 0, \"Immaculate Conception\", 0, 50, 0, 0 },",
                "        { \"PT\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"SE\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"SE\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"SE\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"SE\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 6, 6, 0, 0, 0, \"National Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 12, 24, 0, 0, 0, \"Christmas Eve\", 0, 50, 0, 0 },",
                "        { \"SE\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 12, 26, 0, 0, 0, \"Boxing Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 12, 31, 0, 0, 0, \"New Year's Eve\", 0, 100, 0, 0 },",
                "        { \"SE\", 98, -1, 0, 0, 0, \"Midsubber Eve\", 0, 50, 0, 0 },",
                "        { \"DK\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"DK\", 99, -3, 0, 0, 0, \"Maundy Thursday\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 26, 0, 0, 0, \"Prayer Day\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"DK\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"DK\", 6, 5, 0, 0, 0, \"Constitution Day\", 0, 50, 0, 0 },",
                "        { \"DK\", 12, 24, 0, 0, 0, \"Christmas Eve\", 0, 50, 0, 0 },",
                "        { \"DK\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"DK\", 12, 26, 0, 0, 0, \"Second Day of Christmas\", 0, 100, 0, 0 },",
                "        { \"DK\", 12, 31, 0, 0, 0, \"New Year's Eve\", 0, 100, 0, 0 },",
                "        { \"BR\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"BR\", 4, 21, 0, 0, 0, \"Tiradentes' Day\", 0, 50, 0, 0 },",
                "        { \"BR\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"BR\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"BR\", 9, 7, 0, 0, 0, \"Independence Day\", 0, 100, 0, 0 },",
                "        { \"BR\", 10, 12, 0, 0, 0, \"Lady of Aparecida\", 0, 100, 0, 0 },",
                "        { \"BR\", 11, 2, 0, 0, 0, \"All Soul's Day'\", 0, 100, 0, 0 },",
                "        { \"BR\", 11, 15, 0, 0, 0, \"Republic Day'\", 0, 100, 0, 0 },",
                "        { \"BR\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"JP\", 1, 1, 0, 0, 0, \"New Year's Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 1, 15, 0, 0, 0, \"Coming of Age Day\", 2, 100, 0, 1999 },",
                "        { \"JP\", 1, 0, 1, 2, 0, \"Coming of Age Day\", 0, 100, 2000, 0 },",
                "        { \"JP\", 2, 11, 0, 0, 0, \"National Foundation Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 2, 23, 0, 0, 0, \"The Emperor's Birthday\", 2, 100, 2020, 0 },",
                "        { \"JP\", 12, 23, 0, 0, 0, \"The Emperor's Birthday\", 2, 100, 1989, 2018 },",
                "        { \"JP\", 96, 0, 0, 0, 0, \"Vernal Equinox Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 4, 29, 0, 0, 0, \"The Emperor's Birthday\", 2, 100, 0, 1988 },",
                "        { \"JP\", 4, 29, 0, 0, 0, \"Greenery Day\", 2, 100, 1989, 2006 },",
                "        { \"JP\", 4, 29, 0, 0, 0, \"Shōwa Day\", 2, 100, 2007, 0 },",
                "        { \"JP\", 5, 3, 0, 0, 0, \"Constitution Memorial Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 5, 4, 0, 0, 0, \"Greenery Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 5, 5, 0, 0, 0, \"Children's Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 7, 20, 0, 0, 0, \"Marine Day\", 2, 100, 0, 2002 },",
                "        { \"JP\", 7, 0, 1, 3, 0, \"Marine Day\", 0, 100, 2003, 0 },",
                "        { \"JP\", 8, 11, 0, 0, 0, \"Mountain Day\", 2, 100, 2016, 0 },",
                "        { \"JP\", 9, 15, 0, 0, 0, \"Respect for the Aged Day\", 2, 100, 0, 2002 },",
                "        { \"JP\", 9, 0, 1, 3, 0, \"Respect for the Aged Day\", 0, 100, 2003, 0 },",
                "        { \"JP\", 97, 0, 0, 0, 0, \"Autumnal Equinox Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 10, 10, 0, 0, 0, \"Sports Day\", 2, 100, 0, 1999 },",
                "        { \"JP\", 10, 0, 1, 2, 0, \"Sports Day\", 0, 100, 2000, 0 },",
                "        { \"JP\", 11, 3, 0, 0, 0, \"Culture Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 11, 23, 0, 0, 0, \"Labour Thanksgiving Day\", 2, 100, 0, 0 },",
                "        { \"RU\", 1, 1, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 2, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 3, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 4, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 5, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 6, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 7, 0, 0, 0, \"Рождество Христово\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 8, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 2, 23, 0, 0, 0, \"День защитника Отечества\", 0, 100, 0, 0 },",
                "        { \"RU\", 3, 8, 0, 0, 0, \"Международный женский день\", 0, 100, 0, 0 },",
                "        { \"RU\", 5, 1, 0, 0, 0, \"Праздник Весны и Труда\", 0, 100, 0, 0 },",
                "        { \"RU\", 5, 9, 0, 0, 0, \"День Победы\", 0, 100, 0, 0 },",
                "        { \"RU\", 6, 12, 0, 0, 0, \"День России\", 0, 100, 0, 0 },",
                "        { \"RU\", 11, 4, 0, 0, 0, \"День народного единства\", 0, 100, 0, 0 },",
                "        { \"CN\", 1, 1, 0, 0, 0, \"元旦\", 0, 100, 0, 0 },",
                "        { \"CN\", 5, 1, 0, 0, 0, \"劳动节\", 0, 100, 0, 0 },",
                "        { \"CN\", 10, 1, 0, 0, 0, \"国庆节\", 0, 100, 0, 0 },",
                "        { \"CN\", 10, 2, 0, 0, 0, \"国庆节\", 0, 100, 0, 0 },",
                "        { \"CN\", 10, 3, 0, 0, 0, \"国庆节\", 0, 100, 0, 0 }",
                "    }",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Holidays"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "HolidaysDefinition"
          }
        ]
      },
      {
        "name": "Holidays",
        "isHidden": true,
        "lineageTag": "9f66bef8-a49b-422d-b4a3-466e06b7962b",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Holiday Date]",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "deddb8d6-b6e3-4689-89e2-7cb29f38412e",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Holiday Name]",
            "lineageTag": "7046f7df-d773-4120-a9b1-27d84331ac43",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Holidays",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "-- ",
                "--    Configuration",
                "-- ",
                "VAR __FirstYear = YEAR ( MINX ( { MIN ( 'metrika_stats'[date] ) }, ''[Value] ) )",
                "VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'metrika_stats'[date] ) }, ''[Value] ) )",
                "VAR __IsoCountryHolidays = \"RU\"",
                "VAR __WorkingDays = { 2, 3, 4, 5, 6 }",
                "VAR __InLieuOfPrefix = \"(in lieu of \"",
                "VAR __InLieuOfSuffix = \")\"",
                "----------------------------------------",
                "VAR __FilterIsoConfig =",
                "    FILTER(",
                "        'HolidaysDefinition',",
                "        IF(",
                "            CONTAINS('HolidaysDefinition', 'HolidaysDefinition'[ISO Country], __IsoCountryHolidays)",
                "                || __IsoCountryHolidays = \"\",",
                "            'HolidaysDefinition'[ISO Country] = __IsoCountryHolidays,",
                "            ERROR(\"IsoCountryHolidays set to an unsupported country code\")",
                "        )",
                "    )",
                "VAR __ConfigGeneration =",
                "    GENERATE(",
                "        GENERATESERIES(__FirstYear - 1, __LastYear + 1, 1),",
                "        __FilterIsoConfig",
                "    )",
                "VAR __GeneratedRawWithDuplicatesUnfiltered =",
                "    GENERATE(",
                "        __ConfigGeneration,",
                "        VAR __HolidayYear = ''[Value]",
                "        VAR __EasterDate =",
                "            -- Code adapted from original VB version from https://www.assa.org.au/edm ",
                "            VAR _EasterYear = __HolidayYear",
                "            VAR _FirstDig =",
                "                INT ( _EasterYear / 100 )",
                "            VAR _Remain19 =",
                "                MOD ( _EasterYear, 19 ) ",
                "            -- Calculate PFM date",
                "            VAR _temp1 =",
                "                MOD (",
                "                    INT ( ( _FirstDig - 15 ) / 2 )",
                "                        + 202",
                "                        - 11 * _Remain19",
                "                        + SWITCH (",
                "                            TRUE,",
                "                            _FirstDig IN { 21, 24, 25, 27, 28, 29, 30, 31, 32, 34, 35, 38 },",
                "                            0",
                "                        ),",
                "                    30",
                "                )",
                "            VAR _tA =",
                "                _temp1 + 21",
                "                    + IF ( _temp1 = 29 || ( _temp1 = 28 && _Remain19 > 10 ), -1 ) // ",
                "            -- Find the next Sunday",
                "            VAR _tB =",
                "                MOD ( _tA - 19, 7 )",
                "            VAR _tCpre =",
                "                MOD ( 40 - _FirstDig, 4 )",
                "            VAR _tC =",
                "                _tCpre",
                "                    + IF ( _tCpre = 3, 1 )",
                "                    + IF ( _tCpre > 1, 1 )",
                "            VAR _temp2 =",
                "                MOD ( _EasterYear, 100 )",
                "            VAR _tD =",
                "                MOD ( _temp2 + INT ( _temp2 / 4 ), 7 )",
                "            VAR _tE =",
                "                MOD ( 20 - _tB - _tC - _tD, 7 )",
                "                    + 1",
                "            VAR _d = _tA + _tE ",
                "            -- Return the date",
                "            VAR _EasterDay =",
                "                IF ( _d > 31, _d - 31, _d )",
                "            VAR _EasterMonth =",
                "                IF ( _d > 31, 4, 3 )",
                "            RETURN",
                "                DATE ( _EasterYear, _EasterMonth, _EasterDay ) ",
                "            -- End of code adapted from original VB version from https://www.assa.org.au/edm",
                "        VAR __SwedishMidSummer = ",
                "            -- Compute the Midsummer day in Swedish - it is the Saturday between 20 and 26 June",
                "            -- This calculation is valid only for years after 1953 ",
                "            -- https://sv.wikipedia.org/wiki/Midsommar_i_Sverige",
                "            VAR _June20 = ",
                "                DATE ( __HolidayYear, 6, 20 )",
                "            RETURN",
                "                DATE ( __HolidayYear, 6, 20 + (7 - WEEKDAY ( _June20, 1 ) ) )",
                "            -- End of SwedishMidSummer calculation",
                "        VAR __MarchEquinoxDay =",
                "            INT ( 20.8431 + 0.242194 * ( __HolidayYear - 1980 ) )",
                "                - INT ( ( ( __HolidayYear - 1980 ) / 4 ) )",
                "        VAR __MarchEquinox = DATE ( __HolidayYear, 3, __MarchEquinoxDay )",
                "        VAR __SeptemberEquinoxDay =",
                "            INT ( 23.2488 + 0.242194 * ( __HolidayYear - 1980 ) )",
                "                - INT ( ( __HolidayYear - 1980 ) / 4 )",
                "        VAR __SeptemberEquinox = DATE ( __HolidayYear, 9, __SeptemberEquinoxDay )",
                "        VAR __HolidayDate = ",
                "//  Workaround for a SWITCH regression that fails on service from 2022-12-10 - revert to SWITCH and remove IF once the bug is fixed",
                "//            SWITCH (",
                "//                TRUE,",
                "                IF ( 'HolidaysDefinition'[DayNumber] <> 0",
                "                    && 'HolidaysDefinition'[WeekDayNumber] <> 0, ERROR ( \"Wrong configuration in HolidaysDefinition\" ),",
                "                IF ( 'HolidaysDefinition'[DayNumber] <> 0",
                "                    && 'HolidaysDefinition'[MonthNumber] <= 12, DATE ( __HolidayYear, 'HolidaysDefinition'[MonthNumber], 'HolidaysDefinition'[DayNumber] ),",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 99, -- Easter offset",
                "                    __EasterDate + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 98, -- Swedish Midsummer Day",
                "                    __SwedishMidSummer + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 97, -- September Equinox",
                "                    __SeptemberEquinox + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 96, -- March Equinox",
                "                    __MarchEquinox + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[WeekDayNumber] <> 0,",
                "                    VAR _ReferenceDate =",
                "                        DATE ( __HolidayYear, 1",
                "                            + MOD ( 'HolidaysDefinition'[MonthNumber] - 1 + IF ( 'HolidaysDefinition'[OffsetWeek] < 0, 1 ), 12 ), 1 )",
                "                            - IF ( 'HolidaysDefinition'[OffsetWeek] < 0, 1 )",
                "                    VAR _ReferenceWeekDayNumber =",
                "                        WEEKDAY ( _ReferenceDate, 1 ) - 1",
                "                    VAR _Offset =",
                "                        'HolidaysDefinition'[WeekDayNumber] - _ReferenceWeekDayNumber",
                "                            + 7 * 'HolidaysDefinition'[OffsetWeek]",
                "                            + IF (",
                "                                'HolidaysDefinition'[OffsetWeek] > 0,",
                "                                IF ( 'HolidaysDefinition'[WeekDayNumber] >= _ReferenceWeekDayNumber, -7 ),",
                "                                IF ( _ReferenceWeekDayNumber >= 'HolidaysDefinition'[WeekDayNumber], 7)",
                "                            )",
                "                RETURN",
                "                    _ReferenceDate + _Offset + 'HolidaysDefinition'[OffsetDays],",
                "                ERROR ( \"Wrong configuration in HolidaysDefinition\" )",
                "            ) ) ) ) ) ) )",
                "//            )",
                "        VAR __HolidayDay = WEEKDAY ( __HolidayDate, 1 ) - 1",
                "        VAR __SubstituteHolidayOffset = ",
                "//            SWITCH (",
                "//                TRUE,",
                "                IF ( 'HolidaysDefinition'[SubstituteHoliday] = -1,",
                "                    SWITCH ( ",
                "                        __HolidayDay, ",
                "                        0, 1,       -- If it falls on a Sunday then it is observed on Monday",
                "                        6, -1,      -- If it falls on a Saturday then it is observed on Friday",
                "                        0",
                "                    ),",
                "                IF ( 'HolidaysDefinition'[SubstituteHoliday] > 0",
                "                    && NOT CONTAINS ( __WorkingDays, ''[Value], __HolidayDay ),",
                "                    VAR _NextWorkingDay =",
                "                        MINX (",
                "                            FILTER ( __WorkingDays, ''[Value] > __HolidayDay ),",
                "                            ''[Value]",
                "                        )",
                "                    VAR _SubstituteDay =",
                "                        IF (",
                "                            ISBLANK ( _NextWorkingDay ),",
                "                            MINX ( __WorkingDays, ''[Value] ) + 7,",
                "                            _NextWorkingDay",
                "                        )",
                "                    RETURN",
                "                        _SubstituteDay - __HolidayDay",
                "                            + ( 'HolidaysDefinition'[SubstituteHoliday] - 1 )",
                "            ) )",
                "//            )",
                "        RETURN ROW ( ",
                "            \"@HolidayDate\", DATE ( YEAR ( __HolidayDate ), MONTH ( __HolidayDate ), DAY ( __HolidayDate ) ),",
                "            \"@SubstituteHolidayOffset\", __SubstituteHolidayOffset",
                "        )",
                "    )",
                "VAR __GeneratedRawWithDuplicates =",
                "\tFILTER (",
                "        __GeneratedRawWithDuplicatesUnfiltered,",
                "        ( 'HolidaysDefinition'[FirstYear] = 0 || 'HolidaysDefinition'[FirstYear] <= ''[Value] )",
                "            && ( 'HolidaysDefinition'[LastYear] = 0 || 'HolidaysDefinition'[LastYear] >= ''[Value] )",
                "    )",
                "VAR __RawDatesUnique = ",
                "    DISTINCT ( ",
                "        SELECTCOLUMNS ( ",
                "            __GeneratedRawWithDuplicates,",
                "            \"@HolidayDateUnique\", [@HolidayDate]",
                "        )",
                "    )",
                "VAR __GeneratedRaw = ",
                "    GENERATE (",
                "        __RawDatesUnique,",
                "        VAR _FilterDate = [@HolidayDateUnique]",
                "        RETURN ",
                "            TOPN (",
                "                1,",
                "                FILTER ( ",
                "                    __GeneratedRawWithDuplicates,",
                "                    [@HolidayDate] = _FilterDate",
                "                ),",
                "                'HolidaysDefinition'[ConflictPriority],",
                "                ASC,",
                "                'HolidaysDefinition'[HolidayName], ",
                "                ASC",
                "            )",
                "    )  ",
                "VAR __GeneratedSubstitutesOffset =",
                "    SELECTCOLUMNS(",
                "        FILTER ( __GeneratedRawWithDuplicates, 'HolidaysDefinition'[SubstituteHoliday] <> 0 ),",
                "        \"Value\", ''[Value],",
                "        \"ISO Country\", 'HolidaysDefinition'[ISO Country],",
                "        \"MonthNumber\", 'HolidaysDefinition'[MonthNumber],",
                "        \"DayNumber\", 'HolidaysDefinition'[DayNumber],",
                "        \"WeekDayNumber\", 'HolidaysDefinition'[WeekDayNumber],",
                "        \"OffsetWeek\", 'HolidaysDefinition'[OffsetWeek],",
                "        \"HolidayName\", 'HolidaysDefinition'[HolidayName],",
                "        \"SubstituteHoliday\", 'HolidaysDefinition'[SubstituteHoliday],",
                "        \"ConflictPriority\", 'HolidaysDefinition'[ConflictPriority],",
                "        \"@HolidayDate\", [@HolidayDate],",
                "        \"@SubstituteHolidayOffset\",",
                "            VAR _CurrentHolidayDate = [@HolidayDate]",
                "            VAR _CurrentHolidayName = 'HolidaysDefinition'[HolidayName]",
                "            VAR _OriginalSubstituteDate = [@HolidayDate] + [@SubstituteHolidayOffset]",
                "            VAR _OtherHolidays = ",
                "                FILTER ( ",
                "                    __GeneratedRawWithDuplicates, ",
                "                    [@HolidayDate] <> _CurrentHolidayDate",
                "                    || 'HolidaysDefinition'[HolidayName] <> _CurrentHolidayName",
                "                )",
                "            VAR _ConflictDay0 = ",
                "                CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _OriginalSubstituteDate",
                "                )",
                "            VAR _ConflictDay1 = ",
                "                _ConflictDay0 ",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _OriginalSubstituteDate + 1",
                "                )",
                "            VAR _ConflictDay2 = ",
                "                _ConflictDay1 ",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _OriginalSubstituteDate + 2",
                "                )",
                "            VAR _SubstituteOffsetStep1 = [@SubstituteHolidayOffset] + _ConflictDay0 + _ConflictDay1 + _ConflictDay2",
                "            VAR _HolidayDateStep1 = _CurrentHolidayDate + _SubstituteOffsetStep1",
                "            VAR _HolidayDayStep1 =",
                "                WEEKDAY ( _HolidayDateStep1, 1 ) - 1",
                "            VAR _SubstituteHolidayOffsetNonWorkingDays =",
                "                IF (",
                "                    NOT CONTAINS ( __WorkingDays, ''[Value], _HolidayDayStep1 ),",
                "                    VAR _NextWorkingDayStep2 =",
                "                        MINX (",
                "                            FILTER ( __WorkingDays, ''[Value] > _HolidayDayStep1 ),",
                "                            ''[Value]",
                "                        )",
                "                    VAR _SubstituteDay =",
                "                        IF (",
                "                            ISBLANK ( _NextWorkingDayStep2 ),",
                "                            MINX ( __WorkingDays, ''[Value] ) + 7,",
                "                            _NextWorkingDayStep2",
                "                        )",
                "                    RETURN _SubstituteDay - _HolidayDateStep1",
                "                )",
                "            VAR _SubstituteOffsetStep2 = _SubstituteOffsetStep1 + _SubstituteHolidayOffsetNonWorkingDays",
                "            VAR _SubstituteDateStep2 = _OriginalSubstituteDate + _SubstituteOffsetStep2",
                "            VAR _ConflictDayStep2_0 = ",
                "                CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _SubstituteDateStep2",
                "                )",
                "            VAR _ConflictDayStep2_1 = ",
                "                _ConflictDayStep2_0",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _SubstituteDateStep2 + 1",
                "                )",
                "            VAR _ConflictDayStep2_2 = ",
                "                _ConflictDayStep2_1 ",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _SubstituteDateStep2 + 2",
                "                )",
                "            VAR _FinalSubstituteHolidayOffset = ",
                "                _SubstituteOffsetStep2 + _ConflictDayStep2_0 + _ConflictDayStep2_1 + _ConflictDayStep2_2",
                "            RETURN",
                "                _FinalSubstituteHolidayOffset",
                "        )",
                "VAR __GeneratedSubstitutesExpanded =",
                "    ADDCOLUMNS (",
                "        __GeneratedSubstitutesOffset,",
                "        \"@ReplacementHolidayDate\", [@HolidayDate] + [@SubstituteHolidayOffset]",
                "    )",
                "VAR __GeneratedSubstitutesUnique =",
                "    DISTINCT ( ",
                "        SELECTCOLUMNS ( ",
                "            __GeneratedSubstitutesExpanded,",
                "            \"@UniqueReplacementHolidayDate\", [@ReplacementHolidayDate]",
                "        )",
                "    )",
                "VAR __GeneratedSubstitutes =",
                "    GENERATE (",
                "        __GeneratedSubstitutesUnique,",
                "        TOPN (",
                "            1,",
                "            FILTER ( ",
                "                __GeneratedSubstitutesExpanded,",
                "                [@UniqueReplacementHolidayDate] = [@ReplacementHolidayDate]",
                "            ),",
                "            [ConflictPriority],",
                "            ASC,",
                "            [HolidayName], ",
                "            ASC",
                "        )",
                "    )  ",
                "VAR __Generated =",
                "    UNION (",
                "        SELECTCOLUMNS (",
                "            __GeneratedRaw,",
                "            \"Holiday Date\", [@HolidayDate],",
                "            \"Holiday Name\", 'HolidaysDefinition'[HolidayName]",
                "        ),",
                "        SELECTCOLUMNS (",
                "            FILTER ( __GeneratedSubstitutes, [@SubstituteHolidayOffset] <> 0 ), ",
                "            \"Holiday Date\", [@HolidayDate] + [@SubstituteHolidayOffset],",
                "            \"Holiday Name\", __InLieuOfPrefix & [HolidayName]",
                "                & __InLieuOfSuffix",
                "        )",
                "    )",
                "VAR __GeneratedValidDates =",
                "    FILTER ( __Generated, [Holiday Date] > 2 )",
                "RETURN",
                "    __GeneratedValidDates"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Holidays"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Holidays"
          }
        ]
      },
      {
        "name": "DateAutoTemplate",
        "isHidden": true,
        "lineageTag": "c49fe44d-784b-49ac-bd67-be138c897a13",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "ce011841-1930-439e-99a8-496f9830ca57",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year]",
            "lineageTag": "e1574215-ba1d-40e3-aab3-0106f2d25bc8",
            "dataCategory": "Years",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Quarter Number]",
            "lineageTag": "9394d7cf-4735-445e-9ff9-d60e22327dea",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Quarter]",
            "sortByColumn": "Year Quarter Number",
            "lineageTag": "da68c2b3-8514-417f-a102-da47948a1ffa",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Quarter]",
            "lineageTag": "a9117099-8baf-43bb-ba26-b481a8d0bd56",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Month]",
            "sortByColumn": "Year Month Number",
            "lineageTag": "83b44a42-1f0c-4bc9-aca6-f3334b417ea3",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Month Number]",
            "lineageTag": "f66bb191-d34e-4cb0-9c66-4d1f728fcafc",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Month]",
            "sortByColumn": "Month Number",
            "lineageTag": "241258b6-b45a-494c-a4fa-c95d2be89c50",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Month Number]",
            "lineageTag": "aea2310f-0bcd-4f6f-8188-616ffecf4d3e",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Day of Week Number]",
            "lineageTag": "73a3f8e5-3035-43d7-9ff8-80163cfbd6ea",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Day of Week]",
            "sortByColumn": "Day of Week Number",
            "lineageTag": "aed0abff-ff15-4ad6-a56b-1cea99ee856b",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWorking",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsWorking]",
            "lineageTag": "22bf63f4-8c7b-4e9e-975f-0aa404ec80b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Working Day Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Working Day Value]",
            "lineageTag": "e10009c2-a498-41ff-afbf-23f705e705ca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Holiday Name]",
            "lineageTag": "f355c68a-811b-4bfc-b2c7-98c787026733",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DateWithTransactions",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[DateWithTransactions]",
            "lineageTag": "e157143c-b286-485b-8793-8aab7335cddd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateAutoTemplate",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "--  ",
                "--     Configuration",
                "--  ",
                "VAR __FirstDayOfWeek = 1",
                "VAR __WorkingDays = { 2, 3, 4, 5, 6 }",
                "----------------------------------------",
                "VAR __WeekDayCalculationType = IF ( __FirstDayOfWeek = 0, 7, __FirstDayOfWeek ) + 10",
                "VAR __Calendar = ",
                "    VAR __FirstYear = YEAR ( MINX ( { MIN ( 'metrika_stats'[date] ) }, ''[Value] ) )",
                "    VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'metrika_stats'[date] ) }, ''[Value] ) )",
                "    RETURN CALENDAR (",
                "        DATE ( __FirstYear, 1, 1 ),",
                "        DATE ( __LastYear, 12, 31 )",
                "    )",
                "VAR __Step3 = ",
                "    GENERATE (",
                "        __Calendar,",
                "        VAR __IsStandardLocale = IF ( FORMAT( DATE( 2000, 1, 1 ), \"oooo\" ) = \"oooo\", TRUE, FALSE )",
                "        VAR __MonthFormatString = IF( __IsStandardLocale, \"mmm\", \"ooo\" )",
                "        VAR __DayFormatString = IF( __IsStandardLocale, \"ddd\", \"aaa\" )",
                "        VAR __LastTransactionDate = MAXX ( { MAX ( 'metrika_stats'[date] ) }, ''[Value] )",
                "        VAR __Date = [Date]",
                "        VAR __YearNumber = YEAR ( __Date )",
                "        VAR __QuarterNumber = QUARTER ( __Date )",
                "        VAR __YearQuarterNumber = CONVERT ( __YearNumber * 4 + __QuarterNumber - 1, INTEGER )",
                "        VAR __MonthNumber = MONTH ( __Date )",
                "        VAR __WeekDayNumber = WEEKDAY ( __Date, __WeekDayCalculationType )",
                "        VAR __WeekDay = FORMAT ( __Date, __DayFormatString )",
                "        VAR __HolidayName = LOOKUPVALUE ( 'Holidays'[Holiday Name], 'Holidays'[Holiday Date],  __Date  )",
                "        VAR __IsWorkingDay = WEEKDAY ( __Date, 1 ) IN __WorkingDays && ISBLANK ( __HolidayName )",
                "        RETURN ROW ( ",
                "            \"Year\", __YearNumber,",
                "            \"Year Quarter Number\", __YearQuarterNumber,",
                "            \"Year Quarter\", FORMAT ( __QuarterNumber, \"\\Q0\" ) & \"-\" & FORMAT ( __YearNumber, \"0000\" ),",
                "            \"Quarter\", FORMAT( __QuarterNumber, \"\\Q0\" ),",
                "            \"Year Month\", FORMAT ( __Date, __MonthFormatString & \" yyyy\" ),",
                "            \"Year Month Number\", __YearNumber * 12 + __MonthNumber - 1,",
                "            \"Month\", FORMAT ( __Date, __MonthFormatString ),",
                "            \"Month Number\", __MonthNumber,",
                "            \"Day of Week Number\", __WeekDayNumber,",
                "            \"Day of Week\", __WeekDay,",
                "            \"IsWorking\", __IsWorkingDay,",
                "            \"Working Day Value\", IF ( __IsWorkingDay, 1 ),",
                "            \"Holiday Name\", __HolidayName,",
                "            \"DateWithTransactions\", __Date <= __LastTransactionDate ",
                "        )",
                "    )",
                "RETURN",
                "    __Step3"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "isHidden": true,
            "lineageTag": "42aca588-7ffb-4068-8c9b-9c64a7d2277b",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "b9e466a5-b8b5-4d07-aaae-a2f7d1bdbfd5"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Year Month",
                "lineageTag": "bc1718cb-5b92-4869-afab-4e5232ea6e10"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "0af8883f-f398-469b-9c1a-ce9411783d12"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "DateAutoTemplate"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "422c31b7-21dc-4e79-9b8f-ea767669993f",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "DateAutoTemplate[Date]",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "dec37d1d-a5ed-45ba-b4f3-f5212ebc935b",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Year]",
            "lineageTag": "f5459c73-da7f-4693-ae7f-bb4c2ceb32c2",
            "dataCategory": "Years",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Year Quarter Number]",
            "lineageTag": "3d034e17-7e70-45fa-93ac-c36562df29b2",
            "dataCategory": "Quarters",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Year Quarter]",
            "sortByColumn": "Year Quarter Number",
            "lineageTag": "ee2e41f1-0c5c-448d-a13c-1851c651e182",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Quarter]",
            "lineageTag": "895a7152-d80c-4758-98c8-d70b79a84129",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Year Month]",
            "sortByColumn": "Year Month Number",
            "lineageTag": "0c84c053-fe7c-4a82-9782-cd4aa518b98c",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Year Month Number]",
            "lineageTag": "83102252-2e20-4c3d-a59f-da1fb3c22078",
            "dataCategory": "Months",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Month]",
            "sortByColumn": "Month Number",
            "lineageTag": "a900f04d-dc43-478f-b0fa-24f3a05dc9df",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Month Number]",
            "lineageTag": "057afa39-3606-41d0-8a61-4186d0cfb55f",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Day of Week Number]",
            "lineageTag": "1655a312-7cfd-4b24-b312-9e251d92042b",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Day of Week]",
            "sortByColumn": "Day of Week Number",
            "lineageTag": "00f205f4-c331-426c-bc9a-273954b94a31",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWorking",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[IsWorking]",
            "lineageTag": "742a582c-ecfd-4c66-abcd-a0b23cf816f2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Working Day Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Working Day Value]",
            "lineageTag": "c578ab67-23bc-41d5-89d0-62fe97811387",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Holiday Name]",
            "lineageTag": "785e7660-3387-4cd5-9310-c879df9155f2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DateWithTransactions",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[DateWithTransactions]",
            "lineageTag": "b128de9d-9cb5-46e1-9ad2-64f7914b1efd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNow",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "AND(",
              "",
              "        'Date'[Month Number]=MONTH(TODAY()-1),",
              "",
              "        'Date'[Year]=YEAR(TODAY())",
              "",
              "    )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "917624e9-6ef4-4f6e-a2dd-d1a6e0ae1214",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthPrev",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "AND(",
              "",
              "        'Date'[Month Number]=MONTH(TODAY()-1)-1,",
              "",
              "        'Date'[Year]=YEAR(TODAY())",
              "",
              "    )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "51da1fb2-2cd1-4e1d-8dcb-e08878ec8d8e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Select_period",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(CONTAINS(metrika_stats, 'metrika_stats'[Date], 'Date'[Date]), 1, 0)",
            "formatString": "0",
            "lineageTag": "ff267c91-6e8f-4341-8a4a-0eabbe9b1667",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Week Start",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "    VAR CurrentDate = 'Date'[Date]",
              "    VAR DaysSinceMonday = WEEKDAY(CurrentDate, 2) - 1",
              "    RETURN CurrentDate - DaysSinceMonday"
            ],
            "formatString": "General Date",
            "lineageTag": "b7ab0b77-8917-43e4-8667-a59fab09aac5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Week End",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "    VAR CurrentDate = 'Date'[Date]",
              "    VAR DaysUntilSunday = 7 - WEEKDAY(CurrentDate, 2)",
              "    RETURN CurrentDate + DaysUntilSunday"
            ],
            "formatString": "General Date",
            "lineageTag": "9fc54102-b41a-406c-b7ba-945e8a246bbe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Week Range",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('Date'[Week Start],\"YYYY-MM-DD\")&\" - \"&FORMAT('Date'[Week End],\"YYYY-MM-DD\")",
            "lineageTag": "08b6ffa8-2174-4c9f-92b4-2209afd3a028",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "WeekNow",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "WEEKNUM('Date'[Date],2) = WEEKNUM(TODAY(),2) && YEAR('Date'[Date]) = YEAR(TODAY())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "aff4a492-0e71-47cf-bebf-e04f3a7a412c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "WeekPrev",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "WEEKNUM('Date'[Date],2) = WEEKNUM(TODAY()-1,2)-1 && YEAR('Date'[Date]) = YEAR(TODAY())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8914d467-b93b-425e-b519-64992415248d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Start of Week",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "LEFT([Week Range], 10)",
            "lineageTag": "27cf2dab-846f-457e-bc2a-22d68b72b6d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Yesterday",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "TODAY()-1 = 'Date'[Date]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ec1df4cd-bfca-415d-886a-04a88ef22b90",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Prev7days",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": [
              "AND(",
              "",
              "        TODAY()-1>'Date'[Date],",
              "",
              "        TODAY()-8<='Date'[Date]",
              "",
              "    )"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ad573090-c808-4b60-b237-906f2d3e430f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "All",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "expression": "IF(AND('Date'[Date] >= FIRSTDATE(metrika_stats[Date]), 'Date'[Date] <= LASTDATE(metrika_stats[Date])), TRUE(), FALSE())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "666ff3ca-5ee9-4a6d-933e-b0f7dfade105",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DateAutoTemplate"
            }
          }
        ],
        "measures": [
          {
            "name": "_ShowValueForDates",
            "expression": [
              "",
              "VAR __LastDateWithData =",
              "    CALCULATE (",
              "        MAXX ( { MAX ( 'metrika_stats'[date] ) }, ''[Value] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR __FirstDateVisible =",
              "    MIN ( 'Date'[Date] )",
              "VAR __Result =",
              "    __FirstDateVisible <= __LastDateWithData",
              "RETURN",
              "    __Result"
            ],
            "isHidden": true,
            "displayFolder": "Hidden Time Intelligence",
            "lineageTag": "f1839528-e245-48de-b468-d5396291b9e7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "lineageTag": "be282697-f9ef-433e-8276-96c85f7d2155",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "1a2083db-6cdd-416d-b15c-ffe5b154ccd5"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Year Month",
                "lineageTag": "19fd6c3f-8999-415b-9476-88627b2d7c80"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "c88a5ab3-0fc3-4180-86bb-cfa88d9525ed"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Date"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ]
      },
      {
        "name": "Choose period",
        "lineageTag": "8f807396-8f14-4c32-862a-d89efe050b44",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Свой диапазон",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[All]",
                "    )",
                ")"
              ],
              "ordinal": 0
            },
            {
              "name": "Вчера",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[Yesterday]",
                "    )",
                ")"
              ],
              "ordinal": 1
            },
            {
              "name": "Последняя неделя",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[WeekNow]",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "Прошлая неделя",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[WeekPrev]",
                "    )",
                ")"
              ],
              "ordinal": 3
            },
            {
              "name": "Последний месяц",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[MonthNow]",
                "    )",
                ")"
              ],
              "ordinal": 4
            },
            {
              "name": "Прошлый месяц",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[MonthPrev]",
                "    )",
                ")"
              ],
              "ordinal": 5
            },
            {
              "name": "Последние 7 дней",
              "expression": [
                "CALCULATE (",
                "    SELECTEDMEASURE (),",
                "    TREATAS (",
                "        {",
                "            TRUE",
                "        },",
                "        'Date'[Prev7days]",
                "    )",
                ")"
              ],
              "ordinal": 6
            }
          ]
        },
        "columns": [
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "bf0222d7-7e54-4c8e-9bd9-1007f645a203",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "d5787076-b54c-4aff-8bea-b8a3c74f43bb"
          },
          {
            "type": "calculated",
            "name": "chk",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF('Choose period'[Name] = \"Последняя неделя\", [WEEKNOW_CHECK], 0)",
            "lineageTag": "1b0e9e9c-4622-4c6f-808c-703394986941",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "_goals",
        "lineageTag": "9f531d33-8b40-437a-9990-71180244e030",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "79c667fc-9a54-42bd-945c-eb10fe6bab14",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Goal",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(_goals[Value],",
              "1, \"клик по номеру\",",
              "2, \"отправка формы\",",
              "3, \"Заказ посещения\")"
            ],
            "lineageTag": "4aa0ba3f-817e-4765-a589-a982a6cffed8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_goals-d64c650e-e5aa-414c-8652-a7dfc2a11609",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(1,3,1)"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a4f7d9a11ca84580b414c22e4b1928d3"
          }
        ]
      },
      {
        "name": "Показатели",
        "lineageTag": "5413d67c-c216-4fd3-b513-08013866906e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Показатели таблиц",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ Показатели",
            "lineageTag": "ea95594e-ff85-4ab4-9d4c-9bfb8290b6f6",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: Показатели"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: Показатели",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ Показатели",
            "lineageTag": "fd5790b9-01f3-41bd-88e6-a9e4d888789b",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ Показатели",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "76b14699-9bca-49d4-81cf-809b1082b94a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Показатели-91a8dc15-4cfa-4c0b-887a-b1645f33a363",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Визиты\", NAMEOF('_measures'[Визиты]), 0),",
                "    (\"Показы\", NAMEOF('_measures'[Показы]), 1),",
                "    (\"Клики\", NAMEOF('_measures'[Клики]), 2),",
                "    (\"Расход\", NAMEOF('_measures'[Расход]), 3),",
                "    (\"Кликабельность\", NAMEOF('_measures'[Кликабельность]), 4),",
                "    (\"Стоимость клика\", NAMEOF('_measures'[Стоимость клика]), 5),",
                "    (\"Целевые действия\", NAMEOF('_measures'[Целевые действия]), 6),",
                "    (\"Стоимость действ.\", NAMEOF('_measures'[Стоимость действ.]), 7),",
                "    (\"% Конверсия\", NAMEOF('_measures'[% Конверсия]), 8),",
                "    (\"Ассоц. конв.\", NAMEOF('_measures'[Ассоц. конв.]), 9),",
                "    (\"% Отказов\", NAMEOF('_measures'[% Отказов]), 10),",
                "    (\"Глубина просмотра\", NAMEOF('_measures'[Глубина просмотра]), 11)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3cfbb6ed1fc14c6cb3f74cc4052ef049"
          }
        ]
      },
      {
        "name": "TrafficSources",
        "lineageTag": "c594995f-28c2-46a6-88c8-473e6eff2527",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "NewTypes",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[NewTypes]",
            "lineageTag": "039b33ef-09bd-45a0-9244-3b66626af41f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "TrafficSources-0676612e-c29d-4783-95a8-1cbc7f3affaf",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "CALCULATETABLE(DISTINCT(metrika_stats[NewTypes]),metrika_stats[NewTypes] <> BLANK())"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "266768765bcf4ac5ac7ee8735651fe3a"
          }
        ]
      },
      {
        "name": "CPA_mode",
        "lineageTag": "acbb61e5-d414-42b4-93c6-d836f87e0077",
        "columns": [
          {
            "name": "Расчет CPA",
            "dataType": "string",
            "sourceColumn": "Расчет CPA",
            "lineageTag": "7590e62e-4dcd-4102-91d1-cf8427e727ed",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CPA_mode-1514df0d-4aef-483a-817f-16fdcda6e448",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"ZY3BCYUwEERbWXL+HUl6MUHxIgr/aBUSEUUxtjDTkROvXhZm9u3bqnL448DJgR1mjqaQcSFhZc2AHbtpbIaktLJVYmBEFn9pU/Dk/E+i6XNZOLn7QhmD4capL1FYxlK6yFpF84pm5/0D\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Расчет CPA\" = _t]),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Расчет CPA\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "_interface_A",
        "lineageTag": "685db208-84a2-4948-8096-866b37f2b3eb",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Показатели 1 графика",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ _interface_A",
            "lineageTag": "9e963d99-be79-4586-b7c9-5c18b95e1289",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: _interface_A"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: _interface_A",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ _interface_A",
            "lineageTag": "a56f63fb-77ee-47c5-9209-3572bb0fe4eb",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ _interface_A",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "e248e4f5-60bf-4ab5-b3fb-030ee2073874",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_interface_A-b5f35af0-d6bb-4a5f-88b5-7059c33d2aa5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Визиты\", NAMEOF('_measures'[Визиты]), 0),",
                "    (\"Показы\", NAMEOF('_measures'[Показы]), 1),",
                "    (\"Клики\", NAMEOF('_measures'[Клики]), 2),",
                "    (\"Расход\", NAMEOF('_measures'[Расход]), 3),",
                "    (\"Целевые действия\", NAMEOF('_measures'[Целевые действия]), 4),",
                "    (\"Стоимость клика\", NAMEOF('_measures'[Стоимость клика]), 5),",
                "    (\"Стоимость действ.\", NAMEOF('_measures'[Стоимость действ.]), 6),",
                "    (\"Кликабельность\", NAMEOF('_measures'[Кликабельность]), 7),",
                "    (\"% Конверсия\", NAMEOF('_measures'[% Конверсия]), 8),",
                "    (\"% Отказов\", NAMEOF('_measures'[% Отказов]), 9),",
                "    (\"Глубина просмотра\", NAMEOF('_measures'[Глубина просмотра]), 10)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f820bce1a3854e969d63e4493fb627e5"
          }
        ]
      },
      {
        "name": "_interface_B",
        "lineageTag": "fe54aea5-4f27-4733-abb6-d5ae1bb3fdb2",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Показатели 2 графика",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ _interface_B",
            "lineageTag": "bbb60406-840c-4023-9015-8387eebf2950",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: _interface_B"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: _interface_B",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ _interface_B",
            "lineageTag": "0f42cee4-ad64-41a2-8d61-5c4a5ee579eb",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ _interface_B",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "1ec7f717-878e-4797-8329-18146006c0e9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_interface_B-4391200f-12c1-44df-898e-0eedf59b8bae",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Визиты\", NAMEOF('_measures'[Визиты]), 0),",
                "    (\"Показы\", NAMEOF('_measures'[Показы]), 1),",
                "    (\"Клики\", NAMEOF('_measures'[Клики]), 2),",
                "    (\"Расход\", NAMEOF('_measures'[Расход]), 3),",
                "    (\"Целевые действия\", NAMEOF('_measures'[Целевые действия]), 4),",
                "    (\"Стоимость клика\", NAMEOF('_measures'[Стоимость клика]), 5),",
                "    (\"Стоимость действ.\", NAMEOF('_measures'[Стоимость действ.]), 6),",
                "    (\"Кликабельность\", NAMEOF('_measures'[Кликабельность]), 7),",
                "    (\"% Конверсия\", NAMEOF('_measures'[% Конверсия]), 8),",
                "    (\"% Отказов\", NAMEOF('_measures'[% Отказов]), 9),",
                "    (\"Глубина просмотра\", NAMEOF('_measures'[Глубина просмотра]), 10),",
                "    (\"Скрыть\", NAMEOF('_measures'[BLANK_GRAPH]), 10)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cbec93e9bf8c4a419b47061f79e892a0"
          }
        ]
      },
      {
        "name": "Агрегация",
        "lineageTag": "d970b5f4-13c6-416f-ba78-a9c0f9fc17de",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Агрегация",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ Агрегация",
            "lineageTag": "500d6b9a-9291-428f-b2d1-47dd3674e627",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: Агрегация"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: Агрегация",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ Агрегация",
            "lineageTag": "044aa931-5570-417b-a1ec-d10fe5036699",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ Агрегация",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "e209190b-6d69-4807-ae0b-51a47f4c6aeb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Агрегация-1dc07db6-f8ce-4500-8917-09bc4efd7700",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"По дням\", NAMEOF('Date'[Date]), 0),",
                "    (\"По неделям\", NAMEOF('Date'[Week Range]), 1),",
                "    (\"По месяцам\", NAMEOF('Date'[Year Month]), 2)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bc81c7a0f98a4ec1b00a641844eedc6a"
          }
        ]
      },
      {
        "name": "Детализация",
        "lineageTag": "d793f773-5fe4-4239-937f-054a0dfb60b4",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Детализация",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ Детализация",
            "lineageTag": "1a6085bf-b985-4960-8c8f-a8be415ffeee",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: Детализация"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: Детализация",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ Детализация",
            "lineageTag": "3c3e6913-c2e7-4338-8653-bb0801c546fe",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ Детализация",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "21a441fd-8021-4052-9ff0-90d94999e6c6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Детализация-7d4db4e7-e0ac-4e59-b4d2-8e491cc0544f",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Проект\", NAMEOF('metrika_stats'[tag]), 0),",
                "    (\"Тип трафика\", NAMEOF('metrika_stats'[NewTypes]), 1),",
                "    (\"Источник\", NAMEOF('metrika_stats'[NewEngines]), 2)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3a921baf59e04bc5bb99cead3acaaeb2"
          }
        ]
      },
      {
        "name": "Tags",
        "lineageTag": "c0c6b835-1f02-437e-9cc4-9c2a1ead773f",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "tag",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[tag]",
            "lineageTag": "69aec93e-4b11-4484-9181-78e209207bbd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Tags-54c45c65-a314-4158-81bd-5c667176cf9f",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "CALCULATETABLE(DISTINCT(metrika_stats[tag]),metrika_stats[tag] <> BLANK())"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "16953a09ff554165aa022f4a25b749d0"
          }
        ]
      },
      {
        "name": "Campaigns_list",
        "lineageTag": "de2889ef-96f4-427b-bd50-3f5bab25c7df",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CampaignId",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[CampaignId]",
            "lineageTag": "9ece6875-d8cb-4dfa-bc91-287057d123b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "CampaignName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[CampaignName]",
            "lineageTag": "bfaf77ad-9a85-43f5-a4b8-4cd0cf13facb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "NewEngines",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[NewEngines]",
            "lineageTag": "c69c9fdd-386c-420a-a5bf-995c86f749b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "tag",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[tag]",
            "lineageTag": "833e60bd-f8ff-443f-bcc1-603afdef7aca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Campaigns_list-42e8bc91-2fd5-4b93-b1fb-debd6a4764af",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "CALCULATETABLE(GROUPBY(metrika_stats,",
                "                                        metrika_stats[CampaignId],",
                "                                        metrika_stats[CampaignName],",
                "                                        metrika_stats[NewEngines],",
                "                                        metrika_stats[tag]),",
                "                                        metrika_stats[CampaignName] <> BLANK()",
                "                                        )"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bbb9361d644b458eb14d02951ef65ffc"
          }
        ]
      },
      {
        "name": "Детализация_CPC",
        "lineageTag": "baee4bc5-5b15-4377-9a04-8adde6467d9f",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Детализация_CPC",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ Детализация_CPC",
            "lineageTag": "9cb3f130-e420-4460-bd28-4cd47f2ddd56",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: Детализация_CPC"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: Детализация_CPC",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ Детализация_CPC",
            "lineageTag": "978be469-4179-40ca-a7d2-aff1eeaa5a25",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ Детализация_CPC",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "f66aed5a-448d-411a-accb-ffa005ade64f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Детализация_CPC-c030524f-c72a-45e7-b7dc-0a140b1aa30d",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Проект\", NAMEOF('Tags'[tag]), 0),",
                "    (\"Кампания\", NAMEOF('Campaigns_list'[CampaignName]), 1)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fe67ea08992d49d4ba3e440e3bc8f9f6"
          }
        ]
      },
      {
        "name": "States",
        "lineageTag": "85da0d2c-a647-4296-a4d3-dd9a09b3601c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CampaignId",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Campaigns_list[CampaignId]",
            "lineageTag": "da97b43c-4bd1-4bb8-83c4-f73e7f6359ba",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "state",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "metrika_stats[state]",
            "lineageTag": "d2e8695e-ca65-48cc-b6bf-8f0cb628c7b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "For_Matrix",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(States[state] = \"работает\", 1, 0)",
            "formatString": "0",
            "lineageTag": "0fd44264-55aa-46e1-ad6d-bfc195315382",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "States-cb398613-ed73-4317-8b15-66d64b2fd2ac",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "CALCULATETABLE(GROUPBY(metrika_stats,Campaigns_list[CampaignId],metrika_stats[state]), metrika_stats[state] <> BLANK())"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c758f16c5d764ca2be3eaec1c112d246"
          }
        ]
      },
      {
        "name": "_interface_A_YD",
        "lineageTag": "5d2222fd-5bd3-4b7f-841f-5a6e32bb2708",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "_interface_A_YD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ _interface_A_YD",
            "lineageTag": "becb45e5-aca5-4be1-82d6-d44e797a5917",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: _interface_A_YD"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: _interface_A_YD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ _interface_A_YD",
            "lineageTag": "8ae4c22c-bcd9-4a80-a328-8f88c2bfd060",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ _interface_A_YD",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "79e6bc46-dc69-4713-8361-15d5a286399e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_interface_A_YD-82b5f176-c3bd-46fd-bb0e-42b334b9ca15",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Показы\", NAMEOF('_measures'[Показы YD]), 0),",
                "    (\"Клики\", NAMEOF('_measures'[Клики YD]), 1),",
                "    (\"Расход\", NAMEOF('_measures'[Расход YD]), 2),",
                "    (\"Целевые действия\", NAMEOF('_measures'[Целевые действия YD]), 3),",
                "    (\"Стоимость клика\", NAMEOF('_measures'[Стоимость клика YD]), 4),",
                "    (\"Стоимость действ.\", NAMEOF('_measures'[Стоимость действ. YD]), 5),",
                "    (\"Кликабельность\", NAMEOF('_measures'[Кликабельность YD]), 6),",
                "    (\"% Конверсия\", NAMEOF('_measures'[% Конверсия YD]), 7),",
                "    (\"% Отказов\", NAMEOF('_measures'[% Отказов YD]), 8),",
                "    (\"Глубина просмотра\", NAMEOF('_measures'[Глубина просмотра YD]), 9)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "07f0cf6ef9c541a18146040d669e67f9"
          }
        ]
      },
      {
        "name": "_interface_B_YD",
        "lineageTag": "f5148546-b6ac-48ab-9147-1d5869180360",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "_interface_B_YD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ _interface_B_YD",
            "lineageTag": "06c123d1-04fb-461b-b653-340a61671d3c",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: _interface_B_YD"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: _interface_B_YD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ _interface_B_YD",
            "lineageTag": "1dc20e71-12f0-4705-8270-4df871ac6edf",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ _interface_B_YD",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "9e1fc8b4-91b4-417e-9396-3db827cab49d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_interface_B_YD-63535ed9-1904-47d9-be30-955f9f441fdf",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Показы\", NAMEOF('_measures'[Показы YD]), 0),",
                "    (\"Клики\", NAMEOF('_measures'[Клики YD]), 1),",
                "    (\"Расход\", NAMEOF('_measures'[Расход YD]), 2),",
                "    (\"Целевые действия\", NAMEOF('_measures'[Целевые действия YD]), 3),",
                "    (\"Стоимость клика\", NAMEOF('_measures'[Стоимость клика YD]), 4),",
                "    (\"Стоимость действ.\", NAMEOF('_measures'[Стоимость действ. YD]), 5),",
                "    (\"Кликабельность\", NAMEOF('_measures'[Кликабельность YD]), 6),",
                "    (\"% Конверсия\", NAMEOF('_measures'[% Конверсия YD]), 7),",
                "    (\"% Отказов\", NAMEOF('_measures'[% Отказов YD]), 8),",
                "    (\"Глубина просмотра\", NAMEOF('_measures'[Глубина просмотра YD]), 9),",
                "    (\"Скрыть\", NAMEOF('_measures'[BLANK_GRAPH]), 10)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "37400d0beb874a07b26b1d49bf9c3d33"
          }
        ]
      },
      {
        "name": "Доп_Показатели_YD",
        "lineageTag": "a293da2e-5a5d-4970-9daa-20e0cc366cca",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Доп_Показатели_YD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ Доп_Показатели_YD",
            "lineageTag": "83d83e7a-4c79-428e-bb6f-9095ae6fb6c0",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: Доп_Показатели_YD"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: Доп_Показатели_YD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ Доп_Показатели_YD",
            "lineageTag": "8b7cbb44-fd00-403f-af31-c73efa7be61b",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ Доп_Показатели_YD",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "cdaf3cfd-adf0-4ef3-bcc4-a4f30b3b346e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Доп_Показатели_YD-27faa6f1-4a1a-482e-a77e-1d9a1db81828",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Показы\", NAMEOF('_measures'[Показы YD]), 0),",
                "    (\"Клики\", NAMEOF('_measures'[Клики YD]), 1),",
                "    (\"Расход\", NAMEOF('_measures'[Расход YD]), 2),",
                "    (\"Кликабельность\", NAMEOF('_measures'[Кликабельность YD]), 3),",
                "    (\"Стоимость клика\", NAMEOF('_measures'[Стоимость клика YD]), 4),",
                "    (\"Целевые действия\", NAMEOF('_measures'[Целевые действия YD]), 5),",
                "    (\"Стоимость действ.\", NAMEOF('_measures'[Стоимость действ. YD]), 6),",
                "    (\"% Конверсия\", NAMEOF('_measures'[% Конверсия YD]), 7),",
                "    (\"% Отказов\", NAMEOF('_measures'[% Отказов YD]), 8),",
                "    (\"Глубина просмотра\", NAMEOF('_measures'[Глубина просмотра YD]), 9)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "129e018d8ddb42e5b05a24faa3f3e96e"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "22c62910-a1a3-45aa-b7f9-03662e6f7d89",
        "fromTable": "metrika_stats",
        "fromColumn": "date",
        "toTable": "Date",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "1fded97a-1ce3-4fe0-995b-a8fa8be48693",
        "fromTable": "metrika_stats",
        "fromColumn": "NewTypes",
        "toTable": "TrafficSources",
        "toColumn": "NewTypes",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2c4505c1-03b7-4044-9cb1-eb32c754da89",
        "fromTable": "metrika_stats",
        "fromColumn": "tag",
        "toTable": "Tags",
        "toColumn": "tag"
      },
      {
        "name": "6bf87dd2-3f8e-4ab5-b9c1-e67af3703312",
        "fromTable": "ydirect_extended",
        "fromColumn": "tag",
        "toTable": "Tags",
        "toColumn": "tag",
        "isActive": false
      },
      {
        "name": "3acafc1f-9515-4322-9dad-7f1ae479af15",
        "fromTable": "metrika_stats",
        "fromColumn": "CampaignId",
        "toTable": "Campaigns_list",
        "toColumn": "CampaignId",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "3b41d6f0-6188-498d-a932-edcbcdc370ad",
        "fromTable": "ydirect_extended",
        "fromColumn": "CampaignId",
        "toTable": "Campaigns_list",
        "toColumn": "CampaignId",
        "isActive": false
      },
      {
        "name": "762933d0-2f4b-497f-9045-71824a4221a3",
        "fromCardinality": "one",
        "fromTable": "Campaigns_list",
        "fromColumn": "CampaignId",
        "toTable": "States",
        "toColumn": "CampaignId",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "727e83f6-9983-45b3-b933-edf83c70fd39",
        "fromTable": "ydirect_extended",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "cultures": [
      {
        "name": "ru-RU",
        "linguisticMetadata": {}
      }
    ],
    "extendedProperties": [
      {
        "type": "json",
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "value": {
          "templateUri": "file:///C:/Users/Alexander/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "isCurrent": false,
          "isCustom": false,
          "name": "Config-01",
          "description": "Standard gregorian calendar",
          "autoScan": 1,
          "onlyTablesColumns": [
            "'metrika_stats'[date]"
          ],
          "exceptTablesColumns": [],
          "isoCountry": "RU",
          "autoNaming": 1,
          "targetMeasures": [],
          "defaults": {
            "firstDayOfWeek": 1
          },
          "dateAvailable": true,
          "dateEnabled": true,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "holidaysAvailable": true,
          "holidaysEnabled": true,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 1,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 1,
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "expressions": [
      {
        "name": "associate_conv_campaigns",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
          "    public_control_assists_camp = Источник{[Schema=\"public\",Item=\"control_assists_camp\"]}[Data],",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(public_control_assists_camp,{\"index\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Удаленные столбцы\",{{\"date\", type date}}),",
          "    #\"ОПРЕДЕЛЯЕМ НЕЙМИНГ РК\" = Table.NestedJoin(#\"Измененный тип\", {\"tag\", \"utm_medium\", \"utm_source\", \"utm_campaign\"}, all_camps, {\"tag\", \"utm_medium\", \"utm_source\", \"utm_campaign\"}, \"all_camps\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент all_camps\" = Table.ExpandTableColumn(#\"ОПРЕДЕЛЯЕМ НЕЙМИНГ РК\", \"all_camps\", {\"CampaignId\", \"CampaignName\"}, {\"CampaignId\", \"CampaignName\"}),",
          "    #\"ОПРЕДЕЛЯЕМ ТИПЫ\" = Table.AddColumn(#\"Развернутый элемент all_camps\", \"NewTypes\", each if Text.Contains([utm_source], \"yandex\") then \"Контекст\" else if [utm_source] = \"vk\" then \"Таргет\" else if [utm_source] = \"vkontakte\" then \"Таргет\" else if [utm_source] = \"mytarget\" then \"Таргет\" else null),",
          "    #\"ОПРЕДЕЛЯЕМ ИСТОЧНИКИ\" = Table.AddColumn(#\"ОПРЕДЕЛЯЕМ ТИПЫ\", \"NewEngines\", each if Text.Contains([utm_source], \"yandex\") then \"yandex_direct\" else if [utm_source] = \"vk\" then \"vk_ads\" else if [utm_source] = \"vkontakte\" then \"vk_ads\" else if [utm_source] = \"mytarget\" then \"my_target\" else null),",
          "    #\"Измененный тип1\" = Table.TransformColumnTypes(#\"ОПРЕДЕЛЯЕМ ИСТОЧНИКИ\",{{\"NewTypes\", type text}, {\"NewEngines\", type text}})",
          "in",
          "    #\"Измененный тип1\""
        ],
        "queryGroup": "3 Обработка ассоциированных конверсий",
        "lineageTag": "3e5749a0-4961-4f58-9fef-654e74cbb675",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "associate_conv_sources",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
          "    public_control_assists_sour = Источник{[Schema=\"public\",Item=\"control_assists_sour\"]}[Data],",
          "    #\"Вставлено: объединенный столбец\" = Table.AddColumn(public_control_assists_sour, \"Сведено\", each Text.Combine({[lastTrafficSource], [source2]}, \" \"), type text),",
          "    #\"Условный столбец добавлен\" = Table.AddColumn(#\"Вставлено: объединенный столбец\", \"NewTypes\", each if [Сведено] = \"ad ya_direct\" then \"Контекст\" else if [Сведено] = \"ad vkontakte\" then \"Таргет\" else if [lastTrafficSource] = \"organic\" then \"Поисковые системы\" else if [lastTrafficSource] = \"internal\" then \"Внутренние переходы\" else if [lastTrafficSource] = \"direct\" then \"Прямые заходы\" else if [lastTrafficSource] = \"messenger\" then \"Мессенджеры\" else if [lastTrafficSource] = \"recommend\" then \"Рекомендательные системы\" else if [lastTrafficSource] = \"referral\" then \"Ссылки на иных сайтах\" else if [lastTrafficSource] = \"social\" then \"Соцсети\" else if [lastTrafficSource] = \"ad\" then \"Переходы по рекламе\" else \"Неизвестный источник\"),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Условный столбец добавлен\",{{\"NewTypes\", type text}}),",
          "    #\"ОПРЕДЕЛЯЕМ ИСТОЧНИКИ\" = Table.AddColumn(#\"Измененный тип\", \"NewEngines\", each if [Сведено] = \"ad unknown\" then \"другая реклама: определено по меткам\" else if [Сведено] = \"ad vkontakte\" then \"vk_ads\" else if [Сведено] = \"ad mytarget\" then \"my_target\" else if [source2] = \"yandex\" then \"яндекс\" else if [source2] = \"ya_direct\" then \"yandex_direct\" else if [source2] = \"ya_undefined\" then \"yandex_direct\" else if [source2] = \"mail_ru\" then \"mail.ru\" else if [source2] = \"dzen.ru\" then \"дзен\" else [source2]),",
          "    #\"Измененный тип1\" = Table.TransformColumnTypes(#\"ОПРЕДЕЛЯЕМ ИСТОЧНИКИ\",{{\"NewEngines\", type text}}),",
          "    #\"Измененный тип2\" = Table.TransformColumnTypes(#\"Измененный тип1\",{{\"date\", type date}}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Измененный тип2\",{\"index\", \"Сведено\", \"lastTrafficSource\", \"source2\"})",
          "in",
          "    #\"Удаленные столбцы\""
        ],
        "queryGroup": "3 Обработка ассоциированных конверсий",
        "lineageTag": "711e1d31-738e-45fe-934b-ca7ef862e081",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "vkads_stats",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
          "    public_control_vkads_stats = Источник{[Schema=\"public\",Item=\"control_vkads_stats\"]}[Data],",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(public_control_vkads_stats,{\"Date\", \"Impressions\", \"Clicks\", \"Cost\", \"Login\", \"CampaignId\", \"adUrl\", \"state\", \"CampaignName\", \"tag\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Другие удаленные столбцы\",{{\"Date\", type date}}),",
          "    #\"Вставленный текст между разделителями\" = Table.AddColumn(#\"Измененный тип\", \"utm_source\", each Text.BetweenDelimiters([adUrl], \"utm_source=\", \"&\"), type text),",
          "    #\"Вставленный текст между разделителями1\" = Table.AddColumn(#\"Вставленный текст между разделителями\", \"utm_medium\", each Text.BetweenDelimiters([adUrl], \"utm_medium=\", \"&\"), type text),",
          "    #\"Вставленный текст между разделителями2\" = Table.AddColumn(#\"Вставленный текст между разделителями1\", \"utm_campaign\", each Text.BetweenDelimiters([adUrl], \"utm_campaign=\", \"&\"), type text),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Вставленный текст между разделителями2\", {\"Date\", \"tag\", \"Login\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Impressions\", each List.Sum([Impressions]), type nullable number}, {\"Clicks\", each List.Sum([Clicks]), type nullable number}, {\"Cost\", each List.Sum([Cost]), type nullable number}})",
          "in",
          "    #\"Сгруппированные строки\""
        ],
        "queryGroup": "1 Обработка статы для связи с метрикой",
        "lineageTag": "02b73612-b5ee-4b02-8f5f-ef425a32f805",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "mytarget_stats",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
          "    public_control_mytarget_stats = Источник{[Schema=\"public\",Item=\"control_mytarget_stats\"]}[Data],",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(public_control_mytarget_stats,{\"Date\", \"Impressions\", \"Clicks\", \"Cost\", \"Login\", \"CampaignId\", \"adUrl\", \"state\", \"CampaignName\", \"tag\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Другие удаленные столбцы\",{{\"Date\", type date}}),",
          "    #\"Вставленный текст между разделителями\" = Table.AddColumn(#\"Измененный тип\", \"utm_source\", each Text.BetweenDelimiters([adUrl], \"utm_source=\", \"&\"), type text),",
          "    #\"Вставленный текст между разделителями1\" = Table.AddColumn(#\"Вставленный текст между разделителями\", \"utm_medium\", each Text.BetweenDelimiters([adUrl], \"utm_medium=\", \"&\"), type text),",
          "    #\"Вставленный текст между разделителями2\" = Table.AddColumn(#\"Вставленный текст между разделителями1\", \"utm_campaign\", each Text.BetweenDelimiters([adUrl], \"utm_campaign=\", \"&\"), type text),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Вставленный текст между разделителями2\", {\"Date\", \"tag\", \"Login\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Impressions\", each List.Sum([Impressions]), type nullable text}, {\"Clicks\", each List.Sum([Clicks]), type nullable text}, {\"Cost\", each List.Sum([Cost]), type nullable text}})",
          "in",
          "    #\"Сгруппированные строки\""
        ],
        "queryGroup": "1 Обработка статы для связи с метрикой",
        "lineageTag": "9cb38266-8a10-412a-9dab-5ee7e3ba516a",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "ydirect_stats",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
          "    public_control_ydirect_stats = Источник{[Schema=\"public\",Item=\"control_ydirect_stats\"]}[Data],",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(public_control_ydirect_stats,{\"Date\", \"State\", \"CampaignName\", \"CampaignId\", \"Impressions\", \"Clicks\", \"Cost\", \"Login\", \"tag\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Другие удаленные столбцы\",{{\"Date\", type date}, {\"CampaignId\", type text}}),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Измененный тип\", {\"tag\", \"Date\", \"Login\", \"CampaignId\", \"CampaignName\", \"State\"}, {{\"Impressions\", each List.Sum([Impressions]), type nullable number}, {\"Clicks\", each List.Sum([Clicks]), type nullable number}, {\"Cost\", each List.Sum([Cost]), type nullable number}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Сгруппированные строки\", \"utm_source\", each \"yandex\"),",
          "    #\"Добавлен пользовательский объект1\" = Table.AddColumn(#\"Добавлен пользовательский объект\", \"utm_medium\", each \"cpc\"),",
          "    #\"Добавлен пользовательский объект2\" = Table.AddColumn(#\"Добавлен пользовательский объект1\", \"utm_campaign\", each [CampaignId]),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект2\",{{\"State\", \"state\"}}),",
          "    #\"Измененный тип1\" = Table.TransformColumnTypes(#\"Переименованные столбцы\",{{\"utm_source\", type text}, {\"utm_medium\", type text}, {\"utm_campaign\", type text}})",
          "in",
          "    #\"Измененный тип1\""
        ],
        "queryGroup": "1 Обработка статы для связи с метрикой",
        "lineageTag": "a89feaee-c4f6-4693-8966-8e97efa8a27a",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "all_stats",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.Combine({ydirect_stats, vkads_stats, mytarget_stats, google_stats}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Impressions\", Int64.Type}, {\"Clicks\", Int64.Type}, {\"Cost\", type number}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Измененный тип\",\"OFF\",\"не работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"ARCHIVED\",\"не работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"ON\",\"работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"ENABLED\",\"работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"DISABLED\",\"не работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Замененное значение4\",{{\"Date\", \"date\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "1 Обработка статы для связи с метрикой",
        "lineageTag": "c9a2a25f-4b70-47b3-9426-4c33549ecf9b",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "paid_source_names",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WurDowoaLDRc2X9h6sUlJRynMO97RJRjIKMtWitXBJ52fV5KYXZKKTZVvZHyIY5C7awiQnVtZkliUnlpCUB1UxawL+y7svdh0YeuFXRcbwaoiHf1cXCPiXTyDXJ1BKisT81JSK4hWnYJLpbu/v7uPK9Q/6fn56TlAz8QCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [lastsignTrafficSourceName = _t, lastSignSourceEngineName = _t, utm_source = _t]),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"lastsignTrafficSourceName\", type text}, {\"lastSignSourceEngineName\", type text}, {\"utm_source\", type text}})",
          "in",
          "    #\"Измененный тип\""
        ],
        "queryGroup": "4 Получаем главный датасет метрики",
        "lineageTag": "449bd2cd-f05c-4d8b-b685-ac24c15b22f1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "vk_list",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = vkads_stats,",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(Источник,{\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Другие удаленные столбцы\", {\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Количество\", each Table.RowCount(_), Int64.Type}})",
          "in",
          "    #\"Сгруппированные строки\""
        ],
        "queryGroup": "2 Формируем список кампаний",
        "lineageTag": "458e38d8-da18-4ae9-b4d4-c51117eb26fe",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "mt_list",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = mytarget_stats,",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(Источник,{\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Другие удаленные столбцы\", {\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Количество\", each Table.RowCount(_), Int64.Type}})",
          "in",
          "    #\"Сгруппированные строки\""
        ],
        "queryGroup": "2 Формируем список кампаний",
        "lineageTag": "4c2e854b-a6b6-4a47-b555-c75ae2db521c",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_list",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = ydirect_stats,",
          "    #\"Строки с примененным фильтром\" = Table.SelectRows(Источник, each true),",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(#\"Строки с примененным фильтром\",{\"tag\", \"CampaignId\", \"CampaignName\", \"state\", \"utm_source\", \"utm_medium\", \"utm_campaign\"}),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Другие удаленные столбцы\", {\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Количество\", each Table.RowCount(_), Int64.Type}})",
          "in",
          "    #\"Сгруппированные строки\""
        ],
        "queryGroup": "2 Формируем список кампаний",
        "lineageTag": "01fe33ff-7582-414c-bcdf-aa1a0e5f178f",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "all_camps",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.Combine({yd_list, mt_list, vk_list, ga_list}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(Источник,\"OFF\",\"не работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"ARCHIVED\",\"не работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"ON\",\"работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"ENABLED\",\"работает\",Replacer.ReplaceText,{\"state\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"DISABLED\",\"не работает\",Replacer.ReplaceText,{\"state\"})",
          "in",
          "    #\"Замененное значение4\""
        ],
        "queryGroup": "2 Формируем список кампаний",
        "lineageTag": "ca654b05-8552-4d93-9b14-dc70dbd8b795",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "google_stats",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(#\"server\", #\"Dataset\"),",
          "    public_control_mytarget_stats = Источник{[Schema=\"public\",Item=\"control_google_stats\"]}[Data],",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(public_control_mytarget_stats,{\"Date\", \"Impressions\", \"Clicks\", \"Cost\", \"Login\", \"CampaignId\", \"adUrl\", \"state\", \"CampaignName\", \"tag\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Другие удаленные столбцы\",{{\"Date\", type date}}),",
          "    #\"Вставленный текст между разделителями\" = Table.AddColumn(#\"Измененный тип\", \"utm_source\", each Text.BetweenDelimiters([adUrl], \"utm_source=\", \"&\"), type text),",
          "    #\"Вставленный текст между разделителями1\" = Table.AddColumn(#\"Вставленный текст между разделителями\", \"utm_medium\", each Text.BetweenDelimiters([adUrl], \"utm_medium=\", \"&\"), type text),",
          "    #\"Вставленный текст между разделителями2\" = Table.AddColumn(#\"Вставленный текст между разделителями1\", \"utm_campaign\", each Text.BetweenDelimiters([adUrl], \"utm_campaign=\", \"&\"), type text),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Вставленный текст между разделителями2\", {\"Date\", \"tag\", \"Login\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Impressions\", each List.Sum([Impressions]), type nullable text}, {\"Clicks\", each List.Sum([Clicks]), type nullable text}, {\"Cost\", each List.Sum([Cost]), type nullable text}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Сгруппированные строки\",\"\",\"google\",Replacer.ReplaceValue,{\"utm_source\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"\",\"cpc\",Replacer.ReplaceValue,{\"utm_medium\"})",
          "in",
          "    #\"Замененное значение1\""
        ],
        "queryGroup": "1 Обработка статы для связи с метрикой",
        "lineageTag": "b4e92379-6594-4587-b90c-fc315dcb15a8",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "ga_list",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = google_stats,",
          "    #\"Другие удаленные столбцы\" = Table.SelectColumns(Источник,{\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}),",
          "    #\"Сгруппированные строки\" = Table.Group(#\"Другие удаленные столбцы\", {\"tag\", \"utm_source\", \"utm_medium\", \"CampaignId\", \"CampaignName\", \"utm_campaign\", \"state\"}, {{\"Количество\", each Table.RowCount(_), Int64.Type}})",
          "in",
          "    #\"Сгруппированные строки\""
        ],
        "queryGroup": "2 Формируем список кампаний",
        "lineageTag": "51fd86f1-b25d-4258-961e-4498a9df88bb",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Dataset",
        "kind": "m",
        "expression": "\"control_oceanis_riverstart\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "lineageTag": "669e2b48-955e-4089-8496-a231586c8fbf",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "server",
        "kind": "m",
        "expression": "\"powerbi-db.rs-app.ru:3477\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "lineageTag": "5ebca44d-a33b-432e-bd50-d21cccfad0b6",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "2 Формируем список кампаний",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "1 Обработка статы для связи с метрикой",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "5 Расширенные датасеты по источникам",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ]
      },
      {
        "folder": "4 Получаем главный датасет метрики",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      },
      {
        "folder": "3 Обработка ассоциированных конверсий",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.117.984.0 (23.05)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"paid_source_names\",\"metrika_stats\",\"vkads_stats\",\"ydirect_extended\",\"vk_list\",\"mytarget_stats\",\"mt_list\",\"ydirect_stats\",\"google_stats\",\"yd_list\",\"ga_list\",\"all_camps\",\"associate_conv_sources\",\"associate_conv_campaigns\",\"all_stats\",\"_measures\",\"CPA_mode\",\"Dataset\",\"server\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}