{
  "name": "ca8b34f1-1e61-47d2-be0a-d3e9d4c44e5a",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "ru-RU",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "ru-RU",
    "tables": [
      {
        "name": "_camplist",
        "lineageTag": "5d5fb723-cd47-4805-94eb-83577286a9c2",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "CampaignId",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "dataset[CampaignId]",
            "lineageTag": "08931e53-d28d-4b8f-8d33-ac4fdedef904",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Section",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "dataset[Section]",
            "lineageTag": "56797491-40d2-40be-97c4-38a6a3ff6779",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_camplist-d23ec3ca-3b82-46c5-92ab-0eb9ac5eab6b",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY(FILTER('dataset', 'dataset'[SectionType] = \"Тип размещения\"),'dataset'[Section],'dataset'[CampaignId])"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cb8476bbb37546a4850cae804fc1991c"
          }
        ]
      },
      {
        "name": "_crinput",
        "lineageTag": "f3944a80-cc8c-43eb-9def-aeacbba74cb0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "_crsite",
            "dataType": "double",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "lineageTag": "5ba2b40b-de6d-45c9-8fce-84c6b639fb36",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 0
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_crinput-afd90521-9291-40fc-87cb-cf99f69d317a",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(0, 100, 0.01)"
            }
          }
        ],
        "measures": [
          {
            "name": "_crproject",
            "expression": [
              "",
              "SELECTEDVALUE ( '_crinput'[_crsite], 1 )"
            ],
            "lineageTag": "e151816e-bd13-4371-9a90-eb3ef21b5765",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ecf00e7b086947d9aaea3dd6ec10b772"
          }
        ]
      },
      {
        "name": "dataset",
        "lineageTag": "cd4f9dfe-c95d-4506-8a66-ac06ce50e557",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "25442b10-b6d7-420a-a217-47b6c40fe116",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "CampaignType",
            "dataType": "string",
            "sourceColumn": "CampaignType",
            "lineageTag": "5a231bc4-6633-4080-979c-c531d30d1e03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CampaignName",
            "dataType": "string",
            "sourceColumn": "CampaignName",
            "lineageTag": "5b8793cd-5529-4a63-8d81-d2e88969d7be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CampaignId",
            "dataType": "string",
            "sourceColumn": "CampaignId",
            "lineageTag": "4a2624b5-0fce-4c23-898b-8ee45feb863d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Impressions",
            "dataType": "double",
            "sourceColumn": "Impressions",
            "formatString": "0",
            "lineageTag": "4b247104-9620-4705-8407-18b89b0f6be1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Clicks",
            "dataType": "int64",
            "sourceColumn": "Clicks",
            "formatString": "0",
            "lineageTag": "a2fa3cd3-77c2-4c8d-9dbd-940f7ae31843",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Cost",
            "dataType": "double",
            "sourceColumn": "Cost",
            "formatString": "0",
            "lineageTag": "c27b4e0c-89c3-4a62-a9bd-3ef0ef3c4a8d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "AvgImpressionPosition",
            "dataType": "double",
            "sourceColumn": "AvgImpressionPosition",
            "lineageTag": "842768f4-d5af-4287-8ae0-31278a6fbe2a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "BounceRate",
            "dataType": "double",
            "sourceColumn": "BounceRate",
            "lineageTag": "a2b0d24e-621b-4c99-9078-4836d117366c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "SectionId",
            "dataType": "string",
            "sourceColumn": "SectionId",
            "lineageTag": "836801ae-10f1-4be5-b78a-95a9cb48403c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "SectionType",
            "dataType": "string",
            "sourceColumn": "SectionType",
            "sortByColumn": "Index_Type",
            "lineageTag": "7afbc2a8-5cdf-49d0-a817-692e5e310084",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\"]"
              }
            ]
          },
          {
            "name": "Section",
            "dataType": "string",
            "sourceColumn": "Section",
            "lineageTag": "0c863c87-e3da-46ba-98fc-4b0446a19450",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Login",
            "dataType": "string",
            "sourceColumn": "Login",
            "lineageTag": "8ada3c0a-9dc6-420e-9df8-1ee8d8ad930e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Index_Type",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "RELATED(_sort_types[Индекс])",
            "formatString": "0",
            "lineageTag": "87d374f4-d113-427b-a41b-a5120e2fb6db",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "index",
            "dataType": "int64",
            "sourceColumn": "index",
            "formatString": "0",
            "lineageTag": "13a2f445-c8f0-4e71-8643-abdf5cfe5845",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_237815756_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_237815756_LSC",
            "formatString": "0",
            "lineageTag": "42d09b81-2fb1-4446-80f4-1b9a9b048e07",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_237816036_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_237816036_LSC",
            "formatString": "0",
            "lineageTag": "0cfbe57b-9dca-4cd9-ad9d-e5e4895be2d1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_273910512_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_273910512_LSC",
            "formatString": "0",
            "lineageTag": "1625e9b7-e97d-46a3-80e9-71392de2f4e3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_273910641_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_273910641_LSC",
            "formatString": "0",
            "lineageTag": "1badfc1d-d3a6-413d-830a-2c1791341243",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_273935389_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_273935389_LSC",
            "formatString": "0",
            "lineageTag": "0a5d02de-2a4e-47eb-b1d3-ddef16fd2b08",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_54410023_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_54410023_LSC",
            "formatString": "0",
            "lineageTag": "31fa6e39-38e0-4de1-9f0d-ca4ba925e5d5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_354407326_LSC",
            "dataType": "double",
            "sourceColumn": "Conversions_354407326_LSC",
            "lineageTag": "4736d8f4-f0cf-4bef-99cd-fe1eefd41cfb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Conversions_237768449_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_237768449_LSC",
            "formatString": "0",
            "lineageTag": "1699dc2e-b607-4972-8908-370a95d55554",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_237768482_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_237768482_LSC",
            "formatString": "0",
            "lineageTag": "cf8530dc-51da-4567-83eb-828fd5dc3d9e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Conversions_230629666_LSC",
            "dataType": "int64",
            "sourceColumn": "Conversions_230629666_LSC",
            "formatString": "0",
            "lineageTag": "786ab5d2-69a0-420f-887f-e28d31b49c14",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "dataset-19a011c3-25b0-4661-85d8-9640796f9df9",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Table.Combine({yd_optimize_camp_stat, yd_optimize_adform_stat, yd_optimize_adid_stat, yd_optimize_agegen_stat, yd_optimize_clcktype_stat, yd_optimize_criteria_stat, yd_optimize_critype_stat, yd_optimize_device_stat, yd_optimize_group_stat, yd_optimize_hours, yd_optimize_income_stat, yd_optimize_location_stat, yd_optimize_match_stat, yd_optimize_network_stat, yd_optimize_os_stat, yd_optimize_placement_stat, yd_optimize_slot_stat, yd_optimize_tarcat_stat, href, title1, title2, text, callouts, sitelink_title, sitelink_desc, image_url, image_type, graph_res, image_names, display_url, day_of_week, position_in_search, words_with_stop, accounts}),",
                "    #\"Удаленные столбцы\" = Table.RemoveColumns(Источник,{\"CriterionType\"}),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Удаленные столбцы\",{{\"SectionType\", type text}, {\"Section\", type text}}),",
                "    #\"Замененное значение\" = Table.ReplaceValue(#\"Измененный тип\",\"\",\"--\",Replacer.ReplaceValue,{\"Section\"})",
                "in",
                "    #\"Замененное значение\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          }
        ]
      },
      {
        "name": "_goals",
        "lineageTag": "7d7ee850-d723-4b28-a708-83be21ed2ddd",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "20dfe845-1714-4999-9695-b12c8acd46a9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Goal",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(_goals[Value],",
              "1, \"Подписка\",",
              "2, \"Программа обучения клики\",",
              "3, \"Получить запись обучения клики\",",
              "4, \"Купить обучение клики\",",
              "5, \"Открыл форму FIREGUARD4\",",
              "6, \"Открыл форму FENIX3\",",
              "7, \"Открыл форму Firerisks\",",
              "8, \"Открыл форму Fenixserver\",",
              "9, \"[n] YM_Клик по кнопке_Скачать Demo\",",
              "10, \"Лид\")"
            ],
            "lineageTag": "cc339f2c-67cc-4496-9213-4b26c0d5a10f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_goals-7135d0ac-80db-4d5c-9455-edb72bdb3623",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(1,10,1)"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "15b0a40fcf6a4ad0b536af4d07d4906e"
          }
        ]
      },
      {
        "name": "tCPA",
        "lineageTag": "4e8addf9-c995-4128-9aa9-6a670bcbed98",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "tCPA",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]",
            "formatString": "0",
            "lineageTag": "72022ad8-1c74-49ca-aea5-025603756834",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 0
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "tCPA-ed249754-c083-463f-8f7c-bfcf5a6dc99f",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GENERATESERIES(0, 100000, 10)"
            }
          }
        ],
        "measures": [
          {
            "name": "Значение tCPA",
            "expression": [
              "",
              "SELECTEDVALUE ( 'tCPA'[tCPA], 1000 )"
            ],
            "formatString": "0",
            "lineageTag": "a03c4006-50ee-4ae9-a692-738657318f41"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7b9b98c0110c4fc8bf0b77f1a37cc0bc"
          }
        ]
      },
      {
        "name": "_measures",
        "lineageTag": "6a3dde30-787b-4755-9895-cecabea4801c",
        "columns": [
          {
            "name": "measure",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "measure",
            "formatString": "0",
            "lineageTag": "fb78816d-7ad4-4616-8e5f-30e33c8eebc9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_measures-a94fb2f6-b72a-46d5-a06c-0661965fa075",
            "mode": "import",
            "queryGroup": "Datasets\\service",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [measure = _t]),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"measure\", Int64.Type}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "BR",
            "expression": [
              "",
              "AVERAGE ( 'dataset'[BounceRate] )"
            ],
            "formatString": "0",
            "lineageTag": "e35987d4-80d9-42d4-b8fa-a6daf37122fb",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "CONV",
            "expression": [
              "",
              "VAR __SelectedGoals = ALLSELECTED ( _goals[Goal] )",
              "/// перечислите меры в соответствии с шаблоном",
              "/// VAR __goalN = IF (\"название конверсии\" IN __SelectedGoals, SUM( 'dataset'[Conversions_XXXXXXXXX_LSC] ))",
              "",
              "VAR __goal1 = IF (\"Подписка\" IN __SelectedGoals,SUM ( 'dataset'[Conversions_237816036_LSC] ))",
              "VAR __goal2 = IF (\"Программа обучения клики\" IN __SelectedGoals,SUM ( 'dataset'[Conversions_273910512_LSC] ))",
              "VAR __goal3 = IF (\"Получить запись обучения клики\" IN __SelectedGoals,SUM ( 'dataset'[Conversions_273910641_LSC] ))",
              "VAR __goal4 = IF (\"Купить обучение клики\" IN __SelectedGoals,SUM ( 'dataset'[Conversions_273935389_LSC] ))",
              "VAR __goal5 = IF (\"Открыл форму FIREGUARD4\" IN __SelectedGoals, SUM( 'dataset'[Conversions_54410023_LSC] ))",
              "VAR __goal6 = IF (\"Открыл форму FENIX3\" IN __SelectedGoals, SUM( 'dataset'[Conversions_354407326_LSC] ))",
              "VAR __goal7 = IF (\"Открыл форму Firerisks\" IN __SelectedGoals, SUM( 'dataset'[Conversions_237768449_LSC] ))",
              "VAR __goal8 = IF (\"Открыл форму Fenixserver\" IN __SelectedGoals, SUM( 'dataset'[Conversions_237768482_LSC] ))",
              "VAR __goal9 = IF (\"[n] YM_Клик по кнопке_Скачать Demo\" IN __SelectedGoals, SUM( 'dataset'[Conversions_230629666_LSC] ))",
              "VAR __goal10 = IF (\"Лид\" IN __SelectedGoals, SUM( 'dataset'[Conversions_237815756_LSC] ))",
              "",
              "RETURN",
              "// Добавьте вывод конверсии плюсанув к выражению:",
              "__goal1 + __goal2 + __goal3 + __goal4 + __goal5 + __goal6 + __goal7 + __goal8 + __goal9 + __goal10"
            ],
            "formatString": "0",
            "lineageTag": "d841f3d5-ca3d-4e5f-8d9e-5d115e2c72d5"
          },
          {
            "name": "COST_VAT",
            "expression": [
              "",
              "SUM ( 'dataset'[Cost] ) * 1.2"
            ],
            "formatString": "0",
            "lineageTag": "56c0933b-fc30-4bae-b147-5618ad826f35",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "CPA",
            "expression": [
              "",
              "VAR _mode = ALLSELECTED(_firstconv[first conversion])",
              "VAR _a = DIVIDE ( [COST_VAT], [CONV] )",
              "VAR _b = IF([CONV] > 0, DIVIDE([COST_VAT],[CONV]), [COST_VAT] + [CPC])",
              "VAR _res = IF(\"Отобразить\" in _mode, _b, _a)",
              "",
              "RETURN",
              "_res",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3b4d61c1-ba6d-4a13-9041-c8e02b1eebcf",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "CPC",
            "expression": [
              "",
              "DIVIDE ( [COST_VAT], SUM ( 'dataset'[Clicks] ) )"
            ],
            "formatString": "0",
            "lineageTag": "197d8b8b-348f-4c8f-88f2-78f23aeaf306",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "CR",
            "expression": [
              "",
              "DIVIDE ( [CONV], SUM ( 'dataset'[Clicks] ) )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4d7287d3-4f8e-41c3-b64f-6d239c9e055c",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "CTR",
            "expression": [
              "",
              "DIVIDE ( SUM ( 'dataset'[Clicks] ), SUM ( 'dataset'[Impressions] ) ) * 100"
            ],
            "formatString": "0.00",
            "lineageTag": "656db40f-cfb6-44bc-8a7d-89e53418362f",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "NEW_CORR",
            "expression": [
              "",
              "var cpa = IF([CONV] = 0, [COST_VAT] + [CPC], [CPA])",
              "var res = DIVIDE(tCPA[Значение tCPA], cpa) - 1",
              "var show = IF(res > 1, 1, res)",
              "VAR clck =",
              "    IF (",
              "        SUM ( 'dataset'[Cost] ) < SUM ( tCPA[tCPA] ),",
              "        IF ( [CONV] > 2, show, BLANK () ),",
              "        show",
              "    )",
              "RETURN",
              "    clck"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2aa99a59-a1e7-4d57-9131-30da9697c610",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "POT %",
            "expression": [
              "",
              "var Conv = DIVIDE([CONV],CALCULATE([CONV],ALLSELECTED('dataset'), REMOVEFILTERS('dataset'[Section])))",
              "var Cost = DIVIDE([COST_VAT],CALCULATE([COST_VAT],ALLSELECTED('dataset'), REMOVEFILTERS('dataset'[Section])))",
              "var res = DIVIDE(Conv,Cost,0)-1",
              "VAR clck =",
              "    IF (",
              "        SUM ( 'dataset'[Cost] ) < SUM ( tCPA[tCPA] ),",
              "        IF ( [CONV] > 2, res, BLANK () ),",
              "        res",
              "    )",
              "RETURN",
              "    clck"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c557912f-5e54-4862-9aa9-640d495e0d4b",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "IMPR",
            "expression": "SUM('dataset'[Impressions])",
            "formatString": "0",
            "lineageTag": "46af6b68-f024-460b-a2d8-3b3067446474"
          },
          {
            "name": "CLICK",
            "expression": "SUM('dataset'[Clicks])",
            "formatString": "0",
            "lineageTag": "235b46b8-9189-403b-bb2b-df683b487b63"
          },
          {
            "name": "YTD BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\BR",
            "lineageTag": "b944ec35-ded2-45f2-881b-eb32f8e2358d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\BR",
            "lineageTag": "cfeec337-dacb-4941-a6b2-e0a4af623ef2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\BR",
            "lineageTag": "5172990c-9625-40ee-8f7a-d6f3d2365886",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "b0929bcd-2b84-4551-b84d-c3e47fd84b4a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [BR]",
              "VAR __ValuePreviousPeriod = [PY BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "2b7b5035-abaf-4beb-9db6-e726060cf93f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY BR],",
              "    [PY BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "3160763a-4f87-444d-9d9b-6b3734736057",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "bbd2b685-567c-40b0-92d6-f4f906524461",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [BR]",
              "VAR __ValuePreviousPeriod = [PQ BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "d9d7b762-c26e-460b-8bf8-5eff667ef540",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ BR],",
              "    [PQ BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "25179dcc-5d00-45ce-99e3-12a424e78b83",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD BR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "c83f658c-bfa5-4ec8-8339-0ddd5f7807f1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD BR]",
              "VAR __ValuePreviousPeriod = [PYTD BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "3a8e09af-208a-4ba5-b084-f4f0c76a360f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD BR],",
              "    [PYTD BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "f7f1e3b7-d1b9-427d-b233-19026176eb60",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD BR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "89e57f3d-c5ab-48cb-b283-871bb7727a48",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD BR]",
              "VAR __ValuePreviousPeriod = [PQTD BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "d19afd8e-90f4-4683-bf01-ad5cb982053c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD BR],",
              "    [PQTD BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "bad0f4ba-f9eb-4524-b3a8-f3570609d47b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "2995d76d-d07f-4ad5-a421-6725e854787c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD BR]",
              "VAR __ValuePreviousPeriod = [PYC BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "3aeb2fbb-b431-4ec9-860e-4b335cb1458b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "d5a3bccb-2767-425f-b430-3b6955a10196",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD BR]",
              "VAR __ValuePreviousPeriod = [PQC BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "1ecc0e6b-86f6-47bf-a642-7baa8973eb3c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CONV",
            "lineageTag": "85009991-26be-438a-b036-55df4735b762",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CONV",
            "lineageTag": "4dbfc6ed-241a-450b-b177-e5620fd3e1ab",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CONV",
            "lineageTag": "5c3d7f09-03d8-4a6d-9a2c-c268ceab3b96",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "46f4204a-8ce4-40b9-828e-4150dd50409d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CONV]",
              "VAR __ValuePreviousPeriod = [PY CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "78a4ddae-f981-4247-bc99-a8801dced095",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY CONV],",
              "    [PY CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "6e280105-3027-456d-8bee-43f23b3a5e06",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "f5650493-f5c0-4341-b454-e7a58d2b6351",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CONV]",
              "VAR __ValuePreviousPeriod = [PQ CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "54b21b4a-75ce-4fb2-b556-a0b22f7e850e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ CONV],",
              "    [PQ CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "31ab88f1-936e-4f13-9c70-3e33c4b8c370",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD CONV],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "127f0a07-fd4b-40eb-9792-bc422ac2d47b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CONV]",
              "VAR __ValuePreviousPeriod = [PYTD CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "a17dda3e-3481-4dc7-a59c-108f23eaf62f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD CONV],",
              "    [PYTD CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "532a3554-807e-40e2-928d-40b4dc2e80ab",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD CONV],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "034afa5b-818c-4063-a684-8b2d76ab0e37",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CONV]",
              "VAR __ValuePreviousPeriod = [PQTD CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "0ab078c5-a371-4197-9653-c062f945c37d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD CONV],",
              "    [PQTD CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "6c31ceaa-52ba-4e4b-9276-20039621509c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "f6fb3a93-c4c6-41da-b7cd-b4bbacc23103",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CONV]",
              "VAR __ValuePreviousPeriod = [PYC CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "667c86a4-84ee-43e1-888e-7d04cf2a2373",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "1df2b56d-2c90-47b1-ba15-7a9c26eb59fa",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CONV]",
              "VAR __ValuePreviousPeriod = [PQC CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "74e4b182-2507-47fa-a328-0b3f88f06e50",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\COST_VAT",
            "lineageTag": "42585ec8-be1c-4582-a2cc-4d13666143f7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\COST_VAT",
            "lineageTag": "14a128d9-5d2b-4507-a886-0abc1ff8a9c9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\COST_VAT",
            "lineageTag": "f5622afd-544b-48cd-8e89-c2f4154e6e81",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "b47b907e-fa2d-4408-a3f6-31624acdb786",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [COST_VAT]",
              "VAR __ValuePreviousPeriod = [PY COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "20f6a115-979b-4e59-916b-b39e86d30ba0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY COST_VAT],",
              "    [PY COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "7c58b33b-ce07-45e3-9717-538f1fba0e40",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "61b16119-cd1c-4ca3-9b55-cae7470ce9b4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [COST_VAT]",
              "VAR __ValuePreviousPeriod = [PQ COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "fa85f53f-ad56-46cb-96e8-3520eaca5159",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ COST_VAT],",
              "    [PQ COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "46b6c8ca-a9ed-4d10-9d7e-ef9b6bc4f072",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD COST_VAT],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "135ccf9f-518f-4140-8ff9-72a40a5f4940",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD COST_VAT]",
              "VAR __ValuePreviousPeriod = [PYTD COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "0bd4faa2-d4f2-4897-a41f-cffde1a91296",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD COST_VAT],",
              "    [PYTD COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "7d30920d-7d1b-451e-80b5-3d01db9b5575",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD COST_VAT],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "d78b79c4-56a8-46f6-9f52-53817cb4d9a5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD COST_VAT]",
              "VAR __ValuePreviousPeriod = [PQTD COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "abc74129-919a-472b-9ac5-9710e921a1ac",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD COST_VAT],",
              "    [PQTD COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "416567e9-c6c0-43cf-acbd-73d6757d4b4c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "18964da5-f3ba-4b77-84f4-e92844ae4746",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD COST_VAT]",
              "VAR __ValuePreviousPeriod = [PYC COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "c9761388-0745-4789-a7b2-b25fef8916c3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "a71bf747-eca7-4913-ac9b-cf6f12366174",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD COST_VAT]",
              "VAR __ValuePreviousPeriod = [PQC COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "cd1329d5-74fd-442d-ac05-132ef5d99402",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CPA",
            "lineageTag": "2444bfaa-119a-4a0f-965a-d0aed6cc6f10",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CPA",
            "lineageTag": "d4ce3898-c664-4510-bd3a-ac2182b22dac",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CPA",
            "lineageTag": "33bdf0cf-91e4-4d31-ba5b-654ce5648bae",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "8edd42be-7c24-4baa-adab-c7474791019f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CPA]",
              "VAR __ValuePreviousPeriod = [PY CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "05d1fd18-3458-4677-a07e-88bb62359c0f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY CPA],",
              "    [PY CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "3daf1b02-290f-456f-8a56-86f8d62567ec",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "943a10d8-8580-4e27-870c-a7b1b2fe24d6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CPA]",
              "VAR __ValuePreviousPeriod = [PQ CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "400953e5-7bb8-4ed9-bbc6-d2278a40f237",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ CPA],",
              "    [PQ CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "f2c5e03b-55be-4ddb-b410-ba9caef6d558",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD CPA],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "002849ba-2c38-4171-8727-9bb1f8f0b527",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CPA]",
              "VAR __ValuePreviousPeriod = [PYTD CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "79f7ba7e-6c1b-446f-91c8-7d306a2677de",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD CPA],",
              "    [PYTD CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "b791ea28-230d-4011-9e83-09bb9d4a865e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD CPA],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "4465b190-f011-42c6-952e-7f77ba1ab0b0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CPA]",
              "VAR __ValuePreviousPeriod = [PQTD CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "cff51c18-aeb6-4694-960b-4e44044ae574",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD CPA],",
              "    [PQTD CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "cfe47739-6359-4786-8c01-48a6d87dd66b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "1795deec-c34e-4492-a8ef-b29a531f133b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CPA]",
              "VAR __ValuePreviousPeriod = [PYC CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "6935eae5-3074-427b-9922-a1cc7a05a52f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "626e6733-9836-4633-82da-3d7baa8aaf24",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CPA]",
              "VAR __ValuePreviousPeriod = [PQC CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "ca0a65e0-e34e-42a7-9d56-8ed130e48fa7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CPC",
            "lineageTag": "4ece8f13-4f6b-4ebc-a4e7-7fc0444929f3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CPC",
            "lineageTag": "e67d0509-e0be-4d11-a0c7-56239a88d5bf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CPC",
            "lineageTag": "ab7f7c96-7848-4759-bc60-c291232f2dc3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "aa6f31d5-897d-4dcd-a9f7-e5283a0573e2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CPC]",
              "VAR __ValuePreviousPeriod = [PY CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "00d714e0-6ddc-4331-a61f-dbae1171990f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY CPC],",
              "    [PY CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "0029ead6-e46b-49df-bd3f-345bf4c3a3e7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "fcc49443-115b-4ff8-924a-120d47df41d4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CPC]",
              "VAR __ValuePreviousPeriod = [PQ CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "3c7734e0-4eb2-42bf-81de-eafaba225ab8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ CPC],",
              "    [PQ CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "789cdcbf-b16c-40ee-a17b-c89798443d86",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD CPC],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "5ab07090-a9e7-4510-b964-d24c5fa71e93",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CPC]",
              "VAR __ValuePreviousPeriod = [PYTD CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "7350f367-4888-4b53-8ca8-142c71db3536",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD CPC],",
              "    [PYTD CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "056e68d0-d477-4157-90d8-d21752e8cfd8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD CPC],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "79a13881-f0e4-44a8-9a7a-c3034a772602",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CPC]",
              "VAR __ValuePreviousPeriod = [PQTD CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "eb54d801-306f-4181-80ee-ac23dda86a73",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD CPC],",
              "    [PQTD CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "09258674-a28e-477d-bd6c-5e0d0649f634",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "fcc7dc34-38e6-4d9d-92c3-7ebdba4eb158",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CPC]",
              "VAR __ValuePreviousPeriod = [PYC CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "d5a50e1d-2bdd-4b9e-9d70-4debff34c591",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "af6000e3-4f13-44b5-b9df-7d18bf779b3e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CPC]",
              "VAR __ValuePreviousPeriod = [PQC CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "17784937-7b82-4cf0-b545-981aba2238fd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date total\\CR",
            "lineageTag": "f1cf54f1-d6ac-4231-8adf-cb4637113ef3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date total\\CR",
            "lineageTag": "bdb245d7-b1d3-44ea-ac79-3c4e9806cba1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date total\\CR",
            "lineageTag": "a92df4bf-3370-4157-be11-f8db9f2b0d9f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "70e1437a-c466-4089-825d-eedef310b37e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CR]",
              "VAR __ValuePreviousPeriod = [PY CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "7a959b68-28f6-4287-8c1d-e2fe9721bb38",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY CR],",
              "    [PY CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "d379bb34-2fd4-49f3-a385-53ac9d679dc2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "33d248f6-fac0-4a48-9d77-8e1c7fcdd752",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CR]",
              "VAR __ValuePreviousPeriod = [PQ CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "4c7d6e46-48e0-43f9-832c-56130309b198",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ CR],",
              "    [PQ CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "c8ad5ec4-8ab0-4676-9b79-53b7ae718fdc",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD CR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "82bb8ac7-03f0-4ce2-9250-deab758963f1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CR]",
              "VAR __ValuePreviousPeriod = [PYTD CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "0f7a9aed-5cf9-4e1f-b288-aa35b10761d8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD CR],",
              "    [PYTD CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "9dc6dd2e-ec76-4417-abed-4710034aed2c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD CR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "f3483bd7-3873-47bd-8579-01bc0e4b4800",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CR]",
              "VAR __ValuePreviousPeriod = [PQTD CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "c023c910-152f-4ce0-bcd4-b94ed23880a7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD CR],",
              "    [PQTD CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "15aee124-8f95-4114-a1df-44e1aa77a2c5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "91067354-39c8-4c7c-89d1-a2743de74460",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CR]",
              "VAR __ValuePreviousPeriod = [PYC CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "bb847782-6aca-46c2-8116-35fbdb70edf7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "79ef0a83-c74c-4c5e-b0da-447d2c32b28d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CR]",
              "VAR __ValuePreviousPeriod = [PQC CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "27c0bd91-b353-4969-a8aa-35a3eff385c7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date total\\CTR",
            "lineageTag": "4b42a382-facf-4417-9be5-143048924053",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date total\\CTR",
            "lineageTag": "5b206e62-4813-4988-ad48-4e5288d612de",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date total\\CTR",
            "lineageTag": "cbcac884-25db-486d-bd6f-3ca05e5581ac",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "ec7778dd-0eff-4243-a550-c0525813dcc8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CTR]",
              "VAR __ValuePreviousPeriod = [PY CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "70187bdb-9d54-477e-a6cf-645c510b728e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY CTR],",
              "    [PY CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "aa5fb51c-948a-4cad-9439-487cea9c8851",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "069d0cff-10ed-4358-9b2b-46d9bd1e8e0c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CTR]",
              "VAR __ValuePreviousPeriod = [PQ CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "7efa2fb0-6b24-4a05-8c67-d783f3e13320",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ CTR],",
              "    [PQ CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "37789e6f-a0b3-49ee-ac09-7a27d1218426",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD CTR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "09187f54-1546-4cca-bdf4-af210f4b9fb7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CTR]",
              "VAR __ValuePreviousPeriod = [PYTD CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "3f4c4649-3da7-4fff-bbbc-0187a038a1e7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD CTR],",
              "    [PYTD CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "a90c03df-8e26-4cc1-a4c3-fc69403a33ae",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD CTR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "1d49572e-f409-4af7-9067-2ff930dd8578",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CTR]",
              "VAR __ValuePreviousPeriod = [PQTD CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "f0dca8af-867c-4df0-acca-fefafb4b6c2d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD CTR],",
              "    [PQTD CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "2774219e-fdf2-4f75-bf87-7b582458d2a3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "9a1e9e6d-91c7-4551-a23d-836b1e6d5778",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CTR]",
              "VAR __ValuePreviousPeriod = [PYC CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "bd6e88cb-8d37-4f72-a681-fd34df520213",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "dfd1e147-e897-49db-beff-085495ff3bdf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CTR]",
              "VAR __ValuePreviousPeriod = [PQC CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "3452bec3-49b5-4fcf-9088-3eecf8db8384",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\IMPR",
            "lineageTag": "7bcc1605-d4c6-4614-bd1d-18879ced38cb",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\IMPR",
            "lineageTag": "29c39d81-1183-44f4-bee9-339df7942c24",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\IMPR",
            "lineageTag": "f146c707-fff5-44f1-9c44-2cfd1f4a2cf2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "a6e04cd8-c991-4162-b8bf-d4493f17fddd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [IMPR]",
              "VAR __ValuePreviousPeriod = [PY IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "2d77f5c0-3f10-42b5-836f-b8c8169d333f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY IMPR],",
              "    [PY IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "2461e7d7-6681-4e8e-a41a-6b98b67b684d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "c5335977-592d-42e9-acf6-1171989ab619",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [IMPR]",
              "VAR __ValuePreviousPeriod = [PQ IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "6b3405c7-5e7d-4b62-b674-37c1a1155f51",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ IMPR],",
              "    [PQ IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "96bd790e-bc8e-4f47-8ad0-1cc3c58242a5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD IMPR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "a3f3f96b-bbd8-4ade-a5c2-c94e2dd8e09c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD IMPR]",
              "VAR __ValuePreviousPeriod = [PYTD IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "cb2a244d-c19f-4226-908f-3f550d025f72",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD IMPR],",
              "    [PYTD IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "b6ead1e3-7a37-4f93-a31c-7a34597e18b0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD IMPR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "3b41ae35-85fa-4cbb-a7af-9d3bd6703c31",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD IMPR]",
              "VAR __ValuePreviousPeriod = [PQTD IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "1ba96775-0b7d-45d1-bc3e-bb551f380b09",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD IMPR],",
              "    [PQTD IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "3c9aa956-9620-42e2-8db4-e31f886b8e1d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "f598d49e-0ae6-4841-a2f7-5285223584e4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD IMPR]",
              "VAR __ValuePreviousPeriod = [PYC IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "62b40300-86c6-48d4-9a89-544b305c0cbd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "1e79e0c6-f347-4fe7-ad1c-78e5fa445519",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD IMPR]",
              "VAR __ValuePreviousPeriod = [PQC IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "59b91af4-a9e4-4ed1-a413-cb27a37d18c3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTD CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CLICK",
            "lineageTag": "4883af18-b2e2-4e39-8cba-c319a6688e47",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTD CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        DATESQTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CLICK",
            "lineageTag": "66ee9c78-b0ea-453a-96b0-d7432ffde526",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTD CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        DATESMTD ( 'Date'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date total\\CLICK",
            "lineageTag": "31dd61c9-e17a-4b74-8955-ca8195000b23",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PY CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "fedadcba-749f-4741-80e7-942d26ea969a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CLICK]",
              "VAR __ValuePreviousPeriod = [PY CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "83a88b87-8330-4222-ad09-030d48416215",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOY % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOY CLICK],",
              "    [PY CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "b81c2392-4bd3-450b-bf04-220819855dc0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQ CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "0a6248fe-8d18-4cf5-b83c-c386902f627a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CLICK]",
              "VAR __ValuePreviousPeriod = [PQ CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "a4f65cc7-cc5a-4c90-bd5f-830660ef07d8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQ % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQ CLICK],",
              "    [PQ CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "d5ed79f1-b81a-4ff1-b306-e3cd5680136f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYTD CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [YTD CLICK],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, YEAR ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "7312d350-dde8-439d-bae3-17ace68a92d9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CLICK]",
              "VAR __ValuePreviousPeriod = [PYTD CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "9fc33d59-2e1a-4250-ba41-606d0179122d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YOYTD % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YOYTD CLICK],",
              "    [PYTD CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "e1ba712e-3643-48ab-a1b5-4b26f44be93c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQTD CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [QTD CLICK],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, QUARTER ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "09ddf110-1333-468f-b93b-fa2fb9295e4a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CLICK]",
              "VAR __ValuePreviousPeriod = [PQTD CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "c220213b-7441-457e-aeba-52225f6ffc1e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QOQTD % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QOQTD CLICK],",
              "    [PQTD CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "1cd9014b-d7e9-4ec9-8d0d-b00cb9bd9372",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYC CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "6daef620-bcaa-40ff-985d-2643aa18710f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YTDOPY CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [YTD CLICK]",
              "VAR __ValuePreviousPeriod = [PYC CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "9b25d7fa-ac36-49bd-bbb0-929ac7b9f815",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PQC CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, QUARTER )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "ec53cc1d-381a-4c66-908b-2cf1693d798e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QTDOPQ CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [QTD CLICK]",
              "VAR __ValuePreviousPeriod = [PQC CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "a30fe57d-1de5-4270-8db7-a13c51e7b7b1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "7486502a-f525-4cd3-971f-883a56706d96",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [BR]",
              "VAR __ValuePreviousPeriod = [PM BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "5c533435-dc95-468e-b67c-1c9f5bd6f9ae",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM BR],",
              "    [PM BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\BR",
            "lineageTag": "47153ea7-dc25-45f5-bd08-27fe474d779a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD BR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "2aaa618a-3236-493e-8bdb-06ea797abbc7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD BR]",
              "VAR __ValuePreviousPeriod = [PMTD BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "61f27abe-b4a0-45d2-9945-ac5760cbce1c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD BR],",
              "    [PMTD BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\BR",
            "lineageTag": "6e17deca-519a-4cc8-8817-470b57eb4db6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY BR],",
              "    [PYC BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "1d2e08ff-f4ee-4873-8748-524fac39026a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ BR],",
              "    [PQC BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "d49b2747-4d75-4678-8ef4-3b84ffee4f69",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "07c52a02-f6de-4f11-a730-52bd8f45b3a0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD BR]",
              "VAR __ValuePreviousPeriod = [PMC BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "092d3e81-95af-420c-bde2-6c49f56eca98",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM BR],",
              "    [PMC BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\BR",
            "lineageTag": "0826dad0-4574-471e-b17a-344c58ff07bb",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [BR],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\BR",
            "lineageTag": "9b6208b1-86c8-40cc-83fd-fee560347cf9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT BR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT BR],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\BR",
            "lineageTag": "78ed2a89-c00d-40a5-bcd4-1b25d5f4c007",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG BR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT BR]",
              "VAR __ValuePreviousPeriod = [PYMAT BR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\BR",
            "lineageTag": "6842cf79-ba0d-41d8-a8ed-b6e4810d1077",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % BR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG BR],",
              "    [PYMAT BR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\BR",
            "lineageTag": "cb66a684-3118-468c-8fb6-d40eae88fd09",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "d4615a22-5bec-4a31-818f-b187dcf9bb62",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CONV]",
              "VAR __ValuePreviousPeriod = [PM CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "347af886-3cb2-484a-83b8-05267cf221e3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM CONV],",
              "    [PM CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CONV",
            "lineageTag": "47d290de-17bf-4f8e-8d97-ec0a78ee3607",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD CONV],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "a46fc2a0-4782-4483-bebd-92a4064f1e5c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CONV]",
              "VAR __ValuePreviousPeriod = [PMTD CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "26262b62-33b4-48f4-a2af-46e04d9fb9d9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD CONV],",
              "    [PMTD CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CONV",
            "lineageTag": "012aeebe-9d22-4939-8bb5-a55179afa6c1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY CONV],",
              "    [PYC CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "f4622416-e3b9-48a6-a44b-3bbaf710c3b9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ CONV],",
              "    [PQC CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "03bf786a-785c-49ab-aea8-bdd39a0373d6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "22116fcb-1f75-4dc8-a242-5ee75f540d62",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CONV]",
              "VAR __ValuePreviousPeriod = [PMC CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "186c8993-473c-465a-9494-b8ec1a9b87c4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM CONV],",
              "    [PMC CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CONV",
            "lineageTag": "8c664285-0e5e-4183-9cc3-b8a491bf9117",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CONV],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CONV",
            "lineageTag": "85dff8e8-6031-4273-828c-8059c349187a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT CONV",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT CONV],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CONV",
            "lineageTag": "c8329d3d-dd6e-41a9-b541-ccb6ceaaaa2b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG CONV",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT CONV]",
              "VAR __ValuePreviousPeriod = [PYMAT CONV]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CONV",
            "lineageTag": "3af908bf-1aa4-4e8f-b780-22fcbb5b0599",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % CONV",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG CONV],",
              "    [PYMAT CONV]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CONV",
            "lineageTag": "4f541323-0036-4f34-9828-10bb721ab176",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "1a62e333-82c2-4bc6-9b00-2d5ea347ae7e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [COST_VAT]",
              "VAR __ValuePreviousPeriod = [PM COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "f05838a4-dd29-4281-ad02-9db19c73fe10",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM COST_VAT],",
              "    [PM COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\COST_VAT",
            "lineageTag": "51dcfacb-f37d-4545-8e0b-2f7598a27e06",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD COST_VAT],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "97b4030e-1bd9-409b-97d3-13769859e0d7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD COST_VAT]",
              "VAR __ValuePreviousPeriod = [PMTD COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "7caee5e4-0f4a-4a8c-af9e-099ecc9cc02e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD COST_VAT],",
              "    [PMTD COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\COST_VAT",
            "lineageTag": "830bce81-c0a6-4272-ba6a-05176cb0dbc1",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY COST_VAT],",
              "    [PYC COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "6b6dac35-da69-43e2-b5a1-4e96552bc538",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ COST_VAT],",
              "    [PQC COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "ee85eed2-b961-40d7-b8e0-5a5983d9fe55",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "1e211a89-f41a-4dbb-bc0e-41355c79c8bf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD COST_VAT]",
              "VAR __ValuePreviousPeriod = [PMC COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "97cf0bea-f452-48cd-9c57-4bbe1e9ed311",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM COST_VAT],",
              "    [PMC COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\COST_VAT",
            "lineageTag": "742807a0-1d34-44d0-ba12-a9b67f7a984f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [COST_VAT],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\COST_VAT",
            "lineageTag": "c82c30ce-7e22-4cd3-a641-adef2ef9b18a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT COST_VAT",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT COST_VAT],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\COST_VAT",
            "lineageTag": "15c5e4f6-59fd-4cd4-b587-f8d98fb1d7bd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG COST_VAT",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT COST_VAT]",
              "VAR __ValuePreviousPeriod = [PYMAT COST_VAT]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\COST_VAT",
            "lineageTag": "f9f627f4-cb41-4c1b-a93a-01a1b4653449",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % COST_VAT",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG COST_VAT],",
              "    [PYMAT COST_VAT]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\COST_VAT",
            "lineageTag": "16a82008-90d0-4c68-85ca-1e32f473fce0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "6e0a059a-996b-4cc2-b603-8c3d77d1f872",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CPA]",
              "VAR __ValuePreviousPeriod = [PM CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "ac5e877e-6331-4e98-bf43-6ba6fcd12c49",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM CPA],",
              "    [PM CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CPA",
            "lineageTag": "31392561-9c52-4aee-bee6-fb7437cc2fcc",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD CPA],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "eacf340b-bd88-47fd-84d0-6ed8a1f68fe6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CPA]",
              "VAR __ValuePreviousPeriod = [PMTD CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "753cc67d-29ca-4c8e-a5b5-3bc5ec03ed1e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD CPA],",
              "    [PMTD CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CPA",
            "lineageTag": "b3273313-357d-47ce-87f0-42d8e5555e3a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY CPA],",
              "    [PYC CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "e2d9d160-ebca-47b9-b376-19a7e78cb533",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ CPA],",
              "    [PQC CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "0395cb35-9f0e-4c0d-bd8a-88f5eb3acd33",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "29bb928c-956b-4a3e-baf0-0192eb839873",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CPA]",
              "VAR __ValuePreviousPeriod = [PMC CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "53dd0fa6-7dbc-4d54-aec2-b605395419b5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM CPA],",
              "    [PMC CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CPA",
            "lineageTag": "346df7ea-4387-4fb7-9ba3-0df7b54e1c60",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPA],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPA",
            "lineageTag": "6d8229f4-9218-4f76-a170-0bf04eca2a06",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT CPA",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT CPA],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPA",
            "lineageTag": "4a902216-0744-4590-8886-bf8d2172accc",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG CPA",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT CPA]",
              "VAR __ValuePreviousPeriod = [PYMAT CPA]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPA",
            "lineageTag": "3bddc7b5-61b5-41c0-8042-22bcb61d71a7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % CPA",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG CPA],",
              "    [PYMAT CPA]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPA",
            "lineageTag": "e6f02112-55c6-40d7-9af1-b6f22f6a99c9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "d9201712-42d0-46ff-8fff-ec8a4f96542f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CPC]",
              "VAR __ValuePreviousPeriod = [PM CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "6510dbd3-2335-4c50-a0c2-6b07d0b0d087",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM CPC],",
              "    [PM CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CPC",
            "lineageTag": "a7876e74-d000-432e-b6c6-cb48d25ec680",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD CPC],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "7bb9d645-6b93-4bf2-8ba6-fee36001a4c2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CPC]",
              "VAR __ValuePreviousPeriod = [PMTD CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "9bf7d070-fc12-4205-a802-0d467f198823",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD CPC],",
              "    [PMTD CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CPC",
            "lineageTag": "85276d4e-9172-4b2d-80c4-2ffbe0e464bd",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY CPC],",
              "    [PYC CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "9309cc3c-cc64-41bb-aca5-83b6605614a4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ CPC],",
              "    [PQC CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "7c947b9a-2721-4c46-92c6-c9eaa5a73d59",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "8b5ffe71-7ebd-44ed-937c-beba17be012b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CPC]",
              "VAR __ValuePreviousPeriod = [PMC CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "c16b89c0-d1a3-45e8-8643-4579beb5b861",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM CPC],",
              "    [PMC CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CPC",
            "lineageTag": "9195fb5c-0692-44eb-898f-080453185e3f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CPC],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPC",
            "lineageTag": "5ff02a8d-fa15-41af-9985-4282d79915bb",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT CPC",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT CPC],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPC",
            "lineageTag": "880545f4-95b9-4a27-8385-88924dcef48b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG CPC",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT CPC]",
              "VAR __ValuePreviousPeriod = [PYMAT CPC]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPC",
            "lineageTag": "a57820c7-f146-4770-9c04-9a72e11ca197",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % CPC",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG CPC],",
              "    [PYMAT CPC]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CPC",
            "lineageTag": "69e05589-b7df-4085-9d79-1f613b7bac27",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "efa7b45c-7d34-4faa-b36b-8149d642bd49",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CR]",
              "VAR __ValuePreviousPeriod = [PM CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "974084d4-8049-41dd-bc38-6a82d6f13c9f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM CR],",
              "    [PM CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CR",
            "lineageTag": "f13cd282-2d20-4cd2-9ac4-d696c68c5394",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD CR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "dfbb1966-b798-45ba-9ecc-7fb384eb6321",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CR]",
              "VAR __ValuePreviousPeriod = [PMTD CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "19eaf5fc-b3cc-46db-bf69-a3cb26ca0c87",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD CR],",
              "    [PMTD CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CR",
            "lineageTag": "99d0ee6e-f2b4-448b-8b94-7d12a14e44aa",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY CR],",
              "    [PYC CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "9f6e996b-f653-4d79-a40a-d2532688e28b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ CR],",
              "    [PQC CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "1b01ceb8-0672-4241-b0ad-2fcd63f09641",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "7cabde08-ab12-413c-9400-b088468a89d2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CR]",
              "VAR __ValuePreviousPeriod = [PMC CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "76bf0839-b1fd-45f3-80a5-3fc732b0a7c3",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM CR],",
              "    [PMC CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CR",
            "lineageTag": "3335d08d-a8db-48db-ab49-c7fade4fbe88",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CR],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CR",
            "lineageTag": "bdbf2bf6-0fd1-4ad3-a63d-bdfb4d47025c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT CR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT CR],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CR",
            "lineageTag": "d3a3650e-6bb1-4268-991e-438ca07a34a6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG CR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT CR]",
              "VAR __ValuePreviousPeriod = [PYMAT CR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CR",
            "lineageTag": "598c43e5-24d6-4f31-8a50-89cc3a20a852",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % CR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG CR],",
              "    [PYMAT CR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CR",
            "lineageTag": "293689a7-6a28-44fe-8648-a13e736be4d9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "9b938f20-88f2-43a0-8303-1107bf3a0e61",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CTR]",
              "VAR __ValuePreviousPeriod = [PM CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "e104ace1-88d9-4fe7-8a86-853f18b771da",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM CTR],",
              "    [PM CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CTR",
            "lineageTag": "f2e14f61-ca08-463c-9bf6-b795a5eaebf2",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD CTR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "5a4dbf94-c39b-4173-975a-c4196f7a6c9b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CTR]",
              "VAR __ValuePreviousPeriod = [PMTD CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "737ff0a5-be98-48a5-81a9-22e8472b1b30",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD CTR],",
              "    [PMTD CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CTR",
            "lineageTag": "3eebfec6-91ec-4ea5-abd3-eb4027453a18",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY CTR],",
              "    [PYC CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "124e9452-b0d0-42a3-a778-a2513107b34d",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ CTR],",
              "    [PQC CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "457acdc8-d63e-429f-81db-94a64e6018c0",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "ac9dc26d-9c67-485c-9c7b-673ba6b176f7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CTR]",
              "VAR __ValuePreviousPeriod = [PMC CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "f12ba780-3da1-44bb-aa60-82a84bdc63e5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM CTR],",
              "    [PMC CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CTR",
            "lineageTag": "478ad067-ea28-45b0-b877-b2fb5a9a77ea",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CTR],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Moving annual growth\\CTR",
            "lineageTag": "c0cf2bf5-37b0-4da7-b5d1-57e81f5e0bd7",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT CTR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT CTR],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Moving annual growth\\CTR",
            "lineageTag": "0612776c-bc4b-4133-b7b4-acc409c0d6cf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG CTR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT CTR]",
              "VAR __ValuePreviousPeriod = [PYMAT CTR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0.00",
            "displayFolder": "Time intelligence\\Moving annual growth\\CTR",
            "lineageTag": "38c971a0-5bdf-4f1c-a328-f634a86476a9",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % CTR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG CTR],",
              "    [PYMAT CTR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CTR",
            "lineageTag": "7f187efd-962a-4028-9cab-7e5e7799facc",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "dcdeb47b-b6b4-4981-95ec-4834609156bf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [IMPR]",
              "VAR __ValuePreviousPeriod = [PM IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "f83a519d-6b36-4a2c-a767-0c6d66ed3f90",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM IMPR],",
              "    [PM IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\IMPR",
            "lineageTag": "8eee585c-502e-4151-923f-45ed9c39372f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD IMPR],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "80608a41-1b57-4867-b690-d6409178fc2c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD IMPR]",
              "VAR __ValuePreviousPeriod = [PMTD IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "c0c980f0-0166-4292-ad35-396bd1120a0f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD IMPR],",
              "    [PMTD IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\IMPR",
            "lineageTag": "69d6518b-3bcc-4117-bd6a-a036bc60726e",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY IMPR],",
              "    [PYC IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "87ddeb2d-c758-4225-a1af-289078c574e6",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ IMPR],",
              "    [PQC IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "f2dac79f-3a0a-40de-a208-a461558c8b3b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "043666c6-092d-46ef-98bb-61b1a425d3ec",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD IMPR]",
              "VAR __ValuePreviousPeriod = [PMC IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "6e64ba2e-29da-42aa-8cd4-2bc550a6a20f",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM IMPR],",
              "    [PMC IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\IMPR",
            "lineageTag": "83c9ee9a-7675-4921-8dcd-b4a20e036bbb",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [IMPR],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\IMPR",
            "lineageTag": "865aef4d-dcc9-4db7-887d-9475e435bdd5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT IMPR",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT IMPR],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\IMPR",
            "lineageTag": "9a52b74d-3e5b-4a37-8a6f-6910a9492212",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG IMPR",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT IMPR]",
              "VAR __ValuePreviousPeriod = [PYMAT IMPR]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\IMPR",
            "lineageTag": "4baf95f0-4eb5-44ec-8c81-9a005c01836a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % IMPR",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG IMPR],",
              "    [PYMAT IMPR]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\IMPR",
            "lineageTag": "c077e6d0-f9fb-4865-81c2-f3dbac960f2b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PM CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "73de0264-ca42-470c-8cdc-14e5e224bae5",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [CLICK]",
              "VAR __ValuePreviousPeriod = [PM CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "7ba7736b-144d-4402-b9b5-1eba2f317410",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOM % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOM CLICK],",
              "    [PM CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth\\CLICK",
            "lineageTag": "7f31c2cd-da85-4804-8752-ebe229644c5b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMTD CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MTD CLICK],",
              "        CALCULATETABLE (",
              "            DATEADD ( 'Date'[Date], -1, MONTH ),",
              "            'Date'[DateWithTransactions] = TRUE",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "cc877128-ff0c-4a5c-90db-3375dff27593",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CLICK]",
              "VAR __ValuePreviousPeriod = [PMTD CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "074ea65f-9c95-46e2-9460-4e1255c45943",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MOMTD % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MOMTD CLICK],",
              "    [PMTD CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\To-date growth\\CLICK",
            "lineageTag": "ac96d738-9a2c-4dc3-b619-531295034b8a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "YDTOPY % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [YTDOPY CLICK],",
              "    [PYC CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "c4ee616f-5a8a-455a-8bd7-bc2ec48d21b4",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "QDTOPQ % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [QTDOPQ CLICK],",
              "    [PQC CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "eba45cbd-8ca5-4efc-9f43-b24dbc7d08cf",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PMC CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        PARALLELPERIOD ( 'Date'[Date], -1, MONTH )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "bf98785d-dfa1-48c3-a10b-41ed1349e6b8",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MTD CLICK]",
              "VAR __ValuePreviousPeriod = [PMC CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "c846d49c-2387-4e8f-b4a8-401649f8de50",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MTDOPM % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MTDOPM CLICK],",
              "    [PMC CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Growth over full period\\CLICK",
            "lineageTag": "08905ff1-1c2e-4b01-a0f7-2fc1e767232a",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MAT CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [CLICK],",
              "        DATESINPERIOD (",
              "            'Date'[Date],",
              "            MAX ( 'Date'[Date] ),",
              "            -1,",
              "            YEAR",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CLICK",
            "lineageTag": "6c703e13-5dac-4c7b-921b-32a08b5b7e2c",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "PYMAT CLICK",
            "expression": [
              "",
              "IF (",
              "    [_ShowValueForDates],",
              "    CALCULATE (",
              "        [MAT CLICK],",
              "        DATEADD ( 'Date'[Date], -1, YEAR )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CLICK",
            "lineageTag": "3a6a4de8-895f-47dd-89c3-88db8f147021",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG CLICK",
            "expression": [
              "",
              "VAR __ValueCurrentPeriod = [MAT CLICK]",
              "VAR __ValuePreviousPeriod = [PYMAT CLICK]",
              "VAR __Result =",
              "    IF (",
              "        NOT ISBLANK ( __ValueCurrentPeriod ) && NOT ISBLANK ( __ValuePreviousPeriod ),",
              "        __ValueCurrentPeriod - __ValuePreviousPeriod",
              "    )",
              "RETURN",
              "    __Result"
            ],
            "formatString": "0",
            "displayFolder": "Time intelligence\\Moving annual growth\\CLICK",
            "lineageTag": "edb7ff32-8c8f-4744-84fd-a5dcf11d0538",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "MATG % CLICK",
            "expression": [
              "",
              "DIVIDE ( ",
              "    [MATG CLICK],",
              "    [PYMAT CLICK]",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "Time intelligence\\Moving annual growth\\CLICK",
            "lineageTag": "10d534b9-e6a0-48ee-b75c-b656eaf4f156",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          },
          {
            "name": "BLANK_GRAPH",
            "expression": "BLANK()",
            "formatString": "0",
            "lineageTag": "9baef1b5-f4e7-4be7-8d08-4b232e514484"
          },
          {
            "name": "KPI_CARD_CLICKS",
            "expression": "CALCULATE([CLICK], ALLSELECTED('dataset'))",
            "formatString": "0",
            "lineageTag": "54304e36-79d1-472f-b70c-56651c5185e5"
          },
          {
            "name": "Refresh_date",
            "expression": "\"Последнее обновление \" & FORMAT(LASTDATE('dataset'[Date]) + 1, \"dd.mm.yyyy\")",
            "lineageTag": "f2c739a2-dd58-438a-83e3-6089afa1ea7d"
          },
          {
            "name": "Мера",
            "expression": "DIVIDE([CONV],CALCULATE([CONV],ALLSELECTED('dataset')))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8e409b46-164d-4722-be21-281a5c34adff",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "RECOMMENDS",
            "expression": [
              "",
              "var kpi_section = IF(",
              "    [NEW_CORR] > 0.5, \"KPI выполнен на отлично\", ",
              "    IF([NEW_CORR] > 0.25, \"KPI выполняется хорошо\", ",
              "    IF([NEW_CORR] > 0, \"KPI выполнен\", ",
              "    IF([NEW_CORR] < -0.8, \"Результат сильно хуже KPI\",",
              "    IF([NEW_CORR] < -0.5, \"KPI выполняется плохо\", ",
              "    IF([NEW_CORR] < -0.2, \"KPI не выполняется\", \"KPI незначительно проседает\"))))))",
              "",
              "var ur_section = IF(",
              "    [POT %] > 1, \". Масштабируйте трафик по данному срезу\",",
              "    IF([POT %] > 0.5, \". Повышайте постепенно трафик по срезу\",",
              "    IF([POT %] > 0, \". Можно увеличить трафик, и чуть позже оценить результат\",",
              "    IF([POT %] < -0.8, \". Можно выключить, срез неэффективен\",",
              "    IF([POT %] < -0.5, \". Сокращайте трафик, результат отрицательный\",",
              "    IF([POT %] < -0.2, \". Посмотрите результат за прошлые периоды\", \". Срез не сильно влияет на общий результат\"))))))",
              "",
              "var res = kpi_section & ur_section",
              "VAR clck =",
              "    IF (",
              "        SUM ( 'dataset'[Cost] ) < SUM ( tCPA[tCPA] ),",
              "        IF ( [CONV] > 2, res, BLANK () ),",
              "        res",
              "    )",
              "RETURN",
              "    clck"
            ],
            "lineageTag": "3465f92d-1240-48f4-a2d9-b9688bd4bc69"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "_firstconv",
        "lineageTag": "dbde0def-224a-4fe8-b74f-0ee659b8a799",
        "columns": [
          {
            "name": "first conversion",
            "dataType": "string",
            "sourceColumn": "first conversion",
            "lineageTag": "87ad5e0d-2532-4c82-acb9-1816a7251c10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_firstconv-66fef199-afeb-49a0-a38b-d906e678fda3",
            "mode": "import",
            "queryGroup": "Datasets\\service",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WujDvYtOFfRc2Xmy4sOHC9gs7LjZd7FGK1QFKLLyw62LDxW6IQCwA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"first conversion\" = _t]),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"first conversion\", type text}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "_interface_A",
        "lineageTag": "2f4ffef1-b055-40c2-8854-8c6859fa9940",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "_interface",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ _interface",
            "lineageTag": "f5723199-31dd-42ef-ab5a-b1a28c403f03",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: _interface"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: _interface",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ _interface",
            "lineageTag": "ca094b9e-ba07-47f5-bd2d-d5cb2c4fe6b9",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ _interface",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "293dc241-1fb4-4364-bbd7-a1e60509db33",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_interface_A-0ff6fba6-de13-41c9-906a-43856cdee3ef",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Показы\", NAMEOF('_measures'[IMPR]), 0),",
                "    (\"Клики\", NAMEOF('_measures'[CLICK]), 1),",
                "    (\"Расход\", NAMEOF('_measures'[COST_VAT]), 2),",
                "    (\"Конверсии\", NAMEOF('_measures'[CONV]), 3),",
                "    (\"KPI CPA\", NAMEOF('_measures'[NEW_CORR]), 4),",
                "    (\"CPA\", NAMEOF('_measures'[CPA]), 5),",
                "    (\"CR\", NAMEOF('_measures'[CR]), 6),",
                "    (\"CTR\", NAMEOF('_measures'[CTR]), 7),",
                "    (\"CPC\", NAMEOF('_measures'[CPC]), 8),",
                "    (\"BR\", NAMEOF('_measures'[BR]), 9)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8015e70a1a3841bbb121db60c7f0af8e"
          }
        ]
      },
      {
        "name": "_interface_B",
        "lineageTag": "ee9da4d6-1b53-44c9-ad3e-f0a1b603cef0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "_interface_B",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Заказ _interface_B",
            "lineageTag": "c8757249-4452-4776-933b-943e7c8b17fd",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Поля: _interface_B"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Поля: _interface_B",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Заказ _interface_B",
            "lineageTag": "554d28bd-1d78-45d3-b002-f3b9be165b86",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Заказ _interface_B",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "1b9c90a2-1ec3-45bc-92f3-25049bff5eb9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_interface_B-00e63963-0a3b-48c0-895a-b2483fc5bcaa",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Показы\", NAMEOF('_measures'[IMPR]), 0),",
                "    (\"Клики\", NAMEOF('_measures'[CLICK]), 1),",
                "    (\"Расход\", NAMEOF('_measures'[COST_VAT]), 2),",
                "    (\"Конверсии\", NAMEOF('_measures'[CONV]), 3),",
                "    (\"KPI CPA\", NAMEOF('_measures'[NEW_CORR]), 4),",
                "    (\"CPA\", NAMEOF('_measures'[CPA]), 5),",
                "    (\"CR\", NAMEOF('_measures'[CR]), 6),",
                "    (\"CTR\", NAMEOF('_measures'[CTR]), 7),",
                "    (\"CPC\", NAMEOF('_measures'[CPC]), 8),",
                "    (\"BR\", NAMEOF('_measures'[BR]), 9),",
                "    (\"Скрыть\", NAMEOF('_measures'[BLANK_GRAPH]), 10)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cc2ac5f1ee65495084c7c5bd38546cc2"
          }
        ]
      },
      {
        "name": "_project",
        "lineageTag": "a619df7b-b8f4-46bb-984d-beff6b56ded7",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "fb037d70-6492-42db-973f-41755087a52c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_project-b11b7282-6d43-4ebd-9a7a-c97dc2d33918",
            "mode": "import",
            "queryGroup": "Datasets\\service",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Проект,",
                "    #\"Преобразовано в таблицу\" = #table(1, {{Источник}})",
                "in",
                "    #\"Преобразовано в таблицу\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "HolidaysDefinition",
        "isHidden": true,
        "lineageTag": "5876aabf-5414-4caf-9cc4-ec00d4c18a39",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "ISO Country",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[ISO Country]",
            "lineageTag": "73303790-4806-44a6-a668-15d6c1fcc4ea",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MonthNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MonthNumber]",
            "lineageTag": "f2e731d7-5629-4300-bc5c-bd4090241aa2",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "DayNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[DayNumber]",
            "lineageTag": "28778d14-3d65-45c0-a4ed-12bf998ad343",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "WeekDayNumber",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[WeekDayNumber]",
            "lineageTag": "2aa83e5f-65b5-4755-8c35-cad49e765b47",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OffsetWeek",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OffsetWeek]",
            "lineageTag": "2f863a4b-e68b-4823-9027-921ba61fba10",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OffsetDays",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OffsetDays]",
            "lineageTag": "4e86e01c-d983-4378-a7df-e5681b0b8bef",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "HolidayName",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[HolidayName]",
            "lineageTag": "28d4a37a-9219-4a23-926a-50f1b346acb4",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "SubstituteHoliday",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[SubstituteHoliday]",
            "lineageTag": "6437edc3-c444-4ecc-9545-93970c313fb4",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "ConflictPriority",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[ConflictPriority]",
            "lineageTag": "763afa83-c8f7-4554-8f17-e4621c30bdfc",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "FirstYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[FirstYear]",
            "lineageTag": "60c4ac61-a7ea-4dcc-b394-bdf8daae466d",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "LastYear",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[LastYear]",
            "lineageTag": "fafebfa1-ac6b-4fce-aca1-0b2bf6a29d8a",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "HolidaysDefinition",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "DATATABLE (",
                "    \"ISO Country\", STRING,        -- ISO country code(to enable filter based on country)",
                "    \"MonthNumber\", INTEGER,       -- Number of month - use 99,98,97,96 for relative dates using an offset over special references:",
                "                                  --     99 = Easter (DayNumber 1 = Easter Monday, DayNumber -2 = Easter Friday)",
                "                                  --     98 = Swedish Midsummer Day ",
                "                                  --     97 = September Equinox",
                "                                  --     96 = March Equinox",
                "    \"DayNumber\", INTEGER,         -- Absolute day(ignore WeekDayNumber, otherwise use 0)",
                "    \"WeekDayNumber\", INTEGER,     -- 0 = Sunday, 1 = Monday, ... , 7 = Saturday",
                "    \"OffsetWeek\", INTEGER,        -- 1 = first, 2 = second, ... -1 = last, -2 = second - last, ...",
                "    \"OffsetDays\", INTEGER,        -- days to add after offsetWeek and WeekDayNumber have been applied",
                "    \"HolidayName\", STRING,        -- Holiday name",
                "    \"SubstituteHoliday\", INTEGER, -- 0 = no substituteHoliday, 1 = substitute holiday with next working day, 2 = substitute holiday with next working day",
                "                                  -- (use 2 before 1 only, e.g.Christmas = 2, Boxing Day = 1)",
                "                                  -- -1 = if it falls on a Saturday then it is observed on Friday, if it falls on a Sunday then it is observed on Monday",
                "    \"ConflictPriority\", INTEGER,  -- Priority in case of two or more holidays in the same date - lower number-- > higher priority",
                "                                  -- For example: marking Easter relative days with 150 and other holidays with 100 means that other holidays take",
                "                                  --              precedence over Easter - related days; use 50 for Easter related holidays to invert such a priority",
                "    \"FirstYear\", INTEGER,         -- First year for the holiday, 0 if it is not defined",
                "    \"LastYear\", INTEGER,          -- Last year for the holiday, 0 if it is not defined",
                "    {",
                "        { \"US\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"US\", 1, 0, 1, 3, 0, \"Martin Luther King, Jr.\", 0, 100, 0, 0 },",
                "        { \"US\", 2, 0, 1, 3, 0, \"Presidents' Day\", 0, 100, 0, 0 },",
                "        { \"US\", 5, 0, 1, -1, 0, \"Memorial Day\", 0, 100, 0, 0 },",
                "        { \"US\", 6, 19, 0, 0, 0, \"Juneteenth\", -1, 100, 2021, 0 },",
                "        { \"US\", 7, 4, 0, 0, 0, \"Independence Day\", 0, 100, 0, 0 },",
                "        { \"US\", 9, 0, 1, 1, 0, \"Labor Day\", 0, 100, 0, 0 },",
                "        { \"US\", 10, 0, 1, 2, 0, \"Columbus Day\", 0, 100, 0, 0 },",
                "        { \"US\", 11, 11, 0, 0, 0, \"Veterans Day\", 0, 100, 0, 0 },",
                "        { \"US\", 11, 0, 4, 4, 0, \"Thanksgiving Day\", 0, 100, 0, 0 },",
                "        { \"US\", 11, 0, 4, 4, 1, \"Black Friday\", 0, 100, 0, 0 },",
                "        { \"US\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"AT\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"AT\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"AT\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"AT\", 99, 60, 0, 0, 0, \"Corpus Christi\", 0, 50, 0, 0 },",
                "        { \"AT\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 10, 26, 0, 0, 0, \"National Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 12, 8, 0, 0, 0, \"Immaculate Conception Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"AT\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"AU\", 1, 1, 0, 0, 0, \"New Year's Day\", 1, 100, 0, 0 },",
                "        { \"AU\", 1, 26, 0, 0, 0, \"Australia Day\", 1, 100, 0, 0 },",
                "        { \"AU\", 99, -1, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"AU\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"AU\", 4, 25, 0, 0, 0, \"Anzac Day\", 1, 100, 0, 0 },",
                "        { \"AU\", 12, 25, 0, 0, 0, \"Christmas Day\", 2, 100, 0, 0 },",
                "        { \"AU\", 12, 26, 0, 0, 0, \"Boxing Day\", 1, 100, 0, 0 },",
                "        { \"BE\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"BE\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"BE\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"BE\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 7, 21, 0, 0, 0, \"Belgian National Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 11, 11, 0, 0, 0, \"Armistice Day\", 0, 100, 0, 0 },",
                "        { \"BE\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"CA\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"CA\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"CA\", 7, 1, 0, 0, 0, \"Canada Day\", 0, 50, 0, 0 },",
                "        { \"CA\", 9, 0, 1, 1, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"CA\", 10, 0, 1, 2, 0, \"Thanksgiving\", 0, 100, 0, 0 },",
                "        { \"CA\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"DE\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"DE\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"DE\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"DE\", 10, 3, 0, 0, 0, \"German Unity Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"DE\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"ES\", 99, -3, 0, 0, 0, \"Maundy Thursday\", 0, 50, 0, 0 },",
                "        { \"ES\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"ES\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"ES\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 10, 12, 0, 0, 0, \"Fiesta Navional de España\", 0, 100, 0, 0 },",
                "        { \"ES\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 12, 6, 0, 0, 0, \"Constitution Day\", 0, 100, 0, 0 },",
                "        { \"ES\", 12, 8, 0, 0, 0, \"Immaculate Conception\", 0, 100, 0, 0 },",
                "        { \"ES\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"FR\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 5, 8, 0, 0, 0, \"Victor in Europe Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"FR\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"FR\", 7, 14, 0, 0, 0, \"Bastille Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 11, 11, 0, 0, 0, \"Armistice Day\", 0, 100, 0, 0 },",
                "        { \"FR\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"GB\", 1, 1, 0, 0, 0, \"New Year's Day\", 1, 100, 0, 0 },",
                "        { \"GB\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"GB\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"GB\", 5, 0, 1, 1, 0, \"May Day Bank Holiday\", 0, 100, 0, 0 },",
                "        { \"GB\", 5, 0, 1, -1, 0, \"Spring Bank Holiday\", 0, 100, 0, 0 },",
                "        { \"GB\", 8, 0, 1, -1, 0, \"Late Summer Bank Holiday\", 0, 100, 0, 0 },",
                "        { \"GB\", 12, 25, 0, 0, 0, \"Christmas Day\", 2, 100, 0, 0 },",
                "        { \"GB\", 12, 26, 0, 0, 0, \"Boxing Day\", 1, 100, 0, 0 },",
                "        { \"IT\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"IT\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 100, 0, 0 },",
                "        { \"IT\", 4, 25, 0, 0, 0, \"Liberation Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 6, 2, 0, 0, 0, \"Republic Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 12, 8, 0, 0, 0, \"Immaculate Conception\", 0, 100, 0, 0 },",
                "        { \"IT\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"IT\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"NL\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"NL\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"NL\", 4, 27, 0, 0, 0, \"King's Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 5, 5, 0, 0, 0, \"Liberation Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"NL\", 12, 26, 0, 0, 0, \"St. Stephen's Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 99, -3, 0, 0, 0, \"Maundy Thursday\", 0, 100, 0, 0 },",
                "        { \"NO\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"NO\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"NO\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"NO\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"NO\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 5, 17, 0, 0, 0, \"Constitution Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 12, 24, 0, 0, 0, \"Christmas Eve\", 0, 50, 0, 0 },",
                "        { \"NO\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 12, 26, 0, 0, 0, \"Boxing Day\", 0, 100, 0, 0 },",
                "        { \"NO\", 12, 31, 0, 0, 0, \"New Year's Eve\", 0, 100, 0, 0 },",
                "        { \"PT\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"PT\", 99, 60, 0, 0, 0, \"Corpus Christi\", 0, 50, 0, 0 },",
                "        { \"PT\", 4, 25, 0, 0, 0, \"Freedom Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 6, 10, 0, 0, 0, \"Portugal Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 8, 15, 0, 0, 0, \"Assumption Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 10, 5, 0, 0, 0, \"Republic Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 11, 1, 0, 0, 0, \"All Saints' Day\", 0, 100, 0, 0 },",
                "        { \"PT\", 12, 1, 0, 0, 0, \"Restoration of Independence\", 0, 100, 0, 0 },",
                "        { \"PT\", 12, 8, 0, 0, 0, \"Immaculate Conception\", 0, 50, 0, 0 },",
                "        { \"PT\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 1, 6, 0, 0, 0, \"Epiphany\", 0, 100, 0, 0 },",
                "        { \"SE\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"SE\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"SE\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"SE\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 6, 6, 0, 0, 0, \"National Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 12, 24, 0, 0, 0, \"Christmas Eve\", 0, 50, 0, 0 },",
                "        { \"SE\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 12, 26, 0, 0, 0, \"Boxing Day\", 0, 100, 0, 0 },",
                "        { \"SE\", 12, 31, 0, 0, 0, \"New Year's Eve\", 0, 100, 0, 0 },",
                "        { \"SE\", 98, -1, 0, 0, 0, \"Midsubber Eve\", 0, 50, 0, 0 },",
                "        { \"DK\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"DK\", 99, -3, 0, 0, 0, \"Maundy Thursday\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 1, 0, 0, 0, \"Easter Monday\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 26, 0, 0, 0, \"Prayer Day\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 39, 0, 0, 0, \"Ascension Day\", 0, 50, 0, 0 },",
                "        { \"DK\", 99, 50, 0, 0, 0, \"Whit Monday\", 0, 50, 0, 0 },",
                "        { \"DK\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"DK\", 6, 5, 0, 0, 0, \"Constitution Day\", 0, 50, 0, 0 },",
                "        { \"DK\", 12, 24, 0, 0, 0, \"Christmas Eve\", 0, 50, 0, 0 },",
                "        { \"DK\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"DK\", 12, 26, 0, 0, 0, \"Second Day of Christmas\", 0, 100, 0, 0 },",
                "        { \"DK\", 12, 31, 0, 0, 0, \"New Year's Eve\", 0, 100, 0, 0 },",
                "        { \"BR\", 1, 1, 0, 0, 0, \"New Year's Day\", 0, 100, 0, 0 },",
                "        { \"BR\", 4, 21, 0, 0, 0, \"Tiradentes' Day\", 0, 50, 0, 0 },",
                "        { \"BR\", 99, -2, 0, 0, 0, \"Good Friday\", 0, 50, 0, 0 },",
                "        { \"BR\", 5, 1, 0, 0, 0, \"Labour Day\", 0, 100, 0, 0 },",
                "        { \"BR\", 9, 7, 0, 0, 0, \"Independence Day\", 0, 100, 0, 0 },",
                "        { \"BR\", 10, 12, 0, 0, 0, \"Lady of Aparecida\", 0, 100, 0, 0 },",
                "        { \"BR\", 11, 2, 0, 0, 0, \"All Soul's Day'\", 0, 100, 0, 0 },",
                "        { \"BR\", 11, 15, 0, 0, 0, \"Republic Day'\", 0, 100, 0, 0 },",
                "        { \"BR\", 12, 25, 0, 0, 0, \"Christmas Day\", 0, 100, 0, 0 },",
                "        { \"JP\", 1, 1, 0, 0, 0, \"New Year's Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 1, 15, 0, 0, 0, \"Coming of Age Day\", 2, 100, 0, 1999 },",
                "        { \"JP\", 1, 0, 1, 2, 0, \"Coming of Age Day\", 0, 100, 2000, 0 },",
                "        { \"JP\", 2, 11, 0, 0, 0, \"National Foundation Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 2, 23, 0, 0, 0, \"The Emperor's Birthday\", 2, 100, 2020, 0 },",
                "        { \"JP\", 12, 23, 0, 0, 0, \"The Emperor's Birthday\", 2, 100, 1989, 2018 },",
                "        { \"JP\", 96, 0, 0, 0, 0, \"Vernal Equinox Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 4, 29, 0, 0, 0, \"The Emperor's Birthday\", 2, 100, 0, 1988 },",
                "        { \"JP\", 4, 29, 0, 0, 0, \"Greenery Day\", 2, 100, 1989, 2006 },",
                "        { \"JP\", 4, 29, 0, 0, 0, \"Shōwa Day\", 2, 100, 2007, 0 },",
                "        { \"JP\", 5, 3, 0, 0, 0, \"Constitution Memorial Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 5, 4, 0, 0, 0, \"Greenery Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 5, 5, 0, 0, 0, \"Children's Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 7, 20, 0, 0, 0, \"Marine Day\", 2, 100, 0, 2002 },",
                "        { \"JP\", 7, 0, 1, 3, 0, \"Marine Day\", 0, 100, 2003, 0 },",
                "        { \"JP\", 8, 11, 0, 0, 0, \"Mountain Day\", 2, 100, 2016, 0 },",
                "        { \"JP\", 9, 15, 0, 0, 0, \"Respect for the Aged Day\", 2, 100, 0, 2002 },",
                "        { \"JP\", 9, 0, 1, 3, 0, \"Respect for the Aged Day\", 0, 100, 2003, 0 },",
                "        { \"JP\", 97, 0, 0, 0, 0, \"Autumnal Equinox Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 10, 10, 0, 0, 0, \"Sports Day\", 2, 100, 0, 1999 },",
                "        { \"JP\", 10, 0, 1, 2, 0, \"Sports Day\", 0, 100, 2000, 0 },",
                "        { \"JP\", 11, 3, 0, 0, 0, \"Culture Day\", 2, 100, 0, 0 },",
                "        { \"JP\", 11, 23, 0, 0, 0, \"Labour Thanksgiving Day\", 2, 100, 0, 0 },",
                "        { \"RU\", 1, 1, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 2, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 3, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 4, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 5, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 6, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 7, 0, 0, 0, \"Рождество Христово\", 0, 100, 0, 0 },",
                "        { \"RU\", 1, 8, 0, 0, 0, \"Новогодние каникулы\", 0, 100, 0, 0 },",
                "        { \"RU\", 2, 23, 0, 0, 0, \"День защитника Отечества\", 0, 100, 0, 0 },",
                "        { \"RU\", 3, 8, 0, 0, 0, \"Международный женский день\", 0, 100, 0, 0 },",
                "        { \"RU\", 5, 1, 0, 0, 0, \"Праздник Весны и Труда\", 0, 100, 0, 0 },",
                "        { \"RU\", 5, 9, 0, 0, 0, \"День Победы\", 0, 100, 0, 0 },",
                "        { \"RU\", 6, 12, 0, 0, 0, \"День России\", 0, 100, 0, 0 },",
                "        { \"RU\", 11, 4, 0, 0, 0, \"День народного единства\", 0, 100, 0, 0 },",
                "        { \"CN\", 1, 1, 0, 0, 0, \"元旦\", 0, 100, 0, 0 },",
                "        { \"CN\", 5, 1, 0, 0, 0, \"劳动节\", 0, 100, 0, 0 },",
                "        { \"CN\", 10, 1, 0, 0, 0, \"国庆节\", 0, 100, 0, 0 },",
                "        { \"CN\", 10, 2, 0, 0, 0, \"国庆节\", 0, 100, 0, 0 },",
                "        { \"CN\", 10, 3, 0, 0, 0, \"国庆节\", 0, 100, 0, 0 }",
                "    }",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Holidays"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "HolidaysDefinition"
          }
        ]
      },
      {
        "name": "Holidays",
        "isHidden": true,
        "lineageTag": "996ec6f8-968f-415b-beb4-60c04ab17f74",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Holiday Date]",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "d57149fe-792f-46be-8cb6-552e278e5dbf",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Holiday Name]",
            "lineageTag": "5d4ad990-7d23-4b39-ba56-de9a61ee36d8",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Holidays",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "-- ",
                "--    Configuration",
                "-- ",
                "VAR __FirstYear = YEAR ( MINX ( { MIN ( 'dataset'[Date] ) }, ''[Value] ) )",
                "VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'dataset'[Date] ) }, ''[Value] ) )",
                "VAR __IsoCountryHolidays = \"US\"",
                "VAR __WorkingDays = { 2, 3, 4, 5, 6 }",
                "VAR __InLieuOfPrefix = \"(in lieu of \"",
                "VAR __InLieuOfSuffix = \")\"",
                "----------------------------------------",
                "VAR __FilterIsoConfig =",
                "    FILTER(",
                "        'HolidaysDefinition',",
                "        IF(",
                "            CONTAINS('HolidaysDefinition', 'HolidaysDefinition'[ISO Country], __IsoCountryHolidays)",
                "                || __IsoCountryHolidays = \"\",",
                "            'HolidaysDefinition'[ISO Country] = __IsoCountryHolidays,",
                "            ERROR(\"IsoCountryHolidays set to an unsupported country code\")",
                "        )",
                "    )",
                "VAR __ConfigGeneration =",
                "    GENERATE(",
                "        GENERATESERIES(__FirstYear - 1, __LastYear + 1, 1),",
                "        __FilterIsoConfig",
                "    )",
                "VAR __GeneratedRawWithDuplicatesUnfiltered =",
                "    GENERATE(",
                "        __ConfigGeneration,",
                "        VAR __HolidayYear = ''[Value]",
                "        VAR __EasterDate =",
                "            -- Code adapted from original VB version from https://www.assa.org.au/edm ",
                "            VAR _EasterYear = __HolidayYear",
                "            VAR _FirstDig =",
                "                INT ( _EasterYear / 100 )",
                "            VAR _Remain19 =",
                "                MOD ( _EasterYear, 19 ) ",
                "            -- Calculate PFM date",
                "            VAR _temp1 =",
                "                MOD (",
                "                    INT ( ( _FirstDig - 15 ) / 2 )",
                "                        + 202",
                "                        - 11 * _Remain19",
                "                        + SWITCH (",
                "                            TRUE,",
                "                            _FirstDig IN { 21, 24, 25, 27, 28, 29, 30, 31, 32, 34, 35, 38 },",
                "                            0",
                "                        ),",
                "                    30",
                "                )",
                "            VAR _tA =",
                "                _temp1 + 21",
                "                    + IF ( _temp1 = 29 || ( _temp1 = 28 && _Remain19 > 10 ), -1 ) // ",
                "            -- Find the next Sunday",
                "            VAR _tB =",
                "                MOD ( _tA - 19, 7 )",
                "            VAR _tCpre =",
                "                MOD ( 40 - _FirstDig, 4 )",
                "            VAR _tC =",
                "                _tCpre",
                "                    + IF ( _tCpre = 3, 1 )",
                "                    + IF ( _tCpre > 1, 1 )",
                "            VAR _temp2 =",
                "                MOD ( _EasterYear, 100 )",
                "            VAR _tD =",
                "                MOD ( _temp2 + INT ( _temp2 / 4 ), 7 )",
                "            VAR _tE =",
                "                MOD ( 20 - _tB - _tC - _tD, 7 )",
                "                    + 1",
                "            VAR _d = _tA + _tE ",
                "            -- Return the date",
                "            VAR _EasterDay =",
                "                IF ( _d > 31, _d - 31, _d )",
                "            VAR _EasterMonth =",
                "                IF ( _d > 31, 4, 3 )",
                "            RETURN",
                "                DATE ( _EasterYear, _EasterMonth, _EasterDay ) ",
                "            -- End of code adapted from original VB version from https://www.assa.org.au/edm",
                "        VAR __SwedishMidSummer = ",
                "            -- Compute the Midsummer day in Swedish - it is the Saturday between 20 and 26 June",
                "            -- This calculation is valid only for years after 1953 ",
                "            -- https://sv.wikipedia.org/wiki/Midsommar_i_Sverige",
                "            VAR _June20 = ",
                "                DATE ( __HolidayYear, 6, 20 )",
                "            RETURN",
                "                DATE ( __HolidayYear, 6, 20 + (7 - WEEKDAY ( _June20, 1 ) ) )",
                "            -- End of SwedishMidSummer calculation",
                "        VAR __MarchEquinoxDay =",
                "            INT ( 20.8431 + 0.242194 * ( __HolidayYear - 1980 ) )",
                "                - INT ( ( ( __HolidayYear - 1980 ) / 4 ) )",
                "        VAR __MarchEquinox = DATE ( __HolidayYear, 3, __MarchEquinoxDay )",
                "        VAR __SeptemberEquinoxDay =",
                "            INT ( 23.2488 + 0.242194 * ( __HolidayYear - 1980 ) )",
                "                - INT ( ( __HolidayYear - 1980 ) / 4 )",
                "        VAR __SeptemberEquinox = DATE ( __HolidayYear, 9, __SeptemberEquinoxDay )",
                "        VAR __HolidayDate = ",
                "//  Workaround for a SWITCH regression that fails on service from 2022-12-10 - revert to SWITCH and remove IF once the bug is fixed",
                "//            SWITCH (",
                "//                TRUE,",
                "                IF ( 'HolidaysDefinition'[DayNumber] <> 0",
                "                    && 'HolidaysDefinition'[WeekDayNumber] <> 0, ERROR ( \"Wrong configuration in HolidaysDefinition\" ),",
                "                IF ( 'HolidaysDefinition'[DayNumber] <> 0",
                "                    && 'HolidaysDefinition'[MonthNumber] <= 12, DATE ( __HolidayYear, 'HolidaysDefinition'[MonthNumber], 'HolidaysDefinition'[DayNumber] ),",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 99, -- Easter offset",
                "                    __EasterDate + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 98, -- Swedish Midsummer Day",
                "                    __SwedishMidSummer + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 97, -- September Equinox",
                "                    __SeptemberEquinox + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[MonthNumber] = 96, -- March Equinox",
                "                    __MarchEquinox + 'HolidaysDefinition'[DayNumber],",
                "                IF ( 'HolidaysDefinition'[WeekDayNumber] <> 0,",
                "                    VAR _ReferenceDate =",
                "                        DATE ( __HolidayYear, 1",
                "                            + MOD ( 'HolidaysDefinition'[MonthNumber] - 1 + IF ( 'HolidaysDefinition'[OffsetWeek] < 0, 1 ), 12 ), 1 )",
                "                            - IF ( 'HolidaysDefinition'[OffsetWeek] < 0, 1 )",
                "                    VAR _ReferenceWeekDayNumber =",
                "                        WEEKDAY ( _ReferenceDate, 1 ) - 1",
                "                    VAR _Offset =",
                "                        'HolidaysDefinition'[WeekDayNumber] - _ReferenceWeekDayNumber",
                "                            + 7 * 'HolidaysDefinition'[OffsetWeek]",
                "                            + IF (",
                "                                'HolidaysDefinition'[OffsetWeek] > 0,",
                "                                IF ( 'HolidaysDefinition'[WeekDayNumber] >= _ReferenceWeekDayNumber, -7 ),",
                "                                IF ( _ReferenceWeekDayNumber >= 'HolidaysDefinition'[WeekDayNumber], 7)",
                "                            )",
                "                RETURN",
                "                    _ReferenceDate + _Offset + 'HolidaysDefinition'[OffsetDays],",
                "                ERROR ( \"Wrong configuration in HolidaysDefinition\" )",
                "            ) ) ) ) ) ) )",
                "//            )",
                "        VAR __HolidayDay = WEEKDAY ( __HolidayDate, 1 ) - 1",
                "        VAR __SubstituteHolidayOffset = ",
                "//            SWITCH (",
                "//                TRUE,",
                "                IF ( 'HolidaysDefinition'[SubstituteHoliday] = -1,",
                "                    SWITCH ( ",
                "                        __HolidayDay, ",
                "                        0, 1,       -- If it falls on a Sunday then it is observed on Monday",
                "                        6, -1,      -- If it falls on a Saturday then it is observed on Friday",
                "                        0",
                "                    ),",
                "                IF ( 'HolidaysDefinition'[SubstituteHoliday] > 0",
                "                    && NOT CONTAINS ( __WorkingDays, ''[Value], __HolidayDay ),",
                "                    VAR _NextWorkingDay =",
                "                        MINX (",
                "                            FILTER ( __WorkingDays, ''[Value] > __HolidayDay ),",
                "                            ''[Value]",
                "                        )",
                "                    VAR _SubstituteDay =",
                "                        IF (",
                "                            ISBLANK ( _NextWorkingDay ),",
                "                            MINX ( __WorkingDays, ''[Value] ) + 7,",
                "                            _NextWorkingDay",
                "                        )",
                "                    RETURN",
                "                        _SubstituteDay - __HolidayDay",
                "                            + ( 'HolidaysDefinition'[SubstituteHoliday] - 1 )",
                "            ) )",
                "//            )",
                "        RETURN ROW ( ",
                "            \"@HolidayDate\", DATE ( YEAR ( __HolidayDate ), MONTH ( __HolidayDate ), DAY ( __HolidayDate ) ),",
                "            \"@SubstituteHolidayOffset\", __SubstituteHolidayOffset",
                "        )",
                "    )",
                "VAR __GeneratedRawWithDuplicates =",
                "\tFILTER (",
                "        __GeneratedRawWithDuplicatesUnfiltered,",
                "        ( 'HolidaysDefinition'[FirstYear] = 0 || 'HolidaysDefinition'[FirstYear] <= ''[Value] )",
                "            && ( 'HolidaysDefinition'[LastYear] = 0 || 'HolidaysDefinition'[LastYear] >= ''[Value] )",
                "    )",
                "VAR __RawDatesUnique = ",
                "    DISTINCT ( ",
                "        SELECTCOLUMNS ( ",
                "            __GeneratedRawWithDuplicates,",
                "            \"@HolidayDateUnique\", [@HolidayDate]",
                "        )",
                "    )",
                "VAR __GeneratedRaw = ",
                "    GENERATE (",
                "        __RawDatesUnique,",
                "        VAR _FilterDate = [@HolidayDateUnique]",
                "        RETURN ",
                "            TOPN (",
                "                1,",
                "                FILTER ( ",
                "                    __GeneratedRawWithDuplicates,",
                "                    [@HolidayDate] = _FilterDate",
                "                ),",
                "                'HolidaysDefinition'[ConflictPriority],",
                "                ASC,",
                "                'HolidaysDefinition'[HolidayName], ",
                "                ASC",
                "            )",
                "    )  ",
                "VAR __GeneratedSubstitutesOffset =",
                "    SELECTCOLUMNS(",
                "        FILTER ( __GeneratedRawWithDuplicates, 'HolidaysDefinition'[SubstituteHoliday] <> 0 ),",
                "        \"Value\", ''[Value],",
                "        \"ISO Country\", 'HolidaysDefinition'[ISO Country],",
                "        \"MonthNumber\", 'HolidaysDefinition'[MonthNumber],",
                "        \"DayNumber\", 'HolidaysDefinition'[DayNumber],",
                "        \"WeekDayNumber\", 'HolidaysDefinition'[WeekDayNumber],",
                "        \"OffsetWeek\", 'HolidaysDefinition'[OffsetWeek],",
                "        \"HolidayName\", 'HolidaysDefinition'[HolidayName],",
                "        \"SubstituteHoliday\", 'HolidaysDefinition'[SubstituteHoliday],",
                "        \"ConflictPriority\", 'HolidaysDefinition'[ConflictPriority],",
                "        \"@HolidayDate\", [@HolidayDate],",
                "        \"@SubstituteHolidayOffset\",",
                "            VAR _CurrentHolidayDate = [@HolidayDate]",
                "            VAR _CurrentHolidayName = 'HolidaysDefinition'[HolidayName]",
                "            VAR _OriginalSubstituteDate = [@HolidayDate] + [@SubstituteHolidayOffset]",
                "            VAR _OtherHolidays = ",
                "                FILTER ( ",
                "                    __GeneratedRawWithDuplicates, ",
                "                    [@HolidayDate] <> _CurrentHolidayDate",
                "                    || 'HolidaysDefinition'[HolidayName] <> _CurrentHolidayName",
                "                )",
                "            VAR _ConflictDay0 = ",
                "                CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _OriginalSubstituteDate",
                "                )",
                "            VAR _ConflictDay1 = ",
                "                _ConflictDay0 ",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _OriginalSubstituteDate + 1",
                "                )",
                "            VAR _ConflictDay2 = ",
                "                _ConflictDay1 ",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _OriginalSubstituteDate + 2",
                "                )",
                "            VAR _SubstituteOffsetStep1 = [@SubstituteHolidayOffset] + _ConflictDay0 + _ConflictDay1 + _ConflictDay2",
                "            VAR _HolidayDateStep1 = _CurrentHolidayDate + _SubstituteOffsetStep1",
                "            VAR _HolidayDayStep1 =",
                "                WEEKDAY ( _HolidayDateStep1, 1 ) - 1",
                "            VAR _SubstituteHolidayOffsetNonWorkingDays =",
                "                IF (",
                "                    NOT CONTAINS ( __WorkingDays, ''[Value], _HolidayDayStep1 ),",
                "                    VAR _NextWorkingDayStep2 =",
                "                        MINX (",
                "                            FILTER ( __WorkingDays, ''[Value] > _HolidayDayStep1 ),",
                "                            ''[Value]",
                "                        )",
                "                    VAR _SubstituteDay =",
                "                        IF (",
                "                            ISBLANK ( _NextWorkingDayStep2 ),",
                "                            MINX ( __WorkingDays, ''[Value] ) + 7,",
                "                            _NextWorkingDayStep2",
                "                        )",
                "                    RETURN _SubstituteDay - _HolidayDateStep1",
                "                )",
                "            VAR _SubstituteOffsetStep2 = _SubstituteOffsetStep1 + _SubstituteHolidayOffsetNonWorkingDays",
                "            VAR _SubstituteDateStep2 = _OriginalSubstituteDate + _SubstituteOffsetStep2",
                "            VAR _ConflictDayStep2_0 = ",
                "                CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _SubstituteDateStep2",
                "                )",
                "            VAR _ConflictDayStep2_1 = ",
                "                _ConflictDayStep2_0",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _SubstituteDateStep2 + 1",
                "                )",
                "            VAR _ConflictDayStep2_2 = ",
                "                _ConflictDayStep2_1 ",
                "                && CONTAINS ( ",
                "                    _OtherHolidays,",
                "                    [@HolidayDate], _SubstituteDateStep2 + 2",
                "                )",
                "            VAR _FinalSubstituteHolidayOffset = ",
                "                _SubstituteOffsetStep2 + _ConflictDayStep2_0 + _ConflictDayStep2_1 + _ConflictDayStep2_2",
                "            RETURN",
                "                _FinalSubstituteHolidayOffset",
                "        )",
                "VAR __GeneratedSubstitutesExpanded =",
                "    ADDCOLUMNS (",
                "        __GeneratedSubstitutesOffset,",
                "        \"@ReplacementHolidayDate\", [@HolidayDate] + [@SubstituteHolidayOffset]",
                "    )",
                "VAR __GeneratedSubstitutesUnique =",
                "    DISTINCT ( ",
                "        SELECTCOLUMNS ( ",
                "            __GeneratedSubstitutesExpanded,",
                "            \"@UniqueReplacementHolidayDate\", [@ReplacementHolidayDate]",
                "        )",
                "    )",
                "VAR __GeneratedSubstitutes =",
                "    GENERATE (",
                "        __GeneratedSubstitutesUnique,",
                "        TOPN (",
                "            1,",
                "            FILTER ( ",
                "                __GeneratedSubstitutesExpanded,",
                "                [@UniqueReplacementHolidayDate] = [@ReplacementHolidayDate]",
                "            ),",
                "            [ConflictPriority],",
                "            ASC,",
                "            [HolidayName], ",
                "            ASC",
                "        )",
                "    )  ",
                "VAR __Generated =",
                "    UNION (",
                "        SELECTCOLUMNS (",
                "            __GeneratedRaw,",
                "            \"Holiday Date\", [@HolidayDate],",
                "            \"Holiday Name\", 'HolidaysDefinition'[HolidayName]",
                "        ),",
                "        SELECTCOLUMNS (",
                "            FILTER ( __GeneratedSubstitutes, [@SubstituteHolidayOffset] <> 0 ), ",
                "            \"Holiday Date\", [@HolidayDate] + [@SubstituteHolidayOffset],",
                "            \"Holiday Name\", __InLieuOfPrefix & [HolidayName]",
                "                & __InLieuOfSuffix",
                "        )",
                "    )",
                "VAR __GeneratedValidDates =",
                "    FILTER ( __Generated, [Holiday Date] > 2 )",
                "RETURN",
                "    __GeneratedValidDates"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Holidays"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Holidays"
          }
        ]
      },
      {
        "name": "DateAutoTemplate",
        "isHidden": true,
        "lineageTag": "f77a57ec-1e83-41fc-97ec-d1b0c4e37969",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "ef6d0565-525f-4762-8e2b-69d9c325073f",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year]",
            "lineageTag": "2c60af09-d91d-42cb-8abe-fa6d86b38054",
            "dataCategory": "Years",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Quarter Number]",
            "lineageTag": "de8d24ee-f2f4-4c6a-a812-f9dc8142536e",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Quarter]",
            "sortByColumn": "Year Quarter Number",
            "lineageTag": "5de7e724-19c4-4a56-b85d-fc45cfff3c24",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Quarter]",
            "lineageTag": "9c2def9b-c379-4ded-aa11-3b97df1c231f",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Month]",
            "sortByColumn": "Year Month Number",
            "lineageTag": "0d2b554d-a085-45eb-8856-6b33762d2fac",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Year Month Number]",
            "lineageTag": "9ac08a92-dff2-4ce6-987c-cfd929d22506",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Month]",
            "sortByColumn": "Month Number",
            "lineageTag": "ec984e62-ea1f-477c-bf78-7fa461225e02",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Month Number]",
            "lineageTag": "746df3b3-ec91-4309-ae26-7d754362a108",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Day of Week Number]",
            "lineageTag": "f7acf8a3-99c5-4d0c-bbcf-f9e2d1175a10",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Day of Week]",
            "sortByColumn": "Day of Week Number",
            "lineageTag": "d79bc905-a9a3-4ff6-8af0-42ca08e4d50c",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWorking",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsWorking]",
            "lineageTag": "6411e370-5b6d-44a9-9198-950817f7e023",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Working Day Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Working Day Value]",
            "lineageTag": "67ccea71-abd4-442f-ad43-c586541873ee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Holiday Name]",
            "lineageTag": "5b187c70-ffe2-455d-87e0-18d7e42fd7c6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DateWithTransactions",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[DateWithTransactions]",
            "lineageTag": "aa1fa134-726c-4520-9646-c9534ce6f716",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateAutoTemplate",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "--  ",
                "--     Configuration",
                "--  ",
                "VAR __FirstDayOfWeek = 1",
                "VAR __WorkingDays = { 2, 3, 4, 5, 6 }",
                "----------------------------------------",
                "VAR __WeekDayCalculationType = IF ( __FirstDayOfWeek = 0, 7, __FirstDayOfWeek ) + 10",
                "VAR __Calendar = ",
                "    VAR __FirstYear = YEAR ( MINX ( { MIN ( 'dataset'[Date] ) }, ''[Value] ) )",
                "    VAR __LastYear =  YEAR ( MAXX ( { MAX ( 'dataset'[Date] ) }, ''[Value] ) )",
                "    RETURN CALENDAR (",
                "        DATE ( __FirstYear, 1, 1 ),",
                "        DATE ( __LastYear, 12, 31 )",
                "    )",
                "VAR __Step3 = ",
                "    GENERATE (",
                "        __Calendar,",
                "        VAR __IsStandardLocale = IF ( FORMAT( DATE( 2000, 1, 1 ), \"oooo\" ) = \"oooo\", TRUE, FALSE )",
                "        VAR __MonthFormatString = IF( __IsStandardLocale, \"mmm\", \"ooo\" )",
                "        VAR __DayFormatString = IF( __IsStandardLocale, \"ddd\", \"aaa\" )",
                "        VAR __LastTransactionDate = MAXX ( { MAX ( 'dataset'[Date] ) }, ''[Value] )",
                "        VAR __Date = [Date]",
                "        VAR __YearNumber = YEAR ( __Date )",
                "        VAR __QuarterNumber = QUARTER ( __Date )",
                "        VAR __YearQuarterNumber = CONVERT ( __YearNumber * 4 + __QuarterNumber - 1, INTEGER )",
                "        VAR __MonthNumber = MONTH ( __Date )",
                "        VAR __WeekDayNumber = WEEKDAY ( __Date, __WeekDayCalculationType )",
                "        VAR __WeekDay = FORMAT ( __Date, __DayFormatString )",
                "        VAR __HolidayName = LOOKUPVALUE ( 'Holidays'[Holiday Name], 'Holidays'[Holiday Date],  __Date  )",
                "        VAR __IsWorkingDay = WEEKDAY ( __Date, 1 ) IN __WorkingDays && ISBLANK ( __HolidayName )",
                "        RETURN ROW ( ",
                "            \"Year\", __YearNumber,",
                "            \"Year Quarter Number\", __YearQuarterNumber,",
                "            \"Year Quarter\", FORMAT ( __QuarterNumber, \"\\Q0\" ) & \"-\" & FORMAT ( __YearNumber, \"0000\" ),",
                "            \"Quarter\", FORMAT( __QuarterNumber, \"\\Q0\" ),",
                "            \"Year Month\", FORMAT ( __Date, __MonthFormatString & \" yyyy\" ),",
                "            \"Year Month Number\", __YearNumber * 12 + __MonthNumber - 1,",
                "            \"Month\", FORMAT ( __Date, __MonthFormatString ),",
                "            \"Month Number\", __MonthNumber,",
                "            \"Day of Week Number\", __WeekDayNumber,",
                "            \"Day of Week\", __WeekDay,",
                "            \"IsWorking\", __IsWorkingDay,",
                "            \"Working Day Value\", IF ( __IsWorkingDay, 1 ),",
                "            \"Holiday Name\", __HolidayName,",
                "            \"DateWithTransactions\", __Date <= __LastTransactionDate ",
                "        )",
                "    )",
                "RETURN",
                "    __Step3"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "isHidden": true,
            "lineageTag": "2761371a-800c-4943-9696-ce965584e86f",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "d719be19-2714-43b0-b4df-5a56c55a6413"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Year Month",
                "lineageTag": "08f66a0b-c3b7-448b-9e2d-322755e0dcd3"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "f2c37bd8-02c7-4d6c-937b-d78c224071b0"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "DateAutoTemplate"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "9fa00410-2b80-4607-a86f-004d2a464418",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "DateAutoTemplate[Date]",
            "formatString": "dd.mm.yyyy",
            "lineageTag": "2afb3882-03a5-489b-8933-cffe2d1b6604",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Year]",
            "lineageTag": "832e99e9-3455-4a7e-ac2d-b9ca1ff47c7f",
            "dataCategory": "Years",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Year Quarter Number]",
            "lineageTag": "df34ba62-8222-4f4d-8008-cdf952ba9b9e",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Year Quarter]",
            "sortByColumn": "Year Quarter Number",
            "lineageTag": "6a5edb6b-0307-4681-9e81-add0a4019bd8",
            "dataCategory": "Quarters",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Quarter",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Quarter]",
            "lineageTag": "678e94d9-065b-4102-a916-07736d96a37a",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Year Month]",
            "sortByColumn": "Year Month Number",
            "lineageTag": "e27e67d5-cdf5-416e-ae48-94c8cd1d1005",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Year Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Year Month Number]",
            "lineageTag": "09a6c08f-ea04-4eb0-809b-b15999605e82",
            "dataCategory": "Months",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Month]",
            "sortByColumn": "Month Number",
            "lineageTag": "8975559f-c66a-4e0e-8dd2-42e83b7e99d8",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Month Number]",
            "lineageTag": "e1ed2e40-db5e-453f-91a7-de5558d9f59b",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week Number",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Day of Week Number]",
            "lineageTag": "b6df7f84-bb85-498b-be66-a091271607c2",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DayOfWeek"
              },
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Day of Week",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Day of Week]",
            "sortByColumn": "Day of Week Number",
            "lineageTag": "80b25ab0-3079-46b4-829e-2930e65a659a",
            "dataCategory": "DayOfWeek",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWorking",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[IsWorking]",
            "lineageTag": "2c13e048-9754-4ae3-97cc-231109b1ee1b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Working Day Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[Working Day Value]",
            "lineageTag": "ed6e9cf9-310a-4db8-b181-b7036ea501b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Holiday Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "DateAutoTemplate[Holiday Name]",
            "lineageTag": "b6373b4f-937c-4c11-9c7f-dacc3215fbf0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_FilterSafe",
                "value": "True"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DateWithTransactions",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "DateAutoTemplate[DateWithTransactions]",
            "lineageTag": "77afb4d3-1da0-4af9-9ffb-4f58c107c330",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SQLBI_AttributeTypes",
                "value": "DateDuration"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Week num",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('Date'[Date], \"YYYY\") & \"-\" & WEEKNUM('Date'[Date],2)",
            "lineageTag": "e5b2afeb-1511-440a-9686-d4b0d7c5c4ed",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "week matrix",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT(CALCULATE(FIRSTNONBLANK('Date'[Date],1),ALLEXCEPT('Date','Date'[week num])),\"YYYY-MM-DD\")&\" - \"&FORMAT(CALCULATE(LASTNONBLANK('Date'[Date],1),ALLEXCEPT('Date','Date'[week num])),\"YYYY-MM-DD\")",
            "sortByColumn": "Week num",
            "lineageTag": "84a352f5-9597-4f5d-8b79-d7f1c8c0fdea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Start week",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "DATEVALUE('Date'[Date]) - WEEKDAY(DATEVALUE('Date'[Date]),2)+1",
            "formatString": "General Date",
            "lineageTag": "0570c5b7-c8dc-43ba-b9ce-beff9dcf0e4f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "End week",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "DATEVALUE('Date'[Date]) - WEEKDAY(DATEVALUE('Date'[Date]),2)+7",
            "formatString": "General Date",
            "lineageTag": "733d72fe-886f-4865-8922-5cd0db366245",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Week",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "'Date'[Week num] & \" | \" & 'Date'[Start week] & \" - \" & 'Date'[End week]",
            "sortByColumn": "Week num",
            "lineageTag": "b06e6574-5b5d-48d4-876c-7c86c0ce380d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DateAutoTemplate"
            }
          }
        ],
        "measures": [
          {
            "name": "_ShowValueForDates",
            "expression": [
              "",
              "VAR __LastDateWithData =",
              "    CALCULATE (",
              "        MAXX ( { MAX ( 'dataset'[Date] ) }, ''[Value] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR __FirstDateVisible =",
              "    MIN ( 'Date'[Date] )",
              "VAR __Result =",
              "    __FirstDateVisible <= __LastDateWithData",
              "RETURN",
              "    __Result"
            ],
            "isHidden": true,
            "displayFolder": "Hidden Time Intelligence",
            "lineageTag": "67407c9c-4312-4899-92c2-c52d6b685a3b",
            "annotations": [
              {
                "name": "SQLBI_Template",
                "value": "TimeIntelligence"
              },
              {
                "name": "SQLBI_TimeIntelligence",
                "value": "Standard"
              },
              {
                "name": "SQLBI_CalendarType",
                "value": "Calendar"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar",
            "lineageTag": "bf7662ae-af76-410e-93ec-8ffb7b9adcd9",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "fab5d339-c189-4517-966e-ed97ff618cc0"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Year Month",
                "lineageTag": "23870e1b-2e6f-4194-ae83-889922867bdc"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date",
                "lineageTag": "c68b0753-0a89-4ede-aebb-5a004317709e"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "SQLBI_Template",
            "value": "Dates"
          },
          {
            "name": "SQLBI_TemplateTable",
            "value": "Date"
          },
          {
            "name": "SQLBI_CalendarType",
            "value": "Calendar"
          }
        ]
      },
      {
        "name": "_sort_types",
        "lineageTag": "7963b195-dbd5-49a8-90df-2e423cecbd88",
        "columns": [
          {
            "name": "SectionType",
            "dataType": "string",
            "sourceColumn": "SectionType",
            "lineageTag": "1b0b0ed3-d616-4c9b-b698-dab7a889fa6e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Индекс",
            "dataType": "int64",
            "sourceColumn": "Индекс",
            "formatString": "0",
            "lineageTag": "7af67c37-05d7-4dcb-bbfb-d3e15a33a3aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_sort_types-ef3ed55b-f3ee-4a35-9f03-6f634eacd019",
            "mode": "import",
            "queryGroup": "Datasets\\service",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dVRbbtswELwK4e+ksKg8mrMEuUsk990CSdECLYI2fQXor2KbtSxb0hWWN+rMkpTitIZgg9od7mNmV+fnE7mWBk/lZ9L6cnIwySYXBzDfSCVb6fHfSi01HDY4fuK1N/4SnhUQzr8WR4y/AiYPmI80+XcGdidL/DYa4Sh4v0mHq7V/wUtG5gZpOpwL1OEAOw6wO+mQZYvSSgP/vX/jr2SOUGO6k52SCqA6XwLjfOkLPQXcacB9gYPmziATSmLf8D4N3u8ITDP7bv1bWRu5x2snDTBnAfOL91FVJ+uYoCNl04Ez2JwstHI2h9cKxwUrQr4WJ2bMIsm36NyRSnKBoC2eitcK0qGxtuGCTfmZe57oXSLRcxiWAZSP/G6M1IblyUrjF0HbqMAHfwm9e8r7H2plTWhU4TcvoyA/I3HKRXYy5EGhlVbxcqhc+dGpQVNaVmT/M0RnLnr/PBAxi/zfaoLkr0LvIWQBOTZRrSxK8VUHcB4H1Bn/DMc19UPr/6bSpuw0SV0pL86/il5HsSsVwAWOCc8eztf+qDap+ZhITrPNR61r5asNc/9eftB9lLov4KC2/MfsrYBcUEk1BubtcRqDMnI+0miHZcAYU4Z9ytrTtKSd9E/2JIqafNrxNZypWPZZGnk4D3mPQ6sw3egbuTOcmxmqdCrs1oTdk/4wIfnBmO6s8Cy5AkX8LjSqM5XPs2EJE4i6PQLZcZsXYaloHVYDF/HF4tA2+k3Kwf/FXw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SectionType = _t, Индекс = _t]),",
                "    #\"Измененный тип\" = Table.TransformColumnTypes(Источник,{{\"Индекс\", Int64.Type}})",
                "in",
                "    #\"Измененный тип\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "f7f40283-f867-48ba-aa5a-c9457525709c",
        "toCardinality": "many",
        "fromTable": "_camplist",
        "fromColumn": "CampaignId",
        "toTable": "dataset",
        "toColumn": "CampaignId",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d44ebd69-da0a-4454-b8c0-b695dff34a5e",
        "fromTable": "dataset",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "ffefe7eb-97b6-4f26-bd88-9d182af8cf99",
        "fromTable": "dataset",
        "fromColumn": "SectionType",
        "toTable": "_sort_types",
        "toColumn": "SectionType"
      }
    ],
    "cultures": [
      {
        "name": "ru-RU",
        "linguisticMetadata": {}
      }
    ],
    "extendedProperties": [
      {
        "type": "json",
        "name": "SQLBI_BRAVO_ManageDatesConfiguration",
        "value": {
          "templateUri": "file:///C:/Users/Alex/AppData/Local/Bravo/.temp/ManageDates/Templates/Config-01.template.json",
          "isCurrent": false,
          "isCustom": false,
          "name": "Config-01",
          "description": "Standard gregorian calendar",
          "autoScan": 127,
          "onlyTablesColumns": [
            "'dataset'[Date]"
          ],
          "exceptTablesColumns": [],
          "isoCountry": "US",
          "autoNaming": 1,
          "targetMeasures": [
            "BR",
            "CLICK",
            "CONV",
            "COST_VAT",
            "CPA",
            "CPC",
            "CR",
            "CTR",
            "IMPR"
          ],
          "defaults": {
            "firstDayOfWeek": 1
          },
          "dateAvailable": true,
          "dateEnabled": true,
          "dateTableName": "Date",
          "dateTableValidation": 1,
          "dateReferenceTableName": "DateAutoTemplate",
          "dateReferenceTableValidation": 1,
          "holidaysAvailable": true,
          "holidaysEnabled": true,
          "holidaysTableName": "Holidays",
          "holidaysTableValidation": 1,
          "holidaysDefinitionTableName": "HolidaysDefinition",
          "holidaysDefinitionTableValidation": 1,
          "timeIntelligenceAvailable": true,
          "timeIntelligenceEnabled": true
        }
      }
    ],
    "expressions": [
      {
        "name": "href",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Href\"}, {\"Href\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Развернутый элемент yandex_ads\",{\"Section\", \"SectionType\"}),",
          "    #\"Строки с примененным фильтром\" = Table.SelectRows(#\"Удаленные столбцы\", each [Href] <> null and [Href] <> \"\"),",
          "    #\"Извлеченный текст перед разделителем\" = Table.TransformColumns(#\"Строки с примененным фильтром\", {{\"Href\", each Text.BeforeDelimiter(_, \"utm\"), type text}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Извлеченный текст перед разделителем\", \"SectionType\", each \"Посадочная страница\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Href\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "e6606588-6dcc-4549-bab1-bc834a62774e",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "title1",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Title\"}, {\"Title\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Title\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Основной заголовок\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Title\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "ffee8fe2-7b85-4090-abdf-5722eda82f45",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "title2",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Title2\"}, {\"Title2\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Title2\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Доп. заголовок\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Title2\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "7995df89-9099-4f8c-8b31-13522c3ef506",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "text",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Text\"}, {\"Text\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Text\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Текст объявлений\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Text\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "751ba914-c063-41da-9634-dc9506a5d2de",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "callouts",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"CalloutText\"}, {\"CalloutText\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"CalloutText\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Уточнения\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"CalloutText\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "00090bec-3358-46d7-aa5f-1922cf4f769d",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "sitelink_title",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Title_Sitelink\"}, {\"Title_Sitelink\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Title_Sitelink\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Заголовки БС\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Title_Sitelink\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "0ac3b2d0-9264-4a68-aeb5-2c51b537e78b",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "sitelink_desc",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Description_Sitelink\"}, {\"Description_Sitelink\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Description_Sitelink\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Описания БС\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Description_Sitelink\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "b5a5dea4-ef8d-49be-89c3-6f7a37ce038b",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "image_url",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"OriginalUrl\"}, {\"OriginalUrl\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"OriginalUrl\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Изображения\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"OriginalUrl\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "f41a7fba-fb29-4a7c-8d30-afab82265a36",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "image_type",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Image_Type\"}, {\"Image_Type\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Image_Type\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Тип изображений\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Image_Type\", \"Section\"}}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"FIXED_IMAGE\",\"Графическое\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"WIDE\",\"Широкий формат\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"REGULAR\",\"от 1:1 до 3:4/4:3\",Replacer.ReplaceText,{\"Section\"})",
          "in",
          "    #\"Замененное значение3\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "8585f049-d503-497b-a9ac-8442576953b6",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "graph_res",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Image_Subtype\"}, {\"Image_Subtype\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Image_Subtype\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Разрешение баннеров\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Image_Subtype\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "4eb5bedf-e988-4771-af91-eabdc617560c",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "image_names",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"Name\"}, {\"Name\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"Name\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Название файла изображений\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Name\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "156a96dd-4721-4186-bb70-249c36af3dc4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "display_url",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.NestedJoin(yd_optimize_adid_stat, {\"Section\"}, yandex_ads, {\"AdId\"}, \"yandex_ads\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент yandex_ads\" = Table.ExpandTableColumn(Источник, \"yandex_ads\", {\"DisplayUrlPath\"}, {\"DisplayUrlPath\"}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Развернутый элемент yandex_ads\",null,\"--\",Replacer.ReplaceValue,{\"DisplayUrlPath\"}),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Замененное значение\",{\"Section\", \"SectionType\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Удаленные столбцы\", \"SectionType\", each \"Отображаемая ссылка\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"DisplayUrlPath\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\ads_material_sections",
        "lineageTag": "513965f6-2b5f-40ac-97b0-e40c36b43b15",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "day_of_week",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = yd_optimize_camp_stat,",
          "    #\"Вставленное название дня\" = Table.AddColumn(Источник, \"Название дня\", each Date.DayOfWeekName([Date]), type text),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Вставленное название дня\",{\"SectionId\", \"SectionType\", \"Section\"}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Удаленные столбцы\",{{\"Название дня\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"День недели\"),",
          "    #\"Условный столбец добавлен\" = Table.AddColumn(#\"Добавлен пользовательский объект\", \"Пользовательский\", each if [Section] = \"понедельник\" then 1 else if [Section] = \"вторник\" then 2 else if [Section] = \"среда\" then 3 else if [Section] = \"четверг\" then 4 else if [Section] = \"пятница\" then 5 else if [Section] = \"суббота\" then 6 else 7),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Условный столбец добавлен\",{{\"Пользовательский\", type text}}),",
          "    #\"Объединенные столбцы\" = Table.CombineColumns(#\"Измененный тип\",{\"Пользовательский\", \"Section\"},Combiner.CombineTextByDelimiter(\" - \", QuoteStyle.None),\"Section.1\"),",
          "    #\"Переименованные столбцы1\" = Table.RenameColumns(#\"Объединенные столбцы\",{{\"Section.1\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы1\""
        ],
        "queryGroup": "Datasets\\custom_sections",
        "lineageTag": "d2a20d94-7447-410c-bd7b-d9052d506dbd",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "position_in_search",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = yd_optimize_camp_stat,",
          "    #\"Дублированный столбец\" = Table.DuplicateColumn(Источник, \"AvgImpressionPosition\", \"Копия AvgImpressionPosition\"),",
          "    #\"Вставлено: округление вверх до целого\" = Table.AddColumn(#\"Дублированный столбец\", \"Округление с увеличением\", each Number.RoundUp([Копия AvgImpressionPosition]), Int64.Type),",
          "    #\"Вставлено: округление вниз до целого\" = Table.AddColumn(#\"Вставлено: округление вверх до целого\", \"Округление с уменьшением\", each Number.RoundDown([Копия AvgImpressionPosition]), Int64.Type),",
          "    Округлено = Table.TransformColumns(#\"Вставлено: округление вниз до целого\",{{\"Копия AvgImpressionPosition\", each Number.Round(_, 1), type number}}),",
          "    #\"Дублированный столбец1\" = Table.DuplicateColumn(Округлено, \"Копия AvgImpressionPosition\", \"Копия Копия AvgImpressionPosition\"),",
          "    #\"Измененный тип1\" = Table.TransformColumnTypes(#\"Дублированный столбец1\",{{\"Копия Копия AvgImpressionPosition\", type text}}),",
          "    #\"Разделить столбец по разделителю\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Измененный тип1\", {{\"Копия Копия AvgImpressionPosition\", type text}}, \"ru-RU\"), \"Копия Копия AvgImpressionPosition\", Splitter.SplitTextByDelimiter(\",\", QuoteStyle.None), {\"Копия Копия AvgImpressionPosition.1\", \"Копия Копия AvgImpressionPosition.2\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Разделить столбец по разделителю\",{{\"Копия Копия AvgImpressionPosition.1\", Int64.Type}, {\"Копия Копия AvgImpressionPosition.2\", Int64.Type}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Измененный тип\",null,0,Replacer.ReplaceValue,{\"Копия Копия AvgImpressionPosition.2\"}),",
          "    #\"Условный столбец добавлен\" = Table.AddColumn(#\"Замененное значение\", \"Пользовательский\", each if [Копия Копия AvgImpressionPosition.2] = 0 then [Копия AvgImpressionPosition] else if [Копия Копия AvgImpressionPosition.2] = 5 then [Копия AvgImpressionPosition] else if [Копия Копия AvgImpressionPosition.2] < 5 then [Округление с уменьшением] else [Округление с увеличением]),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Условный столбец добавлен\",{\"SectionId\", \"SectionType\", \"Section\", \"Копия AvgImpressionPosition\", \"Округление с увеличением\", \"Округление с уменьшением\", \"Копия Копия AvgImpressionPosition.1\", \"Копия Копия AvgImpressionPosition.2\"}),",
          "    #\"Измененный тип2\" = Table.TransformColumnTypes(#\"Удаленные столбцы\",{{\"Пользовательский\", type text}}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Измененный тип2\",null,\"--\",Replacer.ReplaceValue,{\"Пользовательский\"}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Замененное значение1\",{{\"Пользовательский\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Позиция в поиске\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\custom_sections",
        "lineageTag": "c9cbb4b9-6324-4b63-83ab-953efe201de7",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "words_with_stop",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = yd_optimize_criteria_stat,",
          "    #\"Извлеченный текст перед разделителем\" = Table.TransformColumns(Источник, {{\"Section\", each Text.BeforeDelimiter(_, \"-\"), type text}}),",
          "    #\"Разделить столбец по разделителю\" = Table.SplitColumn(#\"Извлеченный текст перед разделителем\", \"Section\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.None), {\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Разделить столбец по разделителю\",{{\"1\", type text}, {\"2\", type text}, {\"3\", type text}, {\"4\", type text}, {\"5\", type text}, {\"6\", type text}, {\"7\", type text}}),",
          "    #\"Текст в нижнем регистре\" = Table.TransformColumns(#\"Измененный тип\",{{\"1\", Text.Lower, type text}, {\"2\", Text.Lower, type text}, {\"3\", Text.Lower, type text}, {\"4\", Text.Lower, type text}, {\"5\", Text.Lower, type text}, {\"6\", Text.Lower, type text}, {\"7\", Text.Lower, type text}}),",
          "    #\"Обрезанный текст\" = Table.TransformColumns(#\"Текст в нижнем регистре\",{{\"1\", Text.Trim, type text}, {\"2\", Text.Trim, type text}, {\"3\", Text.Trim, type text}, {\"4\", Text.Trim, type text}, {\"5\", Text.Trim, type text}, {\"6\", Text.Trim, type text}, {\"7\", Text.Trim, type text}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Обрезанный текст\",\"\",null,Replacer.ReplaceValue,{\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"+\",\"\",Replacer.ReplaceText,{\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\"}),",
          "",
          "",
          "    // Обработка каждого слова на предмет наличия стоп-слов",
          "    #\"Объединенные запросы\" = Table.NestedJoin(#\"Замененное значение1\", {\"1\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи\" = Table.ExpandTableColumn(#\"Объединенные запросы\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи\", \"1 clean word\", each if [Малозначимые слова] = null then [1] else null),",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(#\"Условный столбец добавлен\",{\"SectionId\", \"1\", \"Малозначимые слова\"}),",
          "    #\"Объединенные запросы1\" = Table.NestedJoin(#\"Удаленные столбцы\", {\"2\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи1\" = Table.ExpandTableColumn(#\"Объединенные запросы1\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен1\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи1\", \"2 clean word\", each if [Малозначимые слова] = null then [2] else null),",
          "    #\"Удаленные столбцы1\" = Table.RemoveColumns(#\"Условный столбец добавлен1\",{\"2\", \"Малозначимые слова\"}),",
          "    #\"Объединенные запросы2\" = Table.NestedJoin(#\"Удаленные столбцы1\", {\"3\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи2\" = Table.ExpandTableColumn(#\"Объединенные запросы2\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен2\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи2\", \"3 clean word\", each if [Малозначимые слова] = null then [3] else null),",
          "    #\"Удаленные столбцы2\" = Table.RemoveColumns(#\"Условный столбец добавлен2\",{\"3\", \"Малозначимые слова\"}),",
          "    #\"Объединенные запросы3\" = Table.NestedJoin(#\"Удаленные столбцы2\", {\"4\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи3\" = Table.ExpandTableColumn(#\"Объединенные запросы3\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен3\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи3\", \"4 clean word\", each if [Малозначимые слова] = null then [4] else null),",
          "    #\"Удаленные столбцы3\" = Table.RemoveColumns(#\"Условный столбец добавлен3\",{\"4\", \"Малозначимые слова\"}),",
          "    #\"Объединенные запросы4\" = Table.NestedJoin(#\"Удаленные столбцы3\", {\"5\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи4\" = Table.ExpandTableColumn(#\"Объединенные запросы4\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен4\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи4\", \"5 clean word\", each if [Малозначимые слова] = null then [5] else null),",
          "    #\"Удаленные столбцы4\" = Table.RemoveColumns(#\"Условный столбец добавлен4\",{\"5\", \"Малозначимые слова\"}),",
          "    #\"Объединенные запросы5\" = Table.NestedJoin(#\"Удаленные столбцы4\", {\"6\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи5\" = Table.ExpandTableColumn(#\"Объединенные запросы5\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен5\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи5\", \"6 clean word\", each if [Малозначимые слова] = null then [6] else null),",
          "    #\"Удаленные столбцы5\" = Table.RemoveColumns(#\"Условный столбец добавлен5\",{\"6\", \"Малозначимые слова\"}),",
          "    #\"Объединенные запросы6\" = Table.NestedJoin(#\"Удаленные столбцы5\", {\"7\"}, #\"Служебные части речи\", {\"Малозначимые слова\"}, \"Служебные части речи\", JoinKind.LeftOuter),",
          "    #\"Развернутый элемент Служебные части речи6\" = Table.ExpandTableColumn(#\"Объединенные запросы6\", \"Служебные части речи\", {\"Малозначимые слова\"}, {\"Малозначимые слова\"}),",
          "    #\"Условный столбец добавлен6\" = Table.AddColumn(#\"Развернутый элемент Служебные части речи6\", \"7 clean word\", each if [Малозначимые слова] = null then [7] else null),",
          "    #\"Удаленные столбцы6\" = Table.RemoveColumns(#\"Условный столбец добавлен6\",{\"7\", \"Малозначимые слова\"}),",
          "    ",
          "    // ########################",
          "    #\"Измененный тип1\" = Table.TransformColumnTypes(#\"Удаленные столбцы6\",{{\"1 clean word\", type text}, {\"2 clean word\", type text}, {\"3 clean word\", type text}, {\"4 clean word\", type text}, {\"5 clean word\", type text}, {\"6 clean word\", type text}, {\"7 clean word\", type text}}),",
          "    #\"Объединенные столбцы\" = Table.CombineColumns(#\"Измененный тип1\",{\"1 clean word\", \"2 clean word\", \"3 clean word\", \"4 clean word\", \"5 clean word\", \"6 clean word\", \"7 clean word\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"Без стоп слов\"),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Объединенные столбцы\",\"  \",\" \",Replacer.ReplaceText,{\"Без стоп слов\"}),",
          "    #\"Дублированный столбец\" = Table.DuplicateColumn(#\"Замененное значение2\", \"Без стоп слов\", \"Копия Без стоп слов\"),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Дублированный столбец\",\" \",\"\",Replacer.ReplaceText,{\"Копия Без стоп слов\"}),",
          "    #\"Обрезанный текст1\" = Table.TransformColumns(#\"Замененное значение3\",{{\"Без стоп слов\", Text.Trim, type text}}),",
          "    #\"Вставлено: длина текста\" = Table.AddColumn(#\"Обрезанный текст1\", \"Длина\", each Text.Length([Копия Без стоп слов]), Int64.Type),",
          "    #\"Вставлено: длина текста1\" = Table.AddColumn(#\"Вставлено: длина текста\", \"Длина.1\", each Text.Length([Без стоп слов]), Int64.Type),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Вставлено: длина текста1\", \"Кол-во слов\", each [Длина.1]-[Длина]+1),",
          "    #\"Условный столбец добавлен7\" = Table.AddColumn(#\"Добавлен пользовательский объект\", \"Пользовательский\", each if [CriterionType] = \"KEYWORD\" then [#\"Кол-во слов\"] else \"Иное условие показа\"),",
          "    #\"Удаленные столбцы7\" = Table.RemoveColumns(#\"Условный столбец добавлен7\",{\"CriterionType\", \"SectionType\", \"Без стоп слов\", \"Копия Без стоп слов\", \"Длина\", \"Длина.1\", \"Кол-во слов\"}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Удаленные столбцы7\",{{\"Пользовательский\", \"Section\"}}),",
          "    #\"Измененный тип2\" = Table.TransformColumnTypes(#\"Переименованные столбцы\",{{\"Section\", type text}}),",
          "    #\"Добавлен пользовательский объект1\" = Table.AddColumn(#\"Измененный тип2\", \"SectionType\", each \"Кол-во слов в КФ с учетом стоп-слов\"),",
          "    #\"Измененный тип3\" = Table.TransformColumnTypes(#\"Добавлен пользовательский объект1\",{{\"SectionType\", type text}})",
          "in",
          "    #\"Измененный тип3\""
        ],
        "queryGroup": "Datasets\\custom_sections",
        "lineageTag": "0410fbd8-1931-449b-b1d3-0856491ed916",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_camp_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_camp_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Дублированный столбец\" = Table.DuplicateColumn(#\"Измененный тип\", \"CampaignId\", \"Копия CampaignId\"),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Дублированный столбец\",{{\"Копия CampaignId\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Кампании\"),",
          "    #\"Переименованные столбцы1\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"Section\", \"SectionId\"}}),",
          "    #\"Дублированный столбец1\" = Table.DuplicateColumn(#\"Переименованные столбцы1\", \"CampaignName\", \"Копия CampaignName\"),",
          "    #\"Переименованные столбцы2\" = Table.RenameColumns(#\"Дублированный столбец1\",{{\"Копия CampaignName\", \"Section\"}})",
          "in",
          "    #\"Переименованные столбцы2\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "b46185d3-b69e-4964-946a-0cc16a1269d1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_adform_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_adform_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"AdFormat\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"IMAGE\",\"Графический\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"TEXT\",\"Текстовый\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"VIDEO\",\"Видео\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"SMART_MULTIPLE\",\"Смарт-баннер\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"SMART_SINGLE\",\"Смарт-объявление\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение5\" = Table.ReplaceValue(#\"Замененное значение4\",\"ADAPTIVE_IMAGE\",\"Адаптивный графический\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение6\" = Table.ReplaceValue(#\"Замененное значение5\",\"SMART_TILE\",\"Смарт-плитка\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение6\", \"SectionType\", each \"Формат объявления\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "08af2421-ccc8-47ce-b008-61fa0875ffb8",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_adid_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_adid_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"AdId\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Объявление\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "afe73f25-aee5-4b5d-8d8b-c27b7ffc287e",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_agegen_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_agegen_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Измененный тип\",\"GENDER_MALE\",\"Муж\",Replacer.ReplaceText,{\"Gender\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"GENDER_FEMALE\",\"Жен\",Replacer.ReplaceText,{\"Gender\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"AGE_\",\"\",Replacer.ReplaceText,{\"Age\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"_\",\"-\",Replacer.ReplaceText,{\"Age\"}),",
          "    #\"Объединенные столбцы\" = Table.CombineColumns(#\"Замененное значение3\",{\"Gender\", \"Age\"},Combiner.CombineTextByDelimiter(\" | \", QuoteStyle.None),\"Section\"),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Объединенные столбцы\", \"SectionType\", each \"Пол и возраст\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "990c1082-f8a8-41ca-a142-ba0fe803b7d7",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_clcktype_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_clcktype_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"ClickType\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"TITLE\",\"Заголовок или отображ. ссылка\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"SITELINK\",\"Быстрая ссылка \",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"VCARD\",\"Визитка\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"CHAT\",\"Чат с оператором\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"PHONE\",\"Номер телефона\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение5\" = Table.ReplaceValue(#\"Замененное значение4\",\"MOBILE_APP_ICON\",\"Иконка приложения\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение6\" = Table.ReplaceValue(#\"Замененное значение5\",\"BUTTON\",\"Кнопка загрузки/установки\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение7\" = Table.ReplaceValue(#\"Замененное значение6\",\"PRODUCT_EXTENSIONS\",\"Товарные дополнения\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение8\" = Table.ReplaceValue(#\"Замененное значение7\",\"MARKET\",\"Маркет\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение9\" = Table.ReplaceValue(#\"Замененное значение8\",\"UNKNOWN\",\"Не определено\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение9\", \"SectionType\", each \"Место клика\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "7460f44c-e982-4793-9034-cb57c9f966d5",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_criteria_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_criteria_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"Criterion\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Условие показа\"),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Добавлен пользовательский объект\",\"---autotargeting\",\"Автотаргетинг\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Вставленный текст перед разделителем\" = Table.AddColumn(#\"Замененное значение\", \"Текст перед разделителем\", each Text.BeforeDelimiter([Section], \"-\"), type text),",
          "    #\"Условный столбец добавлен\" = Table.AddColumn(#\"Вставленный текст перед разделителем\", \"Пользовательский\", each if [CriterionType] = \"KEYWORD\" then [Текст перед разделителем] else [Section]),",
          "    #\"Удаленные столбцы1\" = Table.RemoveColumns(#\"Условный столбец добавлен\",{\"Текст перед разделителем\", \"Section\"}),",
          "    #\"Переименованные столбцы1\" = Table.RenameColumns(#\"Удаленные столбцы1\",{{\"Пользовательский\", \"Section\"}, {\"CriterionId\", \"SectionId\"}})",
          "in",
          "    #\"Переименованные столбцы1\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "9a8e5df5-0cfc-475f-a049-4da5a390baa5",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_critype_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_critype_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"CriterionType\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"KEYWORD\",\"Ключевая фраза\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"AUTOTARGETING\",\"Автотаргетинг\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"RETARGETING\",\"Условие ретаргетинга\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"INTERESTS_AND_DEMOGRAPHICS\",\"Аудитория по профилю пользователя\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"MOBILE_APP_CATEGORY\",\"Интерес к категории приложений\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение5\" = Table.ReplaceValue(#\"Замененное значение4\",\"WEBPAGE_FILTER\",\"Условие по контенту сайта\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение6\" = Table.ReplaceValue(#\"Замененное значение5\",\"FEED_FILTER\",\"Фильтр на основе фида\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение6\", \"SectionType\", each \"Тип условия показа\"),",
          "    #\"Переименованные столбцы1\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"CriterionId\", \"SectionId\"}})",
          "in",
          "    #\"Переименованные столбцы1\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "027f60c1-b4ef-4f28-b8bb-6b52c237fcc9",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_device_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_device_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"Device\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"DESKTOP\",\"Компьютер\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"MOBILE\",\"Смартфон\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"TABLET\",\"Планшет\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение2\", \"SectionType\", each \"Устройство\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "75563056-6c16-40cb-a0a9-b14d2c16fa16",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_group_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_group_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"AdGroupName\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Группа объявлений\"),",
          "    #\"Переименованные столбцы1\" = Table.RenameColumns(#\"Добавлен пользовательский объект\",{{\"AdGroupId\", \"SectionId\"}})",
          "in",
          "    #\"Переименованные столбцы1\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "9e6228e0-2b3e-4bd0-9af6-974d1980d57d",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_hours",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_hours_stat\"]}[Data],",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(public_yandex_ads,{{\"ym_ad_hour\", \"Section\"}}),",
          "    #\"Строки с примененным фильтром\" = Table.SelectRows(#\"Переименованные столбцы\", each [Section] <> null and [Section] <> \"\"),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Строки с примененным фильтром\",{{\"Date\", type date}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Измененный тип\", \"SectionType\", each \"Час суток\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "41315794-c269-48ed-9bee-6758e74042a1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_income_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_income_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"IncomeGrade\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"VERY_HIGH\",\"Очень высокий доход\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"HIGH\",\"Высокий доход\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"ABOVE_AVERAGE\",\"Выше среднего\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"OTHER\",\"Остальные\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение3\", \"SectionType\", each \"Уровень дохода\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "3dd8f9b0-e050-4744-91d7-ae4c8d5b5cc9",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_location_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_location_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"LocationOfPresenceName\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Регион\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "04e94851-1455-4d83-a639-9f63042d66ce",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_match_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_match_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"MatchType\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"RELATED_KEYWORD\",\"Показ по ДРФ\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"SYNONYM\",\"Показ по семантическому соотв. кф\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"KEYWORD\",\"Показ по КФ\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"NONE\",\"Остальные случаи\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение3\", \"SectionType\", each \"Тип соответствия\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "74fe341e-f3b4-488b-9d66-4df7c8774812",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_network_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_network_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"AdNetworkType\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"AD_NETWORK\",\"Сеть\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"SEARCH\",\"Поиск\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение1\", \"SectionType\", each \"Тип размещения\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "810f6593-1988-428d-b0d4-b0776731ddee",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_os_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_os_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"MobilePlatform\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"OTHER\",\"Другие ОС\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"UNKNOWN\",\"Не определено\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение1\", \"SectionType\", each \"Операционная система\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "a13c696f-d52b-46bb-9246-bb1d53c59c84",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_placement_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_placement_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"Placement\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы\", \"SectionType\", each \"Площадки\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "dc3c3599-4622-4b58-ae14-4ab9f51adc6f",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_slot_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_slot_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"Slot\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"OTHER\",\"Другие блоки\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"PREMIUMBLOCK\",\"Спецразмещение\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"ALONE\",\"Эксклюзивное размещение\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"SUGGEST\",\"Реклама в саджесте\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"PRODUCT_GALLERY\",\"Товарная галерея\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение4\", \"SectionType\", each \"Рекламный блок\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "6aeff92c-5707-4c05-afe2-fbda1593b678",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yd_optimize_tarcat_stat",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yd_optimize_tarcat_stat\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Date\", type date}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"TargetingCategory\", \"Section\"}}),",
          "    #\"Замененное значение\" = Table.ReplaceValue(#\"Переименованные столбцы\",\"EXACT\",\"Целевые запросы\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение1\" = Table.ReplaceValue(#\"Замененное значение\",\"ALTERNATIVE\",\"Альтернативные запросы\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение2\" = Table.ReplaceValue(#\"Замененное значение1\",\"COMPETITOR\",\"Упоминание конкурентов\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение3\" = Table.ReplaceValue(#\"Замененное значение2\",\"BROADER\",\"Широкие запросы\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение4\" = Table.ReplaceValue(#\"Замененное значение3\",\"ACCESSORY\",\"Сопутствующие запросы\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Замененное значение5\" = Table.ReplaceValue(#\"Замененное значение4\",\"UNKNOWN\",\"Не определено\",Replacer.ReplaceText,{\"Section\"}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Замененное значение5\", \"SectionType\", each \"Категория таргетинга\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\ordinary_sections",
        "lineageTag": "2b2873c5-74f5-489e-841d-84ccb7cd15c6",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "yandex_ads",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = PostgreSQL.Database(\"powerbi-db.rs-app.ru:3477\", #\"PGSQL Database\"),",
          "    public_yandex_ads = Источник{[Schema=\"public\",Item=\"yandex_ads\"]}[Data],",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(public_yandex_ads,{{\"Id\", type text}, {\"CampaignId\", type text}, {\"AdGroupId\", type text}}),",
          "    #\"Переименованные столбцы\" = Table.RenameColumns(#\"Измененный тип\",{{\"Id\", \"AdId\"}})",
          "in",
          "    #\"Переименованные столбцы\""
        ],
        "queryGroup": "Datasets\\texts",
        "lineageTag": "5ef2d356-b979-4150-a5a2-8994341d87a7",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Служебные части речи",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZZdTiMxEITvkue9EeKB8KNEAkYKYSPelolWYRUGrgJsJuTHE65g32g9f6Gq2vsA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Малозначимые слова\" = _t]),",
          "    #\"Замененное значение\" = Table.ReplaceValue(Источник,\"-\",\" \",Replacer.ReplaceText,{\"Малозначимые слова\"}),",
          "    #\"Измененный тип\" = Table.TransformColumnTypes(#\"Замененное значение\",{{\"Малозначимые слова\", type text}}),",
          "    #\"Строки с примененным фильтром\" = Table.SelectRows(#\"Измененный тип\", each ([Малозначимые слова] <> \"\"))",
          "in",
          "    #\"Строки с примененным фильтром\""
        ],
        "queryGroup": "Datasets\\texts",
        "lineageTag": "ed540511-14ba-42a7-b4ce-215eea335c4c",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "accounts",
        "kind": "m",
        "expression": [
          "let",
          "    Источник = yd_optimize_camp_stat,",
          "    #\"Удаленные столбцы\" = Table.RemoveColumns(Источник,{\"SectionId\", \"SectionType\", \"Section\"}),",
          "    #\"Дублированный столбец\" = Table.DuplicateColumn(#\"Удаленные столбцы\", \"Login\", \"Копия Login\"),",
          "    #\"Переименованные столбцы1\" = Table.RenameColumns(#\"Дублированный столбец\",{{\"Копия Login\", \"Section\"}}),",
          "    #\"Добавлен пользовательский объект\" = Table.AddColumn(#\"Переименованные столбцы1\", \"SectionType\", each \"Аккаунт\")",
          "in",
          "    #\"Добавлен пользовательский объект\""
        ],
        "queryGroup": "Datasets\\custom_sections",
        "lineageTag": "a14702ab-ca4c-40ea-8ecc-71a0d73a80c0",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Навигация"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Проект",
        "kind": "m",
        "expression": "null meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "queryGroup": "control",
        "lineageTag": "15434dee-61f2-42c2-9b26-408af8b2a7e7",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "PGSQL Database",
        "kind": "m",
        "expression": "null meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "queryGroup": "control",
        "lineageTag": "e77d69e7-4ada-4c4f-9e2c-89a7cbb25b0e",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Datasets",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "control",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Datasets\\ads_material_sections",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Datasets\\custom_sections",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Datasets\\ordinary_sections",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      },
      {
        "folder": "Datasets\\texts",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ]
      },
      {
        "folder": "Datasets\\service",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"yd_optimize_camp_stat\",\"yd_optimize_adform_stat\",\"yd_optimize_adid_stat\",\"yd_optimize_agegen_stat\",\"yd_optimize_clcktype_stat\",\"yd_optimize_criteria_stat\",\"yd_optimize_critype_stat\",\"yd_optimize_device_stat\",\"yd_optimize_group_stat\",\"yd_optimize_hours\",\"yd_optimize_income_stat\",\"yd_optimize_location_stat\",\"yd_optimize_match_stat\",\"yd_optimize_network_stat\",\"yd_optimize_os_stat\",\"yd_optimize_placement_stat\",\"yd_optimize_slot_stat\",\"yd_optimize_tarcat_stat\",\"yandex_ads\",\"Проект\",\"href\",\"title1\",\"title2\",\"text\",\"callouts\",\"sitelink_title\",\"sitelink_desc\",\"image_url\",\"image_type\",\"graph_res\",\"image_names\",\"display_url\",\"day_of_week\",\"position_in_search\",\"words_with_stop\",\"Служебные части речи\",\"dataset\",\"_measures\",\"_firstconv\",\"accounts\",\"_project\",\"_sort_types\",\"PGSQL Database\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.114.864.0 (23.02)"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}